/* Deep dive — Computer Vision */
window.AtlasRef && window.AtlasRef.register('cv', {
  color: '#22D3EE',
  title: 'How machines see the world',
  lead: 'From raw pixels to convolution, from CNNs to Vision Transformers — the full course on computer vision. Every idea with the intuition, the exact math, a worked example, and code: image tensors, the sliding kernel, receptive fields, detection and segmentation, and the attention-based models eating the field.',
  sections: [

    { h: 'Images as tensors: pixels, channels & shape', p: [
      'A digital image is a grid of <b>pixels</b>. A grayscale image is a 2-D array <code>H×W</code> of intensities, usually 8-bit integers in <code>[0,255]</code> (or floats in <code>[0,1]</code> after normalisation). A colour image adds a <b>channel</b> axis: three planes — red, green, blue — stacked to give shape <code>H×W×3</code>. Each pixel is thus a length-3 vector.',
      'Deep-learning frameworks batch images into 4-D tensors. NumPy/TensorFlow use <b>NHWC</b> <code>(batch, height, width, channels)</code>; PyTorch prefers <b>NCHW</b> <code>(batch, channels, height, width)</code> because channel-first memory layout is faster for convolution. A batch of 32 RGB 224×224 images is <code>(32, 3, 224, 224)</code> in PyTorch. Nearly every shape bug in vision is a confused channel position or a missing batch axis.'],
      terms: [['Pixel', 'the smallest sample of an image; a scalar (gray) or a vector (colour).'], ['Channel', 'one colour/feature plane; RGB has 3, RGBA 4, a feature map may have hundreds.'], ['Resolution', 'the H×W pixel count, e.g. 1920×1080.'], ['Normalisation', 'rescale pixels (÷255, then subtract mean / divide by std) so training is stable.']],
      ex: [{ h: 'Reading and inspecting an image tensor', p: ['Load an image, inspect its shape and dtype, then normalise. The last axis of size 3 is the RGB channels; values start as bytes and become floats for the network.'],
        code: 'import numpy as np\nfrom PIL import Image\nimg = np.asarray(Image.open(\'cat.jpg\'))   # (H, W, 3) uint8\nprint(img.shape, img.dtype)                # (480, 640, 3) uint8\nx = img.astype(np.float32) / 255.0         # scale to [0,1]\nmean = np.array([0.485, 0.456, 0.406])\nstd  = np.array([0.229, 0.224, 0.225])\nx = (x - mean) / std                       # ImageNet normalisation' }],
      note: 'A 224×224 RGB image is 150,528 raw numbers. Treating them as an unstructured vector (as an MLP would) throws away the crucial fact that nearby pixels are related — convolution is the fix.' },

    { h: 'The convolution operation', p: [
      'Convolution slides a small grid of weights — the <b>kernel</b> (or filter) — across the image. At every position it multiplies the overlapping pixels by the kernel weights and <b>sums</b> the products into one output number. Sweeping over all positions produces a <b>feature map</b>. This local, repeated dot product is the entire computational core of a CNN.',
      'Formally, for a kernel <code>K</code> of size <code>k×k</code> and input <code>I</code>, output pixel <code>(i,j)</code> is the sum-of-products over the kernel window. (Deep-learning "convolution" is technically <b>cross-correlation</b> — the kernel is not flipped — but the network learns the weights either way, so the distinction is cosmetic.)',
      'Because the same kernel is reused at every location, convolution detects a pattern <i>wherever</i> it appears. Different kernels detect different things: edges, blobs, textures, and — in deep layers — eyes, wheels, and faces.'],
      eqn: 'S(i,j) = (I * K)(i,j) = Σ_m Σ_n  I(i+m, j+n) · K(m,n)',
      ex: [{ h: 'A 3×3 convolution by hand', p: ['Take a 3×3 input patch and a 3×3 vertical <b>Sobel</b> edge kernel. Multiply element-wise and sum. A large positive response means a strong left-to-right intensity change — a vertical edge.'],
        eqn: 'I = [10 10 10 ; 10 10 10 ; 80 80 80]\nK = [-1 0 1 ; -2 0 2 ; -1 0 1]   (Sobel-x)\nS = (-1·10 +0·10 +1·10) + (-2·10 +0 +2·10) + (-1·80 +0 +2·80... )\n  = 0 + 0 + 0 = 0   here (no horizontal change)  →  flip kernel to Sobel-y to catch the strong top→bottom edge' }],
      code: 'import numpy as np\n\ndef conv2d(image, kernel):\n    """Valid 2-D cross-correlation (no padding, stride 1)."""\n    kh, kw = kernel.shape\n    H, W = image.shape\n    out = np.zeros((H - kh + 1, W - kw + 1))\n    for i in range(out.shape[0]):\n        for j in range(out.shape[1]):\n            patch = image[i:i+kh, j:j+kw]\n            out[i, j] = np.sum(patch * kernel)   # sum of products\n    return out\n\nimg = np.array([[10,10,10],[10,10,10],[80,80,80]], float)\nsobel_y = np.array([[-1,-2,-1],[0,0,0],[1,2,1]], float)\nconv2d(img, sobel_y)   # -> [[280]]  strong horizontal edge detected' },

    { h: 'Kernels, filters & feature maps', p: [
      'A <b>kernel</b> is the 2-D weight grid; a <b>filter</b> spans all input channels — for a 3-channel input a single 3×3 filter has shape <code>3×3×3</code> and produces one output channel by summing across channels. A conv <b>layer</b> stacks many filters, each yielding its own feature map, so a layer maps <code>C_in</code> channels to <code>C_out</code> feature maps.',
      'Early layers learn generic detectors (oriented edges, colour gradients) that look remarkably like the Gabor filters in biological vision. Deeper layers compose these into textures, then parts, then whole objects — a learned hierarchy of features, no hand-engineering required.',
      'A <b>1×1 convolution</b> mixes channels without looking at spatial neighbours; it is a per-pixel linear layer used to cheaply change channel depth (the bottleneck trick in ResNet/Inception).'],
      eqn: 'filter shape = (k, k, C_in)     layer weights = (C_out, C_in, k, k)     params = C_out·C_in·k·k + C_out',
      terms: [['Feature map', 'the 2-D activation output of one filter.'], ['Depth / channels', 'number of feature maps stacked at a layer.'], ['Bias', 'one learned scalar added per output channel.'], ['1×1 conv', 'channel mixing / dimensionality change with no spatial extent.']],
      ex: [{ h: 'Counting parameters in a conv layer', p: ['A layer taking 64 input channels to 128 output channels with 3×3 filters has 128·64·3·3 + 128 = 73,856 weights — independent of the image size, because the same filters are reused everywhere. Compare a fully-connected layer over a 224×224×64 input: billions of weights.'],
        eqn: 'params = 128·64·3·3 + 128 = 73,728 + 128 = 73,856' }] },

    { h: 'Stride, padding, dilation & pooling', p: [
      '<b>Stride</b> is the step size of the sliding window. Stride 1 visits every position; stride 2 skips every other one, halving the output resolution and cheaply downsampling. <b>Padding</b> adds a border of (usually zero) pixels so the kernel can sit on edge pixels; <code>same</code> padding keeps the output the same size as the input, <code>valid</code> padding uses none and shrinks it. <b>Dilation</b> inserts gaps between kernel taps, enlarging the field of view without adding weights or losing resolution — the key trick in DeepLab\'s atrous convolutions. The output-size formula below ties all three together and is worth memorising.',
      '<b>Pooling</b> is the other way to downsample: it summarises each small window into one value. <b>Max pooling</b> keeps the strongest activation — "was this feature present anywhere in this region?" — giving a little translation invariance and discarding precise position; <b>average pooling</b> takes the mean. A 2×2 pool with stride 2 quarters the spatial area and has no learnable parameters. Modern nets often replace it with <b>strided convolutions</b> (learned downsampling), but <b>global average pooling</b> — collapsing each entire feature map to one number — remains the standard bridge from convolutional features to a classifier, replacing bulky fully-connected layers.'],
      eqn: 'out = floor( (in + 2·pad − dilation·(k−1) − 1) / stride ) + 1\nmaxpool(region) = max over window     avgpool(region) = mean over window     GAP: (C,H,W) → (C,)',
      ex: [{ h: 'Sizing a strided conv layer', p: ['A 224×224 input through a 3×3 kernel with stride 2 and padding 1 gives 112×112. This "halve the spatial size, double the channels" pattern is the backbone rhythm of almost every CNN.'],
        eqn: 'out = floor((224 + 2·1 − 1·(3−1) − 1)/2) + 1 = floor(223/2) + 1 = 111 + 1 = 112' },
        { h: 'Max pooling a 4×4 map', p: ['A 2×2 max-pool with stride 2 over a 4×4 map produces a 2×2 output, each cell the maximum of its quadrant — downsampling by 2× while keeping the salient responses and cutting the next layer\'s compute fourfold.'],
        code: 'import numpy as np\nx = np.array([[1,3,2,4],[5,6,1,2],[7,8,3,0],[1,2,9,4]], float)\ndef maxpool2x2(a):\n    H, W = a.shape\n    return a.reshape(H//2,2,W//2,2).max(axis=(1,3))\nmaxpool2x2(x)   # -> [[6,4],[8,9]]' }],
      terms: [['Stride', 'step of the window; s>1 downsamples.'], ['Same / valid padding', 'keep size vs. shrink by k−1 (no pad).'], ['Dilation', 'spacing between kernel taps; widens receptive field for free.'], ['Global avg pooling', '(C,H,W)→(C,); links conv features to the head.']],
      note: 'Pooling trades spatial precision for invariance and efficiency — great for classification, but detection and segmentation must recover that lost resolution (via skip connections or upsampling).' },

    { h: 'Receptive field, weight sharing & equivariance', p: [
      'The <b>receptive field</b> of a neuron is the region of the original image that can influence it. Stacking convolutions and pooling grows it: a neuron deep in the network "sees" a large context even though each individual kernel is tiny. This is why depth matters — it is how a network goes from detecting edges to recognising whole scenes.',
      '<b>Weight sharing</b> — reusing one kernel across every position — is what makes CNNs efficient and gives them <b>translation equivariance</b>: shift the input, and the feature map shifts by the same amount. Combined with pooling\'s local invariance, the network recognises an object regardless of where it sits in the frame. (Full translation <i>invariance</i> is approximate, not exact — a known limitation.)'],
      eqn: 'RF stacking:  RF_L = RF_{L−1} + (k_L − 1) · Π(strides before L)',
      terms: [['Receptive field', 'input region a neuron depends on.'], ['Weight sharing', 'same kernel weights reused at all positions.'], ['Equivariance', 'shift input → output shifts identically.'], ['Invariance', 'output unchanged under a transformation (approx. from pooling).']],
      ex: [{ h: 'Growing the receptive field', p: ['Two stacked 3×3 convolutions (stride 1) give each output neuron a 5×5 receptive field, using 2·9=18 weights instead of a single 5×5 kernel\'s 25 — cheaper and more non-linear. Three 3×3s reach 7×7. This "small kernels, more depth" insight is the core of VGG.'],
        eqn: 'RF: 3 → 3+(3−1) = 5 → 5+(3−1) = 7   (per 3×3 layer, stride 1)' }] },

    { h: 'CNN architectures — the lineage', p: [
      'The history of image classification is a ladder of architectural ideas, each fixing the previous bottleneck. <b>LeNet</b> proved convolutions work; <b>AlexNet</b> scaled them onto GPUs with ReLU and dropout and won ImageNet 2012, igniting deep learning. <b>VGG</b> showed that depth with uniform 3×3 filters helps. <b>Inception</b> ran multiple kernel sizes in parallel for efficiency. <b>ResNet</b>\'s <b>skip connections</b> let gradients flow through hundreds of layers by learning residuals <code>F(x)+x</code> instead of full mappings — the single most important trick that made very deep nets trainable. <b>EfficientNet</b> then found the optimal balance of depth, width, and resolution via compound scaling.'],
      table: { cols: ['Model (year)', 'Key idea', 'Depth / notes'], rows: [
        ['LeNet-5 (1998)', 'first practical CNN; conv + pool + FC', '~7 layers; digit recognition'],
        ['AlexNet (2012)', 'ReLU, dropout, GPU training, big data', '8 layers; won ImageNet, sparked the boom'],
        ['VGG-16/19 (2014)', 'deep stacks of 3×3 convs only', '16–19 layers; simple, heavy (138M params)'],
        ['GoogLeNet / Inception (2014)', 'parallel multi-scale branches + 1×1 bottlenecks', '22 layers; efficient, fewer params'],
        ['ResNet (2015)', 'residual skip connections F(x)+x', '18–152 layers; trains very deep nets'],
        ['EfficientNet (2019)', 'compound scaling of depth·width·resolution', 'B0–B7; state-of-art accuracy/FLOP']] },
      ex: [{ h: 'Why the residual block works', p: ['A residual block computes <code>y = F(x) + x</code>: the layer only needs to learn the <i>change</i> from its input. If the optimal function is close to identity, the weights can go to zero — trivially learnable. The <code>+x</code> shortcut also gives gradients a direct highway backward, curing the vanishing-gradient problem that capped earlier nets around 20 layers.'],
        code: 'import torch.nn as nn\nclass ResidualBlock(nn.Module):\n    def __init__(self, c):\n        super().__init__()\n        self.conv1 = nn.Conv2d(c, c, 3, padding=1)\n        self.bn1   = nn.BatchNorm2d(c)\n        self.conv2 = nn.Conv2d(c, c, 3, padding=1)\n        self.bn2   = nn.BatchNorm2d(c)\n    def forward(self, x):\n        out = torch.relu(self.bn1(self.conv1(x)))\n        out = self.bn2(self.conv2(out))\n        return torch.relu(out + x)     # skip connection' }] },

    { h: 'Training in practice: augmentation & transfer learning', p: [
      'A model only generalises to variations it has seen. <b>Data augmentation</b> synthesises new training views by applying label-preserving transforms, cheaply enlarging the dataset and acting as a powerful regulariser. Geometric transforms (<b>flips, crops, rotations, scaling</b>) teach spatial invariance; photometric ones (<b>colour jitter, brightness, contrast, blur</b>) teach robustness to lighting. Mixing augmentations go further: <b>Mixup</b> blends two images and their labels linearly, <b>CutMix</b> pastes a patch of one onto another, and <b>RandAugment</b> samples random operation chains — all blur decision boundaries and lift accuracy. Caveat: choose transforms that preserve the label — a vertical flip is fine for a cat but wrong for a digit or road sign.',
      'Training a big CNN from scratch needs millions of labelled images. <b>Transfer learning</b> reuses a network already pretrained on ImageNet: its early/middle layers have learned general visual features that transfer to almost any vision task. You keep the <b>backbone</b> and swap the final classifier head for your own classes.',
      'Two regimes: <b>feature extraction</b> freezes the backbone and trains only the new head (fast, few labels, small data); <b>fine-tuning</b> unfreezes some or all layers and continues training at a low learning rate to adapt features to your domain (more data, higher accuracy). Rule of thumb — small/similar data: freeze; large/different data: fine-tune more layers.'],
      table: { cols: ['Your data', 'Similar to pretrain?', 'Strategy'], rows: [
        ['Small', 'Similar', 'freeze backbone, train head only'],
        ['Small', 'Different', 'freeze early layers, train later + head'],
        ['Large', 'Similar', 'fine-tune whole net, low LR'],
        ['Large', 'Different', 'fine-tune all (or even train from scratch)']] },
      ex: [{ h: 'A torchvision augmentation pipeline', p: ['Randomised transforms are applied fresh every epoch, so the model essentially never sees the exact same image twice; test-time uses only deterministic resize + normalise.'],
        code: 'from torchvision import transforms\ntrain_tf = transforms.Compose([\n    transforms.RandomResizedCrop(224),\n    transforms.RandomHorizontalFlip(),\n    transforms.ColorJitter(0.4, 0.4, 0.4, 0.1),\n    transforms.ToTensor(),\n    transforms.Normalize([0.485,0.456,0.406],\n                         [0.229,0.224,0.225]),\n])' },
        { h: 'Fine-tuning a pretrained ResNet-50', p: ['Load ImageNet weights, replace the 1000-way head with a head for your N classes, and train. Freeze the backbone first for a quick baseline; then unfreeze and drop the learning rate to squeeze out accuracy.'],
        code: 'import torch, torch.nn as nn\nfrom torchvision import models\n\nnet = models.resnet50(weights=\'IMAGENET1K_V2\')\nfor p in net.parameters():          # 1) freeze backbone\n    p.requires_grad = False\nnet.fc = nn.Linear(net.fc.in_features, 10)   # 2) new head, 10 classes\n\nopt = torch.optim.Adam(net.fc.parameters(), lr=1e-3)\nloss_fn = nn.CrossEntropyLoss()\n# ... train head ...\nfor p in net.layer4.parameters():   # 3) unfreeze last block, fine-tune\n    p.requires_grad = True\nopt = torch.optim.Adam(filter(lambda p: p.requires_grad,\n                              net.parameters()), lr=1e-4)' }],
      note: 'Transfer learning is why a startup with 2,000 labelled images can hit production accuracy — the hard, expensive representation learning was already paid for by ImageNet/CLIP-scale pretraining.' },

    { h: 'Object detection: from sliding windows to YOLO', p: [
      'Classification says <i>what</i>; <b>detection</b> says what <i>and where</i>, drawing a bounding box around every object. The naive approach slides a classifier over every window at every scale — hopelessly slow. <b>R-CNN</b> instead proposes ~2000 candidate regions and classifies each, but running the CNN per region is still costly. <b>Fast R-CNN</b> runs the backbone once and pools features per region; <b>Faster R-CNN</b> adds a learned <b>Region Proposal Network</b>, making it end-to-end. These <b>two-stage</b> detectors are accurate but slower.',
      '<b>One-stage</b> detectors — <b>YOLO</b> ("You Only Look Once") and <b>SSD</b> — skip the proposal step, predicting boxes and classes directly on a dense grid in a single pass. They are far faster (real-time) at a modest accuracy cost, and dominate practical deployment. Both families predict offsets relative to predefined <b>anchor boxes</b> — reference shapes of assorted sizes/aspect ratios tiled across the image — which the network refines.'],
      table: { cols: ['Detector', 'Type', 'Trait'], rows: [
        ['R-CNN (2014)', 'two-stage', 'region proposals + per-region CNN; slow'],
        ['Fast R-CNN (2015)', 'two-stage', 'shared conv, RoI pooling; faster'],
        ['Faster R-CNN (2015)', 'two-stage', 'learned RPN; end-to-end, accurate'],
        ['SSD (2016)', 'one-stage', 'multi-scale anchors, single pass'],
        ['YOLO (2015→v8+)', 'one-stage', 'dense grid prediction; real-time'],
        ['DETR (2020)', 'transformer', 'set prediction, no anchors/NMS']] },
      terms: [['Bounding box', 'a rectangle (x,y,w,h) localising an object.'], ['Anchor box', 'predefined reference box the model refines via offsets.'], ['RoI pooling', 'extract a fixed-size feature grid from a region.'], ['Confidence', 'objectness × class probability per prediction.']],
      ex: [{ h: 'Anchors on a grid', p: ['YOLO divides the image into an S×S grid; each cell predicts B boxes as offsets from anchors, plus an objectness score and class probabilities. A 13×13 grid with 3 anchors and 80 classes emits 13·13·3·(4+1+80) = 43,095 numbers, filtered down to final detections by confidence thresholding and NMS.'],
        eqn: 'per prediction = (t_x, t_y, t_w, t_h, objectness, p_1..p_C)\nbox: b_x = σ(t_x)+c_x ,  b_w = a_w·e^{t_w}   (offset from anchor a)' }] },

    { h: 'IoU, Non-Max Suppression & mAP', p: [
      'Detection needs a way to score box quality. <b>Intersection over Union (IoU)</b> measures overlap between a predicted and a ground-truth box: the area of their intersection divided by the area of their union. IoU=1 is a perfect match, 0 is no overlap; a prediction usually counts as correct if IoU ≥ 0.5.',
      'A detector fires many overlapping boxes on one object. <b>Non-Max Suppression (NMS)</b> cleans this up: keep the highest-confidence box, discard every other box with IoU above a threshold, repeat. To score a detector overall, <b>Average Precision (AP)</b> is the area under its precision–recall curve for one class, and <b>mean Average Precision (mAP)</b> averages AP across all classes (often over several IoU thresholds, e.g. COCO\'s mAP@[.5:.95]).'],
      eqn: 'IoU = area(A ∩ B) / area(A ∪ B) = I / (area_A + area_B − I)        mAP = mean over classes of AP',
      ex: [{ h: 'IoU by hand', p: ['Box A = (0,0,2,2) and box B = (1,1,3,3) (as x1,y1,x2,y2). The intersection is the square (1,1)–(2,2), area 1. Each box has area 4, so the union is 4+4−1 = 7. IoU = 1/7 ≈ 0.14 — poor overlap, so this prediction would be counted a miss at the 0.5 threshold.'],
        eqn: 'inter = 1·1 = 1     union = 4 + 4 − 1 = 7     IoU = 1/7 ≈ 0.143' }],
      code: 'import numpy as np\n\ndef iou(a, b):\n    """Boxes as [x1, y1, x2, y2]."""\n    x1 = max(a[0], b[0]); y1 = max(a[1], b[1])\n    x2 = min(a[2], b[2]); y2 = min(a[3], b[3])\n    inter = max(0, x2 - x1) * max(0, y2 - y1)\n    area_a = (a[2]-a[0]) * (a[3]-a[1])\n    area_b = (b[2]-b[0]) * (b[3]-b[1])\n    return inter / (area_a + area_b - inter + 1e-9)\n\ndef nms(boxes, scores, thr=0.5):\n    idx = np.argsort(scores)[::-1]        # highest score first\n    keep = []\n    while len(idx):\n        i = idx[0]; keep.append(i)\n        idx = [j for j in idx[1:] if iou(boxes[i], boxes[j]) < thr]\n    return keep\n\niou([0,0,2,2], [1,1,3,3])   # -> 0.1428...' },

    { h: 'Image segmentation', p: [
      'Segmentation classifies <i>every pixel</i>, not just boxes. <b>Semantic segmentation</b> labels each pixel with a class (all "car" pixels alike, instances merged). <b>Instance segmentation</b> separates individual objects (car #1 vs car #2). <b>Panoptic segmentation</b> unifies both — every pixel gets a class, and "thing" classes also get instance IDs while "stuff" (sky, road) does not.',
      'The classic architectures: <b>FCN</b> made segmentation end-to-end by replacing dense layers with convolutions and upsampling. <b>U-Net</b> — an encoder–decoder with <b>skip connections</b> linking matching resolutions — recovers fine detail and dominates medical imaging. <b>DeepLab</b> uses <b>atrous/dilated convolutions</b> and spatial pyramid pooling for large receptive fields at high resolution. <b>Mask R-CNN</b> extends Faster R-CNN with a per-region mask head, the go-to for instance segmentation.'],
      table: { cols: ['Task', 'Output', 'Example model'], rows: [
        ['Semantic', 'per-pixel class (no instances)', 'FCN, U-Net, DeepLab'],
        ['Instance', 'per-object mask + class', 'Mask R-CNN'],
        ['Panoptic', 'class for all + IDs for things', 'Panoptic FPN, Mask2Former']] },
      terms: [['Encoder–decoder', 'downsample to features, upsample back to full resolution.'], ['Skip connection', 'pass high-res features across to the decoder (U-Net).'], ['Atrous / dilated conv', 'wide receptive field without losing resolution (DeepLab).'], ['Transposed conv', 'learned upsampling that increases spatial size.']],
      ex: [{ h: 'The U-Net shape', p: ['The encoder halves resolution and doubles channels four times (contracting path); the decoder mirrors it, upsampling and <b>concatenating</b> the matching encoder feature map at each step so precise boundaries survive. The U shape and its cross-links are why it needs so few training images.'],
        eqn: '572² → 284² → 140² → 68² → 32²   (contract)\n32² → 68² → 140² → 284² → 388²   (expand, + skip concats)' }] },

    { h: 'Vision Transformers, DETR & SAM', p: [
      'The <b>Vision Transformer (ViT)</b> drops convolution entirely. It cuts the image into fixed <b>patches</b> (e.g. 16×16), flattens each into a vector, linearly projects it into a <b>token</b>, adds a learned <b>positional embedding</b>, and feeds the sequence to a standard transformer encoder. <b>Self-attention</b> lets every patch attend to every other, giving a global receptive field from layer one — unlike a CNN\'s slowly-growing local field. Given enough data (or strong pretraining), ViTs match or beat CNNs.',
      'Transformers reshaped downstream tasks too. <b>DETR</b> casts detection as direct <b>set prediction</b>: a transformer emits a fixed set of boxes matched to ground truth by bipartite (Hungarian) matching, eliminating anchors and NMS. <b>SAM</b> (Segment Anything) is a promptable foundation model that, trained on a billion masks, segments essentially any object from a point or box prompt — zero-shot. <b>CLIP</b>-style image–text pretraining underpins much of modern open-vocabulary vision.'],
      eqn: 'tokens = patchify(image) → linear → + pos_emb        Attention(Q,K,V) = softmax(QKᵀ/√d) V',
      terms: [['Patch', 'a small image tile (e.g. 16×16) treated as one token.'], ['[CLS] token', 'a learned token whose output represents the whole image for classification.'], ['Positional embedding', 'encodes where each patch sits, since attention is order-agnostic.'], ['DETR / SAM / CLIP', 'set-prediction detection / promptable segmentation / image-text alignment.']],
      ex: [{ h: 'Patchifying an image into tokens', p: ['A 224×224 image split into 16×16 patches yields (224/16)² = 196 patches; each 16·16·3 = 768-dim patch is projected to the model width and prepended with a [CLS] token, giving a length-197 sequence for the transformer. The number of tokens — not the pixel count — sets the attention cost.'],
        code: 'import torch, torch.nn as nn\n\nclass PatchEmbed(nn.Module):\n    def __init__(self, img=224, patch=16, dim=768, ch=3):\n        super().__init__()\n        self.n = (img // patch) ** 2                 # 196 patches\n        # a strided conv is an efficient patchify + linear projection\n        self.proj = nn.Conv2d(ch, dim, kernel_size=patch, stride=patch)\n        self.cls  = nn.Parameter(torch.zeros(1, 1, dim))\n        self.pos  = nn.Parameter(torch.zeros(1, self.n + 1, dim))\n    def forward(self, x):                            # x: (B,3,224,224)\n        x = self.proj(x).flatten(2).transpose(1, 2)  # (B,196,768)\n        cls = self.cls.expand(x.size(0), -1, -1)\n        x = torch.cat([cls, x], dim=1) + self.pos    # (B,197,768)\n        return x' }],
      note: 'CNNs bake in locality and translation equivariance as a prior; ViTs learn structure from data instead. Hybrids (e.g. Swin Transformer, ConvNeXt) blend both — local windows plus global attention.' },

    { h: 'Tasks & loss functions', p: [
      'Each vision task pairs an output format with a loss that measures its error. <b>Classification</b> outputs class probabilities via softmax and minimises <b>cross-entropy</b> against the one-hot label. <b>Detection</b> uses a compound loss: cross-entropy (or focal loss, which down-weights easy negatives) for the class, plus a box-regression loss (smooth-L1, or IoU-based GIoU/DIoU) for localisation. <b>Segmentation</b> applies per-pixel cross-entropy, often combined with <b>Dice loss</b> which directly optimises overlap and handles class imbalance in medical images.',
      'The pattern is always the same: define what "correct" means, encode it as a differentiable loss, and backpropagate. Picking the right loss — focal for imbalance, Dice for thin structures, IoU-based for boxes — often matters more than the architecture.'],
      eqn: 'CE = −Σ y_c log(p_c)      Focal = −(1−p_t)^γ log(p_t)      Dice = 1 − 2|P∩G| / (|P|+|G|)',
      table: { cols: ['Task', 'Output', 'Typical loss'], rows: [
        ['Classification', 'class probabilities (softmax)', 'cross-entropy'],
        ['Detection', 'boxes + classes', 'focal/CE (class) + smooth-L1 / GIoU (box)'],
        ['Semantic seg.', 'per-pixel class map', 'pixel cross-entropy + Dice'],
        ['Instance seg.', 'masks + boxes + classes', 'Mask R-CNN multi-task loss'],
        ['Metric learning', 'embeddings', 'triplet / contrastive (InfoNCE)']] },
      ex: [{ h: 'Cross-entropy for image classification', p: ['For a true class and softmax outputs, cross-entropy reduces to −log(p_correct): near zero when the model is confidently right, exploding when confidently wrong. This is the same maximum-likelihood loss used throughout ML, applied to the CNN or ViT\'s final logits.'],
        code: 'import torch, torch.nn.functional as F\nlogits = torch.tensor([[2.0, 0.5, 0.1]])   # 1 image, 3 classes\ntarget = torch.tensor([0])                  # true class = 0\nloss = F.cross_entropy(logits, target)      # softmax + NLL in one\nprint(loss.item())   # -> 0.417  (confident & correct -> low)' }] },
  ]
});
