/* Deep dive — Data Engineering: ETL, pipelines & the modern data stack */
window.AtlasRef && window.AtlasRef.register('etl', {
  color: '#22D3EE',
  title: 'Moving data at scale: ETL, pipelines & the modern stack',
  lead: 'How raw events become clean, trustworthy tables that feed dashboards and models. The full tour — ingestion, orchestration, distributed processing with Spark, streaming with Kafka, the warehouse-vs-lake-vs-lakehouse debate, dimensional modeling, data quality, and feature stores — each with the exact vocabulary, a worked example, and real SQL/PySpark.',
  sections: [

    { h: 'ETL vs ELT — and why ELT won', p: [
      'A data pipeline does three jobs: <b>Extract</b> data from sources, <b>Transform</b> it into a clean shape, and <b>Load</b> it into a destination. The historic order was <b>ETL</b>: transform on a separate box <i>before</i> loading, because the warehouse was expensive and rigid. The modern order is <b>ELT</b>: load raw data into a cloud warehouse first, then transform <i>inside</i> it with SQL.',
      'ELT won because cloud warehouses (Snowflake, BigQuery, Redshift) <b>decoupled storage from compute</b> and made both cheap and elastic. Loading raw is fast and lossless — you keep the original so you can re-derive anything later. Transformation becomes version-controlled SQL that any analyst can read, instead of opaque Java jobs on a bespoke ETL server.'],
      table: { cols: ['Aspect', 'ETL (transform-first)', 'ELT (load-first)'], rows: [
        ['Transform location', 'separate engine before load', 'inside the warehouse/lake'],
        ['Raw data kept?', 'often discarded', '<b>yes</b> — replayable, auditable'],
        ['Schema decided', 'up front (schema-on-write)', 'later (schema-on-read)'],
        ['Who owns transforms', 'data engineers, custom code', 'analysts + engineers, SQL/dbt'],
        ['Best fit', 'legacy, tight compliance, small compute', 'cloud warehouses, large elastic compute']] },
      note: 'ELT is not universally superior: heavy PII masking, GDPR minimisation, or when the destination cannot transform (a plain object store) still argue for transforming in flight.' },

    { h: 'Data ingestion — batch, streaming, APIs & CDC', p: [
      '<b>Ingestion</b> is the extract step: getting bytes out of a source and into your platform. <b>Batch</b> ingestion moves bounded chunks on a schedule (nightly dump of yesterday\'s orders) — simple, cheap, high-throughput, but latent. <b>Streaming</b> ingestion moves each record as it happens (a click, a payment) — low latency, but harder to get right.',
      'Sources fall into a few families: <b>databases</b> (pull via JDBC or, better, <b>change-data-capture</b>), <b>APIs</b> (paginated REST/GraphQL, rate-limited, often needing incremental cursors), <b>files</b> (CSV/Parquet landing in S3), and <b>event streams</b> (Kafka, Kinesis).',
      '<b>Change-Data-Capture (CDC)</b> is the key technique for keeping a warehouse in sync with an operational database. Instead of re-scanning the whole table, CDC reads the database\'s <i>write-ahead log</i> (e.g. Postgres WAL, MySQL binlog) and streams every insert/update/delete as an event. Tools like Debezium turn a transactional DB into a real-time source with near-zero load on the primary.'],
      terms: [['Full load', 'copy the entire source every run — simple, wasteful.'], ['Incremental load', 'copy only rows changed since a high-water mark (updated_at, id).'], ['CDC', 'stream row-level changes from the DB transaction log.'], ['Backfill', 're-ingest historical data into a new or fixed pipeline.'], ['High-water mark', 'the max cursor value seen, stored to resume next run.'], ['Watermark (streaming)', 'a bound on event-time lateness, used to close windows.']],
      ex: [{ h: 'Incremental extract with a high-water mark', p: ['Instead of pulling every order each night, pull only rows updated since the last successful run. Store the new maximum <code>updated_at</code> so the next run resumes there. This is the workhorse of batch ingestion.'],
        code: 'SELECT order_id, customer_id, amount, status, updated_at\nFROM   orders\nWHERE  updated_at > :last_high_water_mark   -- e.g. \'2026-07-21 03:00:00\'\nORDER  BY updated_at;\n-- after load succeeds, persist MAX(updated_at) as the new mark' }] },

    { h: 'The DAG: a pipeline as a graph of tasks', p: [
      'Every non-trivial pipeline is modeled as a <b>DAG</b> — a Directed Acyclic Graph. <b>Nodes</b> are tasks (extract, transform, load, validate); <b>edges</b> are dependencies (B runs only after A succeeds). <b>Directed</b> means dependencies have a direction; <b>Acyclic</b> means no task can depend on itself transitively — otherwise the schedule could never start.',
      'The DAG buys you three things: an unambiguous <b>execution order</b> (topological sort), <b>parallelism</b> (independent branches run at once), and precise <b>recovery</b> (a failed task reruns without redoing upstream work). Almost every orchestrator — Airflow, Prefect, Dagster, dbt — compiles your pipeline into a DAG under the hood.'],
      eqn: 'extract_orders ─┐\n                 ├─▶ join_and_clean ─▶ load_fact ─▶ validate ─▶ publish\nextract_users  ─┘',
      note: 'A DAG describes structure, not timing. When it runs (cron, event, sensor) and how far back (the "data interval") are separate concerns the scheduler owns.' },

    { h: 'Orchestration — Airflow, Prefect & Dagster', p: [
      'An <b>orchestrator</b> schedules the DAG, runs tasks in dependency order, retries failures, tracks state, backfills history, and surfaces logs and alerts. It is the control plane of a data platform.',
      '<b>Airflow</b> is the incumbent: mature, huge operator ecosystem, DAGs written as Python. Its roots show — scheduling is task-centric and testing locally can be awkward. <b>Prefect</b> reframes flows as ordinary Python functions with decorators, dynamic at runtime, easy local dev. <b>Dagster</b> is <i>asset-centric</i>: you declare the tables/datasets you want to exist and their dependencies, and it works out the tasks — which makes lineage and data-quality first-class.'],
      table: { cols: ['Tool', 'Model', 'Strength'], rows: [
        ['Airflow', 'task DAGs (Python)', 'ubiquity, operators, battle-tested at scale'],
        ['Prefect', 'flows as functions', 'dynamic graphs, great local/dev ergonomics'],
        ['Dagster', 'software-defined assets', 'lineage, typing & data quality baked in']] },
      ex: [{ h: 'A tiny Airflow DAG', p: ['Three tasks wired extract → transform → load. The <code>>></code> operator declares dependencies; Airflow derives the graph, schedules it daily, and retries each task twice on failure.'],
        code: 'from airflow import DAG\nfrom airflow.operators.python import PythonOperator\nimport pendulum\n\nwith DAG(\n    dag_id=\'orders_elt\',\n    schedule=\'@daily\',\n    start_date=pendulum.datetime(2026, 1, 1, tz=\'UTC\'),\n    catchup=False,\n    default_args={\'retries\': 2},\n) as dag:\n\n    extract = PythonOperator(task_id=\'extract\', python_callable=extract_orders)\n    transform = PythonOperator(task_id=\'transform\', python_callable=clean_orders)\n    load = PythonOperator(task_id=\'load\', python_callable=load_to_warehouse)\n\n    extract >> transform >> load   # dependency edges define the DAG' }] },

    { h: 'Idempotency & delivery semantics', p: [
      'Pipelines fail and retry, so tasks must be <b>idempotent</b>: running the same task twice with the same inputs leaves the system in the same state as running it once. The classic pattern is <b>delete-insert by partition</b> (or <code>MERGE</code>): a rerun overwrites its own slice rather than appending duplicates.',
      'Networks and brokers force a choice of <b>delivery guarantee</b>. <b>At-most-once</b> may drop data (fire and forget). <b>At-least-once</b> never drops but may duplicate — the common default, made safe by idempotent writes downstream. <b>Exactly-once</b> is the ideal but expensive: it needs transactional coordination (offsets committed atomically with output), e.g. Kafka transactions or Flink\'s checkpoint-based two-phase commit.'],
      terms: [['Idempotent write', 'MERGE / delete-insert so replays don\'t duplicate.'], ['At-most-once', 'no retries; data loss possible.'], ['At-least-once', 'retries until ack; duplicates possible.'], ['Exactly-once', 'each record affects output once; needs transactions.'], ['Dedup key', 'a unique id (event_id) used to drop replays.'], ['Effectively-once', 'at-least-once delivery + idempotent sink = no visible dup.']],
      ex: [{ h: 'Idempotent load with MERGE (upsert)', p: ['A <code>MERGE</code> keyed on <code>order_id</code> updates existing rows and inserts new ones. Rerun the same batch and the result is identical — no duplicates — which is what makes at-least-once delivery survivable.'],
        code: 'MERGE INTO warehouse.dim_orders AS t\nUSING staging.orders_batch  AS s\n  ON t.order_id = s.order_id\nWHEN MATCHED THEN UPDATE SET\n    t.status = s.status, t.amount = s.amount, t.updated_at = s.updated_at\nWHEN NOT MATCHED THEN INSERT (order_id, customer_id, amount, status, updated_at)\n    VALUES (s.order_id, s.customer_id, s.amount, s.status, s.updated_at);' }] },

    { h: 'Transformation with dbt and with Spark', p: [
      'Two dominant transform styles. <b>dbt (data build tool)</b> is the SQL-native, in-warehouse approach: every transformation is a <code>SELECT</code> saved as a <i>model</i>; dbt handles dependency ordering (via <code>ref()</code>), materialisation (view/table/incremental), testing, and documentation. It is the T of ELT and the reason analysts now own transformation.',
      '<b>Spark</b> is the code-native, out-of-warehouse approach for data too big or too unstructured for pure SQL — petabyte joins, ML feature pipelines, semi-structured logs. You write Python/Scala over distributed data. Many stacks use both: Spark for heavy lifting into the lake, dbt for business logic in the warehouse.'],
      ex: [{ h: 'A dbt model with ref() and a test', p: ['This model builds daily revenue from a staging model. <code>ref()</code> tells dbt the dependency, so it builds <code>stg_orders</code> first and knows the lineage. A schema test then asserts the output is never null.'],
        code: '-- models/marts/daily_revenue.sql\nSELECT\n    DATE(order_ts)        AS order_date,\n    COUNT(*)              AS orders,\n    SUM(amount)           AS revenue\nFROM {{ ref(\'stg_orders\') }}     -- dbt resolves & orders the dependency\nWHERE status = \'completed\'\nGROUP BY 1\n\n-- models/marts/schema.yml\n-- models:\n--   - name: daily_revenue\n--     columns:\n--       - name: revenue\n--         tests: [not_null]' }],
      note: 'dbt\'s incremental materialisation + a unique_key gives you idempotent, append-or-merge transforms without hand-writing MERGE.' },

    { h: 'Distributed processing with Spark', p: [
      'Spark processes data that does not fit on one machine by <b>partitioning</b> it across a cluster and running the same code on each slice in parallel. The original API is the <b>RDD</b> (Resilient Distributed Dataset) — a low-level, typed collection. The modern API is the <b>DataFrame</b>: a distributed table that the <b>Catalyst optimizer</b> can rewrite, so it is faster and preferred for almost everything.',
      'Spark is <b>lazy</b>: <i>transformations</i> (<code>select</code>, <code>filter</code>, <code>join</code>, <code>groupBy</code>) only build a plan; nothing runs until an <i>action</i> (<code>count</code>, <code>collect</code>, <code>write</code>) forces execution. Laziness lets Catalyst fuse and reorder operations across the whole job.',
      'The performance story is dominated by <b>shuffles</b>. A <b>narrow</b> transformation (map, filter) needs only a partition\'s own data. A <b>wide</b> transformation (join, groupBy, distinct) must move rows with the same key onto the same node — a <b>shuffle</b>: network + disk heavy, the usual bottleneck. Good Spark is mostly the art of minimising and balancing shuffles (partitioning, broadcast joins, avoiding skew).'],
      terms: [['RDD', 'low-level distributed collection; full control, no optimizer.'], ['DataFrame', 'distributed table; optimized by Catalyst — use this.'], ['Transformation', 'lazy op that builds the plan (map, filter, join).'], ['Action', 'triggers execution (count, collect, write).'], ['Partition', 'a chunk of the data processed by one task.'], ['Shuffle', 'redistribute rows by key across the network — expensive.'], ['Broadcast join', 'ship a small table to every node to avoid a shuffle.'], ['Skew', 'one key with far more rows, creating a straggler task.']],
      ex: [{ h: 'PySpark: aggregate with a shuffle, then broadcast-join', p: ['<code>groupBy</code> triggers a wide transformation (shuffle by <code>customer_id</code>). Joining a small dimension is made cheap with a <b>broadcast</b> hint, which replicates the tiny table instead of shuffling the big one. Nothing runs until <code>write</code>.'],
        code: 'from pyspark.sql import functions as F\nfrom pyspark.sql.functions import broadcast\n\norders = spark.read.parquet(\'s3://lake/orders/\')      # big, partitioned\ncustomers = spark.read.parquet(\'s3://lake/customers/\') # small dim\n\nrevenue = (orders\n    .filter(F.col(\'status\') == \'completed\')            # narrow\n    .groupBy(\'customer_id\')                            # WIDE -> shuffle\n    .agg(F.sum(\'amount\').alias(\'revenue\')))\n\nresult = revenue.join(broadcast(customers), \'customer_id\')  # no shuffle of orders\nresult.write.mode(\'overwrite\').parquet(\'s3://lake/mart/revenue/\')  # ACTION' }] },

    { h: 'Streaming with Kafka, Flink & Spark Structured Streaming', p: [
      '<b>Apache Kafka</b> is the de-facto backbone for real-time data — a distributed, durable <b>commit log</b>. Producers append records to a <b>topic</b>; the topic is split into <b>partitions</b> for parallelism and ordering (order is guaranteed only <i>within</i> a partition, chosen by the record key). Records persist for a retention window, so consumers can replay history — Kafka is storage, not just a queue.',
      '<b>Consumer groups</b> are how Kafka scales reads: each partition is assigned to exactly one consumer in a group, so adding consumers (up to the partition count) linearly increases throughput. Each consumer tracks its <b>offset</b> — its position in the log — and commits it to resume after a crash.',
      'Kafka moves the bytes; a <b>stream processor</b> computes over them. <b>Flink</b> is a true event-at-a-time engine with rich <b>event-time</b> windowing, watermarks, and exactly-once state — the choice for low-latency, stateful streaming. <b>Spark Structured Streaming</b> models a stream as an unbounded table processed in micro-batches — slightly higher latency, but one API shared with batch, which many teams prefer.'],
      terms: [['Topic', 'a named, append-only stream of records.'], ['Partition', 'an ordered shard of a topic; the unit of parallelism.'], ['Offset', 'a consumer\'s position (index) within a partition.'], ['Consumer group', 'consumers sharing a topic; one partition each.'], ['Event time vs processing time', 'when it happened vs when we saw it.'], ['Watermark', 'how long to wait for late events before closing a window.']],
      ex: [{ h: 'Spark Structured Streaming: windowed count from Kafka', p: ['Read a Kafka topic as a streaming DataFrame, parse the JSON value, and count events per 5-minute event-time window with a 10-minute watermark for lateness. The same DataFrame API you\'d use in batch — that is the appeal.'],
        code: 'from pyspark.sql import functions as F\n\nraw = (spark.readStream.format(\'kafka\')\n    .option(\'kafka.bootstrap.servers\', \'broker:9092\')\n    .option(\'subscribe\', \'clicks\')\n    .load())\n\nevents = raw.select(\n    F.from_json(F.col(\'value\').cast(\'string\'), schema).alias(\'e\')).select(\'e.*\')\n\nagg = (events\n    .withWatermark(\'event_ts\', \'10 minutes\')\n    .groupBy(F.window(\'event_ts\', \'5 minutes\'), \'page\')\n    .count())\n\n(agg.writeStream.outputMode(\'update\')\n    .format(\'console\').start().awaitTermination())' }] },

    { h: 'Storage layers — warehouse vs lake vs lakehouse', p: [
      'Where does the data live? Three answers. A <b>data warehouse</b> (Snowflake, BigQuery, Redshift) stores structured, modeled tables with strong SQL, transactions, and governance — great for BI, weaker for raw/unstructured data and ML. A <b>data lake</b> is cheap object storage (S3, GCS) holding raw files (Parquet, JSON) — infinitely flexible and cheap, but no transactions, no schema enforcement, easy to turn into a "data swamp".',
      'The <b>lakehouse</b> merges both: an open <b>table format</b> — <b>Delta Lake</b>, <b>Apache Iceberg</b>, or <b>Apache Hudi</b> — adds a transaction log over files in the lake, giving ACID, schema evolution, time travel, and upserts on cheap storage that both Spark and warehouses can query. It is the direction most modern platforms are converging on.'],
      table: { cols: ['', 'Warehouse', 'Data lake', 'Lakehouse'], rows: [
        ['Examples', 'Snowflake, BigQuery', 'S3 + Parquet, GCS', 'Delta, Iceberg, Hudi'],
        ['Data types', 'structured', 'any (raw files)', 'any + tabular'],
        ['ACID transactions', '<b>yes</b>', 'no', '<b>yes</b> (via table log)'],
        ['Schema', 'on write, enforced', 'on read, loose', 'enforced + evolvable'],
        ['Cost / scale', 'higher $, elastic', 'cheapest storage', 'cheap storage + ACID'],
        ['Best for', 'BI & analytics', 'raw landing, ML, archive', 'unified BI + ML + streaming']] },
      note: 'The three lakehouse formats differ in emphasis: Delta pairs tightly with Spark/Databricks; Iceberg is engine-neutral with strong hidden partitioning; Hudi leads on fast upserts and incremental pulls (CDC-friendly).' },

    { h: 'Dimensional modeling — star & snowflake schemas', p: [
      'Analytics tables are shaped for fast, intuitive querying using <b>dimensional modeling</b> (Kimball). A <b>fact table</b> holds the measurable events — one row per transaction, with numeric <i>measures</i> (amount, quantity) and <i>foreign keys</i> to dimensions. <b>Dimension tables</b> hold the descriptive context you filter and group by (customer, product, date, store).',
      'Arranged as a <b>star schema</b>, one central fact table points out to denormalised dimensions — few joins, fast, analyst-friendly. A <b>snowflake schema</b> normalises those dimensions into sub-tables (product → category → department): less storage and redundancy, but more joins and complexity.',
      'This is the deliberate opposite of OLTP design. Operational databases <b>normalise</b> (3NF) to avoid update anomalies for many small writes. Analytics <b>denormalises</b> to avoid joins for a few huge reads. <b>Slowly Changing Dimensions (SCD Type 2)</b> handle history by adding a new dimension row with validity dates when an attribute changes, so past facts still join to the value that was true at the time.'],
      terms: [['Fact table', 'the events; measures + FKs; long and narrow.'], ['Dimension', 'descriptive context; short and wide.'], ['Grain', 'what one fact row means (e.g. one order line).'], ['Star schema', 'fact + denormalised dims; fewer joins.'], ['Snowflake schema', 'normalised dims; less redundancy, more joins.'], ['SCD Type 2', 'version dimension rows to preserve history.']],
      ex: [{ h: 'Star-schema query', p: ['One fact table joined to three dimensions answers "completed revenue by product category and month". The star shape keeps it to simple, fast joins on surrogate keys.'],
        code: 'SELECT   d.year, d.month, p.category, SUM(f.amount) AS revenue\nFROM     fact_sales     f\nJOIN     dim_date       d ON f.date_key    = d.date_key\nJOIN     dim_product    p ON f.product_key = p.product_key\nJOIN     dim_customer   c ON f.customer_key= c.customer_key\nWHERE    f.status = \'completed\'\nGROUP BY d.year, d.month, p.category\nORDER BY d.year, d.month, revenue DESC;' }] },

    { h: 'Data quality, contracts & lineage', p: [
      'A pipeline that silently emits wrong numbers is worse than one that fails loudly. <b>Data quality testing</b> asserts expectations about the data at each stage: not-null keys, unique ids, values in range, referential integrity, freshness. Frameworks like <b>Great Expectations</b> (and dbt tests) codify these as versioned checks that fail the run or quarantine bad rows.',
      'A <b>data contract</b> pushes quality upstream: the producer and consumers agree on an explicit schema and semantics (types, nullability, allowed values, SLAs) enforced at the boundary — so a mobile team can\'t rename a field and break the finance dashboard next morning. It turns "we noticed the numbers looked off" into a build-time failure.',
      '<b>Data lineage</b> is the map of where each column came from — which sources, through which transforms, into which reports. It answers "if this table is wrong, what breaks?" (downstream impact) and "why is this number what it is?" (upstream debugging). Tools like dbt, Dagster, OpenLineage, and catalogs (DataHub, Unity Catalog) build it automatically from the DAG.'],
      terms: [['Expectation / test', 'an assertion about the data (not_null, unique, range).'], ['Freshness SLA', 'max acceptable lag before data is "stale".'], ['Data contract', 'enforced producer↔consumer schema + semantics agreement.'], ['Lineage', 'column-level graph of sources → transforms → outputs.'], ['Quarantine', 'route failing rows aside instead of blocking the whole load.']],
      ex: [{ h: 'A Great Expectations suite', p: ['A few expectations turn assumptions into enforced checks. If <code>order_id</code> ever contains nulls or duplicates, or <code>amount</code> goes negative, the validation fails and the orchestrator can halt the pipeline before bad data reaches the warehouse.'],
        code: 'import great_expectations as gx\n\nbatch = context.sources.pandas_default.read_parquet(\'orders.parquet\')\n\nbatch.expect_column_values_to_not_be_null(\'order_id\')\nbatch.expect_column_values_to_be_unique(\'order_id\')\nbatch.expect_column_values_to_be_between(\'amount\', min_value=0, max_value=100000)\nbatch.expect_column_values_to_be_in_set(\'status\',\n    [\'pending\', \'completed\', \'cancelled\', \'refunded\'])\n\nresults = batch.validate()\nassert results.success, \'Data quality checks failed — halting load\'' }] },

    { h: 'Feature stores — offline vs online', p: [
      'ML adds a hard problem on top of ETL: the same feature (e.g. "customer\'s 7-day spend") must be computed for <b>training</b> over years of history <i>and</i> served at <b>prediction</b> time in milliseconds — and the two must match exactly, or you get <b>training–serving skew</b>. A <b>feature store</b> (Feast, Tecton) solves this by defining each feature once and materialising it into two synchronized stores.',
      'The <b>offline store</b> (warehouse/lake — BigQuery, Snowflake, Parquet) holds the full history for training, and crucially supports <b>point-in-time correct</b> joins: for each training label it fetches feature values as they were <i>at that moment</i>, preventing <b>data leakage</b> from the future. The <b>online store</b> (a low-latency KV store — Redis, DynamoDB) holds only the latest value per entity for fast lookups at inference.',
      'The store also gives <b>discoverability and reuse</b> (teams share vetted features instead of re-deriving them), consistent transformations across both paths, and lineage from raw source to served feature.'],
      table: { cols: ['', 'Offline store', 'Online store'], rows: [
        ['Purpose', 'training & batch scoring', 'real-time inference'],
        ['Backing tech', 'warehouse / lake (Parquet)', 'Redis, DynamoDB, Bigtable'],
        ['Data held', 'full history, all versions', 'latest value per entity'],
        ['Access pattern', 'large scan, point-in-time join', 'single-key lookup, <10ms'],
        ['Read latency', 'seconds–minutes', 'milliseconds']] },
      ex: [{ h: 'Feast: point-in-time training set + online lookup', p: ['<code>get_historical_features</code> does the point-in-time-correct join against the offline store to build a leakage-free training set; <code>get_online_features</code> fetches the freshest values for live inference. One feature definition, two consistent surfaces.'],
        code: 'from feast import FeatureStore\nstore = FeatureStore(repo_path=\'.\')\n\n# TRAINING: point-in-time correct join over history (offline)\ntraining_df = store.get_historical_features(\n    entity_df=labels_df,            # entity ids + event_timestamp per label\n    features=[\'customer_stats:spend_7d\', \'customer_stats:orders_30d\'],\n).to_df()\n\n# SERVING: low-latency lookup of the latest values (online)\nfeatures = store.get_online_features(\n    features=[\'customer_stats:spend_7d\', \'customer_stats:orders_30d\'],\n    entity_rows=[{\'customer_id\': 42}],\n).to_dict()' }],
      note: 'The unifying rule: define a feature once, compute it identically for offline and online, and always join features point-in-time to avoid leaking the future into training.' },
  ]
});
