/* Deep dive — Generative models */
window.AtlasRef && window.AtlasRef.register('generative', {
  color: '#FB7185',
  title: 'How machines learn to create',
  lead: 'Generative models learn the shape of the data itself, then sample from it — turning noise into images, sound and text. This is the full course: autoencoders and VAEs, GANs, the diffusion models behind today\'s image tools, conditioning and guidance, evaluation, and the risks that come with synthetic media.',
  sections: [

    { h: 'Generative vs discriminative models', p: [
      'A <b>discriminative</b> model learns the boundary between classes — it models <code>P(y|x)</code>, the probability of a label given the input. That is all a classifier needs: given this image, is it a cat or a dog? It never has to understand what a cat <i>looks like</i>, only how to tell the two apart.',
      'A <b>generative</b> model is more ambitious: it models the data distribution itself — either the joint <code>P(x,y)</code> or the marginal <code>P(x)</code> — so it can <i>sample new x</i>. Learn what images of cats look like well enough and you can draw a brand-new cat that never existed. Generation is harder because you must capture the full structure of the data, not just where to slice it.'],
      eqn: 'discriminative:  P(y | x)          # decision boundary\ngenerative:      P(x)  or  P(x | y)  # the data itself, sampleable',
      terms: [['Density', 'how much probability mass sits at each point x.'], ['Sampling', 'drawing a fresh x ~ P(x) the model has never emitted before.'], ['Likelihood', 'P(data | model) — how well the model explains observed data.'], ['Latent variable', 'a hidden z that explains the visible x (style, content, class).']],
      ex: [{ h: 'Same task, two philosophies', p: ['To classify email as spam, a discriminative model (logistic regression) learns weights on words that separate spam from ham. A generative model (Naive Bayes) instead learns <code>P(words | spam)</code> and <code>P(words | ham)</code> separately, then uses Bayes\' rule to classify. The generative one can also <i>generate</i> a plausible spam email; the discriminative one cannot.'],
        eqn: 'P(y | x) = P(x | y) P(y) / P(x)   # Bayes turns generative into discriminative' }],
      note: 'Rule of thumb: if you only need labels, discriminative usually wins on accuracy per parameter. If you need to synthesise, fill in, or reason about uncertainty over x, you need a generative model.' },

    { h: 'Autoencoders: compress, then reconstruct', p: [
      'An <b>autoencoder</b> is a neural network trained to copy its input to its output through a narrow middle. An <b>encoder</b> squeezes the input x into a low-dimensional code z (the <b>bottleneck</b> or latent), and a <b>decoder</b> expands z back into a reconstruction x̂. Because z is much smaller than x, the network cannot just memorise — it must learn the efficient, structured features that matter.',
      'The training signal is simply <b>reconstruction error</b>: make x̂ look like x. The bottleneck forces a compressed representation, which is useful for denoising, anomaly detection (bad reconstructions flag outliers), and pretraining. But a plain autoencoder\'s latent space is <i>lumpy</i> — points between two valid codes often decode to garbage, so you cannot reliably sample from it.'],
      eqn: 'z = encoder(x)      x̂ = decoder(z)      L = ‖x − x̂‖²   (reconstruction)',
      ex: [{ h: 'A denoising autoencoder', p: ['Corrupt the input with noise but ask the network to reconstruct the <i>clean</i> original. It learns to remove noise because the bottleneck can only pass through the true signal. This trick — predict clean from corrupted — is the conceptual seed of diffusion models.'],
        code: 'x_noisy = x + 0.3 * torch.randn_like(x)\nz  = encoder(x_noisy)      # compress the corrupted input\nxr = decoder(z)            # reconstruct\nloss = ((xr - x) ** 2).mean()   # target is the CLEAN x' }],
      note: 'A bottleneck smaller than the input makes it undercomplete (forced compression). Regularised variants (sparse, contractive, denoising) shape the latent without shrinking it.' },

    { h: 'Variational Autoencoders (VAEs)', p: [
      'A <b>VAE</b> fixes the autoencoder\'s unsamplable latent by making the encoder output a <i>distribution</i> instead of a single point. For each input, the encoder predicts a mean μ and variance σ² of a Gaussian in latent space; you sample z from that Gaussian, then decode. A <b>KL-divergence</b> term pulls every per-input Gaussian toward a standard normal N(0, I), packing the whole latent space into a smooth, continuous ball you <i>can</i> sample from.',
      'The loss is the <b>ELBO</b> (Evidence Lower BOund), written as two competing terms: a <b>reconstruction</b> term (decode z back to x) and a <b>KL</b> term (keep the latent close to the prior). Reconstruction wants sharp, faithful outputs; KL wants a tidy, generative latent. Their balance is the whole game.'],
      eqn: 'ELBO = E[ log p(x | z) ]  −  KL( q(z | x) ‖ p(z) )\n       └ reconstruction ┘      └ regulariser (prior N(0,I)) ┘\nLoss = reconstruction  −  β · KL      (maximise ELBO = minimise −ELBO)',
      ex: [{ h: 'The reparameterization trick', p: ['You cannot backpropagate through a random <code>sample</code> — the gradient has nowhere to flow. The trick: instead of sampling <code>z ~ N(μ, σ²)</code> directly, sample a fixed noise <code>ε ~ N(0, I)</code> and compute <code>z = μ + σ·ε</code>. Now the randomness lives in ε (no gradient needed there), while μ and σ are deterministic functions the gradient <i>can</i> flow through. This one reparameterisation is what makes VAEs trainable.'],
        eqn: 'ε ~ N(0, I)      z = μ + σ ⊙ ε      # gradients flow through μ, σ' }],
      code: 'def vae_loss(x, x_recon, mu, logvar):\n    # reconstruction: how well we rebuilt the input\n    recon = F.mse_loss(x_recon, x, reduction=\'sum\')\n    # KL( N(mu, sigma^2) || N(0, I) ), closed form\n    kl = -0.5 * torch.sum(1 + logvar - mu.pow(2) - logvar.exp())\n    return recon + kl   # minimise = maximise ELBO\n\ndef reparameterize(mu, logvar):\n    std = torch.exp(0.5 * logvar)\n    eps = torch.randn_like(std)      # fixed noise\n    return mu + eps * std            # differentiable sample',
      note: 'VAEs give smooth, well-behaved latents (great for interpolation) but tend to blur — the Gaussian likelihood averages over plausible outputs. GANs and diffusion produce sharper samples.' },

    { h: 'GANs: a forger versus a detective', p: [
      'A <b>Generative Adversarial Network</b> pits two networks against each other. The <b>generator</b> G maps random noise z to fake samples and tries to fool a judge. The <b>discriminator</b> D looks at a sample and outputs the probability it is real. They play a <b>minimax game</b>: D trains to catch fakes, G trains to produce fakes D cannot catch. At equilibrium, G\'s samples are indistinguishable from real data and D is reduced to guessing 50/50.',
      'There is no reconstruction loss and no explicit density — G learns purely from D\'s gradients. When it works, GANs produce razor-sharp images. When it doesn\'t, training is a notoriously unstable tightrope.'],
      eqn: 'min_G max_D  V(D,G) = E_x[ log D(x) ]  +  E_z[ log(1 − D(G(z))) ]\n            └ D wants real→1 ┘   └ D wants fake→0, G wants fake→1 ┘',
      ex: [{ h: 'One training step, both players', p: ['Each iteration updates the discriminator to better separate real from fake, then updates the generator to push its fakes toward "real" in D\'s eyes. In practice G maximises <code>log D(G(z))</code> (the non-saturating loss) rather than minimising <code>log(1−D(G(z)))</code>, which gives stronger gradients early when fakes are obvious.'],
        code: '# --- train discriminator ---\nreal_loss = bce(D(x_real), ones)\nfake_loss = bce(D(G(z).detach()), zeros)   # detach: no grad to G\nd_loss = real_loss + fake_loss\nd_loss.backward(); opt_D.step()\n\n# --- train generator ---\ng_loss = bce(D(G(z)), ones)   # want D to call fakes "real"\ng_loss.backward(); opt_G.step()' }],
      terms: [['Nash equilibrium', 'neither player can improve unilaterally; G matches the data.'], ['Mode collapse', 'G finds a few outputs that fool D and emits only those — no diversity.'], ['Training instability', 'oscillation or divergence if D and G get out of balance.'], ['Wasserstein GAN', 'swaps the loss for Earth-Mover distance to stabilise training.']],
      note: 'Mode collapse is the signature GAN failure: a face generator that produces beautiful but nearly identical faces has collapsed onto one mode of the true distribution.' },

    { h: 'Diffusion models: destroy, then learn to rebuild', p: [
      'Diffusion is the idea behind most modern image generators, and it is disarmingly simple. The <b>forward process</b> takes a real image and adds a tiny bit of Gaussian noise, step after step, over hundreds of steps, until nothing but pure noise remains. This process is fixed — no learning, just a known noise schedule.',
      'The <b>reverse process</b> is what we train: a network that, given a noisy image and the timestep, predicts how to remove one step of noise. Run it backward from pure noise and it gradually denoises a random field into a coherent image. Crucially, the network is trained to <b>predict the noise ε</b> that was added — a simple regression target. Denoising a little at a time, hundreds of times, is what turns static into a photograph.'],
      eqn: 'forward:  x_t = √(ᾱ_t) · x₀  +  √(1 − ᾱ_t) · ε ,   ε ~ N(0, I)\ntraining loss:  L = E‖ ε  −  ε_θ(x_t, t) ‖²      # predict the noise\nreverse:  x_{t−1} = denoise( x_t, ε_θ(x_t, t), t )   # one step cleaner',
      ex: [{ h: 'Why predicting noise is enough', p: ['The forward equation lets you jump to any noise level <code>x_t</code> in one shot from the clean image <code>x₀</code> and a sampled ε. So training needs no slow simulation: pick a random timestep t, corrupt the image to <code>x_t</code>, and ask the network to recover the exact ε you used. Because <code>x_t</code> is a known mix of <code>x₀</code> and ε, predicting ε is equivalent to predicting the clean image — but the ε target is better-scaled and trains more stably.'],
        code: 'def training_step(x0, model):\n    t   = torch.randint(0, T, (x0.size(0),))     # random timestep\n    eps = torch.randn_like(x0)                    # the noise to add\n    xt  = sqrt_abar[t] * x0 + sqrt_1m_abar[t] * eps   # forward jump\n    eps_pred = model(xt, t)                       # predict the noise\n    return F.mse_loss(eps_pred, eps)              # simple regression' }],
      note: 'A U-Net (with skip connections and self-attention) is the usual denoiser: it sees the whole image at multiple scales, which is exactly what removing structured noise requires.' },

    { h: 'Sampling: DDPM vs DDIM', p: [
      'Once ε_θ is trained you generate by running the reverse process. <b>DDPM</b> (the original) is <i>stochastic</i>: at each of ~1000 steps it predicts the noise, subtracts a portion, and adds a little fresh noise back. It is faithful to the theory and high quality, but slow — a thousand network calls per image.',
      '<b>DDIM</b> reinterprets the same trained model as a <i>deterministic</i> ODE you can integrate in far fewer steps — often 20–50 — with little quality loss. Because it is deterministic, the same starting noise always yields the same image, which makes latent interpolation and reproducibility possible. Most production samplers (DPM++, Euler, etc.) are refinements of this deterministic view.'],
      eqn: 'DDPM step (stochastic):  x_{t−1} = μ_θ(x_t, t)  +  σ_t · z ,   z ~ N(0, I)\nDDIM step (deterministic): x_{t−1} = √(ᾱ_{t−1}) · x̂₀  +  direction(x_t)\n(σ = 0 → fully deterministic, fewer steps possible)',
      ex: [{ h: 'A minimal sampling loop', p: ['Start from pure noise and walk the schedule backward. Each step estimates the noise, uses it to estimate the clean image, then re-noises to the next (lower) level. DDPM injects extra randomness each step; DDIM sets that term to zero and can skip timesteps.'],
        code: 'def sample(model, shape, timesteps):\n    x = torch.randn(shape)                  # pure noise\n    for t in reversed(range(timesteps)):    # T-1 ... 0\n        eps = model(x, t)                   # predict noise\n        x0_hat = (x - sqrt_1m_abar[t] * eps) / sqrt_abar[t]\n        if t > 0:                           # DDPM: re-noise a bit\n            noise = torch.randn_like(x)\n            x = mean_from(x0_hat, x, t) + sigma[t] * noise\n        else:\n            x = x0_hat                      # last step: clean image\n    return x' }],
      table: { cols: ['Sampler', 'Nature', 'Steps', 'Trade-off'], rows: [
        ['DDPM', 'stochastic', '~1000', 'highest fidelity, slow'],
        ['DDIM', 'deterministic', '20–50', 'fast, reproducible, near-DDPM quality'],
        ['DPM++ / Euler-a', 'refined ODE/SDE', '15–30', 'production default for Stable Diffusion']] } },

    { h: 'Latent diffusion: diffuse in a compressed space', p: [
      'Running diffusion on full-resolution pixels is expensive — a 512×512 image is ~786k values to denoise a thousand times. <b>Latent diffusion</b> (the engine of <b>Stable Diffusion</b>) first trains a VAE to compress images into a small latent grid (e.g. 64×64×4, ~48× fewer values), then runs the entire diffusion process <i>in that latent space</i>. A final VAE decode turns the denoised latent back into a full image.',
      'This is the key efficiency unlock: diffusion handles the hard, perceptual structure in a compact space, while the VAE handles high-frequency pixel detail. It is why high-quality open image models run on a single consumer GPU rather than a datacentre.'],
      eqn: 'x → [VAE encoder] → z   (compress)\ndiffuse & denoise entirely in z-space\nẑ → [VAE decoder] → image   (decompress)',
      ex: [{ h: 'The Stable Diffusion pipeline', p: ['A text prompt is encoded to embeddings, random latent noise is initialised, a U-Net denoises that latent over ~30 steps conditioned on the text, and the VAE decodes the result to pixels. Every step operates on the tiny latent, so the whole thing is fast.'],
        code: 'z = torch.randn(1, 4, 64, 64)          # latent noise (not pixels)\ntext_emb = clip_text_encoder(prompt)\nfor t in scheduler.timesteps:          # ~30 steps\n    eps = unet(z, t, text_emb)         # denoise in latent space\n    z   = scheduler.step(eps, t, z)\nimage = vae.decode(z)                  # latent -> 512x512 pixels' }],
      note: 'The VAE here is a perceptual compressor, not the generative model — the diffusion U-Net is where generation happens. Separating the two is the whole trick.' },

    { h: 'Conditioning & classifier-free guidance', p: [
      'Unconditional diffusion makes <i>some</i> image; we want a <i>specific</i> one. <b>Conditioning</b> feeds an extra signal — a class label, a text embedding — into the denoiser so ε_θ depends on it. But naive conditioning often follows the prompt only weakly.',
      '<b>Classifier-free guidance (CFG)</b> is the fix that made text-to-image sharp and prompt-faithful. During training the condition is randomly dropped, so one network learns <i>both</i> conditional and unconditional prediction. At sampling, you run both and <b>extrapolate away</b> from the unconditional toward the conditional. The <b>guidance scale</b> controls how far: low values are creative and loosely related to the prompt, high values are literal and saturated but can look over-cooked and lose diversity.'],
      eqn: 'ε̂ = ε_uncond  +  s · ( ε_cond  −  ε_uncond )\n         └ base ┘        └ guidance scale s (e.g. 7.5) ┘\ns = 1 → plain conditioning ;  s > 1 → stronger prompt adherence',
      ex: [{ h: 'Turning up the guidance knob', p: ['At <code>s = 1</code> the model barely listens to the prompt. At <code>s ≈ 7–8</code> (the common default) it follows text closely with good quality. At <code>s = 20</code> it obeys the prompt aggressively but colours blow out and variety collapses. CFG is why the guidance scale is the single most-tuned slider in image tools.'],
        code: 'eps_uncond = unet(z, t, empty_embedding)   # no prompt\neps_cond   = unet(z, t, text_embedding)    # with prompt\neps = eps_uncond + scale * (eps_cond - eps_uncond)   # extrapolate\nz = scheduler.step(eps, t, z)' }],
      note: 'CFG costs two U-Net passes per step. It applies to any condition — text, class, image — not just prompts.' },

    { h: 'Text-to-image: aligning words and pixels', p: [
      'To generate from text, the model needs the prompt in a form that lives in the same conceptual space as images. <b>CLIP</b> provides exactly this: it is trained on hundreds of millions of image–caption pairs with a <b>contrastive</b> objective — pull matching image and text embeddings together, push mismatched pairs apart. The result is a shared embedding space where "a photo of a red bicycle" sits near actual photos of red bicycles.',
      'A text-to-image diffusion model uses CLIP\'s (or a larger language model\'s) text encoder to turn the prompt into conditioning embeddings, then cross-attends to them at every denoising step. The image model never "reads" English — it navigates the geometry of a space where language and vision have already been aligned.'],
      eqn: 'contrastive loss (CLIP): maximise  sim(image_i, text_i)\n                          minimise sim(image_i, text_j≠i)\nprompt → text_encoder → embeddings → cross-attention in U-Net',
      ex: [{ h: 'Why CLIP embeddings transfer', p: ['Because CLIP saw captions describing objects, styles, and relations, its text space encodes compositional meaning. A diffusion model conditioned on "an oil painting of a cat astronaut" can combine <i>oil painting</i>, <i>cat</i>, and <i>astronaut</i> even if that exact image never existed — the concepts are separable directions in the shared space.'],
        code: 'img_emb  = clip.encode_image(images)   # (N, d)\ntxt_emb  = clip.encode_text(captions)  # (N, d)\nlogits   = img_emb @ txt_emb.T         # cosine similarities\n# diagonal should be largest: each image matches its own caption\nloss = ce(logits, arange(N)) + ce(logits.T, arange(N))' }],
      note: 'CLIP is also reused at evaluation time (CLIP score) to measure whether a generated image matches its prompt — the same alignment, run in reverse.' },

    { h: 'Control: ControlNet, pose, depth & edges', p: [
      'A text prompt cannot specify exact spatial layout — where a hand goes, what pose a figure holds. <b>ControlNet</b> adds precise structural control by attaching a trainable copy of the diffusion U-Net that ingests a <i>conditioning image</i> — a human-pose skeleton, a depth map, a Canny edge map, a segmentation mask — and injects its features into the frozen base model. The base model still generates from text; ControlNet constrains <i>where</i>.',
      'A clever detail: the connections from ControlNet start as <b>zero-initialised</b> convolutions, so at the start of training it has no effect and the base model is never disrupted. It learns its control gently. Related techniques — <b>IP-Adapter</b> (image prompts), <b>T2I-Adapter</b> (lighter control), <b>LoRA</b> (cheap style/subject fine-tuning), and <b>inpainting</b> masks — form a whole ecosystem of steering tools layered on top of a frozen generator.'],
      terms: [['OpenPose control', 'condition on a stick-figure skeleton to fix body pose.'], ['Depth control', 'condition on a depth map to fix 3-D layout and perspective.'], ['Canny / edge control', 'condition on edge lines to preserve outlines and composition.'], ['Zero-convolution', 'control connections start at 0 so the base model is untouched initially.']],
      ex: [{ h: 'Locking a pose while changing everything else', p: ['Extract an OpenPose skeleton from a reference photo, then generate "a knight in armour" conditioned on both the text and that skeleton. The output character strikes the exact same pose, but the subject, style, and background are entirely re-imagined by the prompt.'],
        code: 'pose = openpose_detector(reference_image)   # skeleton map\nimage = pipe(\n    prompt=\'a knight in ornate armour, dramatic light\',\n    image=pose,                 # ControlNet conditioning\n    controlnet_conditioning_scale=1.0,\n).images[0]' }] },

    { h: 'Autoregressive generation for images & audio', p: [
      'Diffusion is not the only way. <b>Autoregressive</b> models generate one token at a time, each conditioned on all previous ones — the same left-to-right recipe as language models, applied to other media. For images (PixelCNN, and modern token-based models) you first turn the image into a grid of discrete tokens with a <b>VQ-VAE</b>, then predict those tokens in sequence. For audio, <b>WaveNet</b> predicts raw waveform samples one at a time, and codec-token models (like the ones behind modern music and speech tools) predict compressed audio tokens.',
      'The trade-off is inherent: autoregressive models give exact likelihoods and superb coherence, but generation is <i>sequential</i> — thousands of steps for one image or a second of audio — whereas diffusion denoises the whole canvas in parallel. Newer image models blur the line, mixing discrete tokens, masking, and diffusion.'],
      eqn: 'p(x) = Π_i  p( x_i  |  x_1, …, x_{i−1} )      # one token at a time',
      ex: [{ h: 'VQ-VAE: images as a vocabulary', p: ['A VQ-VAE encodes an image into a grid of indices pointing at a learned codebook of vectors — effectively a "language" of visual patches. An autoregressive transformer then models that grid like a sentence, predicting patch-tokens in raster order. Decode the token grid back through the VQ-VAE and you have a fresh image.'],
        code: '# encode image to discrete tokens, then model them like text\ntokens = vqvae.encode(image)        # e.g. 32x32 grid of codebook ids\nflat   = tokens.reshape(-1)         # sequence of 1024 ids\n# transformer predicts next token given all previous\nfor i in range(len(flat)):\n    logits = transformer(flat[:i])\n    flat[i] = sample(logits[-1])    # sequential generation\nimage = vqvae.decode(flat.reshape(32, 32))' }],
      note: 'WaveNet\'s dilated causal convolutions let each audio sample see thousands of past samples — long-range context without a full recurrent scan.' },

    { h: 'Evaluating generative models', p: [
      'How do you score a model whose whole job is to invent things with no ground truth? You measure <b>fidelity</b> (do samples look real?) and <b>diversity</b> (does it cover the whole data distribution, not just a few modes?). No single number captures both, so several metrics are reported together.',
      'The dominant image metric is <b>FID</b> (Fréchet Inception Distance): it embeds real and generated images with an Inception network and compares the two sets as Gaussians — <i>lower is better</i>. It penalises both blur and mode collapse, which is why it became standard. <b>Inception Score</b> rewards confident, varied classifications but ignores the real data. <b>CLIP score</b> measures prompt–image agreement for text-to-image. Human preference studies remain the ultimate judge.'],
      eqn: 'FID = ‖μ_r − μ_g‖²  +  Tr( Σ_r + Σ_g − 2√(Σ_r Σ_g) )      (lower = better)\n(r = real features, g = generated features, from Inception-v3)',
      table: { cols: ['Metric', 'Measures', 'Direction', 'Blind spot'], rows: [
        ['FID', 'realism + diversity vs real set', 'lower better', 'needs many samples; Inception bias'],
        ['Inception Score', 'confident, varied classes', 'higher better', 'ignores real data; gameable'],
        ['CLIP score', 'prompt–image agreement', 'higher better', 'says nothing about image quality'],
        ['Precision / Recall', 'fidelity vs coverage, split out', 'higher better', 'two numbers, harder to summarise'],
        ['Human eval', 'actual perceived quality', '—', 'slow, costly, subjective']] },
      ex: [{ h: 'Reading an FID number', p: ['An FID of ~2–5 on a benchmark like ImageNet is excellent; ~50 looks obviously synthetic. Because FID compares feature <i>distributions</i>, a model that mode-collapses to a few gorgeous images scores badly — the generated Gaussian is too narrow. That dual sensitivity to quality <i>and</i> spread is exactly why FID beats "does it look nice."']}] },

    { h: 'Applications & the double-edged sword', p: [
      'Generative models have escaped the lab. In <b>art and design</b> they draft concepts, textures, and variations; in <b>synthetic data</b> they augment scarce or private datasets (medical scans, rare defects) to train other models; in <b>drug and material discovery</b> they propose novel molecules and protein structures that satisfy target properties, searching chemical space far faster than trial and error. They power photo editing, super-resolution, voice synthesis, and code generation.',
      'The same power enables harm. <b>Deepfakes</b> — synthetic video and voice of real people — threaten fraud, non-consensual imagery, and disinformation. Models trained on scraped data raise <b>copyright</b> and consent questions. The response is <b>provenance</b> infrastructure: <b>watermarking</b> (embedding a detectable, ideally invisible signal in outputs), <b>C2PA</b> Content Credentials (cryptographically signed metadata recording how media was made and edited), and detection tools. None is bulletproof — watermarks can be attacked and metadata stripped — so provenance is layered, not absolute.'],
      terms: [['Synthetic data', 'model-generated training data to augment or protect real data.'], ['Deepfake', 'synthetic media impersonating a real person\'s face or voice.'], ['Watermarking', 'an embedded, detectable mark signalling AI origin.'], ['C2PA / Content Credentials', 'signed provenance metadata: what made this, and how.']],
      ex: [{ h: 'Provenance in practice', p: ['A responsible image tool can (1) embed an invisible statistical watermark in the pixels, (2) attach a signed C2PA manifest stating the model and prompt, and (3) publish a detector. A viewer\'s software checks the signature and flags AI origin. Defence-in-depth: strip the metadata and the watermark may survive; scrub the watermark and the signature may still verify — but a determined adversary can defeat any single layer.'],
        code: '# conceptual provenance pipeline\nimage = model.generate(prompt)\nimage = watermark.embed(image, key)          # invisible signal\nmanifest = c2pa.sign({\n    \'generator\': \'diffusion-v1\',\n    \'prompt\': prompt,\n    \'timestamp\': now(),\n}, private_key)                              # tamper-evident\nsave(image, attach=manifest)' }],
      note: 'Regulation is catching up: several jurisdictions now require disclosure of AI-generated media. Provenance is becoming an expectation, not a courtesy.' },
  ]
});
