/* Deep dive — LLMs & Agents */
window.AtlasRef && window.AtlasRef.register('llm-agents', {
  color: '#818CF8',
  title: 'From next-token prediction to autonomous agents',
  lead: 'How a large language model is actually built, aligned, shrunk, served and extended — the full pipeline: pre-training, scaling laws, instruction tuning, RLHF/DPO, quantization, the KV cache, local runtimes, LoRA fine-tuning, RAG, and the plan-act-observe agent loop. Each topic with the real formulas, worked numbers, and code you can run.',
  sections: [

    { h: 'Pre-training: next-token prediction at scale', p: [
      'A large language model is, at heart, a function that reads a sequence of tokens and outputs a probability distribution over the <b>next</b> token. That is the entire training objective — no labels, no human annotation, just <b>self-supervised</b> learning on a huge corpus of text. Given the prefix <code>The capital of France is</code>, the model learns to put most of its probability mass on <code>Paris</code>.',
      'Text is first <b>tokenized</b> (usually with byte-pair encoding) into sub-word units, then each token becomes a learned <b>embedding</b> vector. A stack of <b>transformer</b> blocks — self-attention plus feed-forward layers — mixes information across positions, and a final linear + softmax head produces the next-token distribution. Training minimises the cross-entropy between that distribution and the actual next token, averaged over trillions of tokens.',
      'The magic is emergent: by getting very good at "guess the next word" over a corpus that contains code, dialogue, reasoning, and facts, the model is forced to internalise grammar, world knowledge, and rudimentary reasoning. Everything downstream (chat, tools, agents) is built on top of this <b>base model</b>.'],
      eqn: 'L = -(1/N) Σ_t log P(x_t | x_1 … x_{t-1} ; θ)     # mean cross-entropy / next-token loss',
      terms: [['Token', 'a sub-word unit; ~4 characters or 0.75 words of English on average.'], ['Base / foundation model', 'the raw pre-trained model, good at completion but not yet a helpful chatbot.'], ['Context window', 'the maximum number of tokens the model can attend to at once.'], ['Perplexity', 'exp(loss); the effective branching factor — lower is better.']],
      ex: [{ h: 'What the loss is really measuring', p: ['If a model assigns probability 0.5 to the correct next token, its loss on that token is <code>-log(0.5) = 0.69</code> nats. Perplexity is <code>exp(loss)</code>, so a per-token loss of 0.69 is a perplexity of 2 — the model is effectively choosing between 2 equally likely options. State-of-the-art models reach perplexities near 1.5 on held-out English.'],
        code: 'import math\np_correct = 0.5\nloss = -math.log(p_correct)   # 0.693 nats\nperplexity = math.exp(loss)   # 2.0\n\n# A confident, correct model:\nloss_good = -math.log(0.9)    # 0.105\nmath.exp(loss_good)           # ~1.11 perplexity' }],
      note: 'Pre-training a frontier model costs millions of GPU-hours. What you download from a model hub is the frozen result of that run — the weights θ.' },

    { h: 'Scaling laws & Chinchilla-optimal training', p: [
      'Model quality improves predictably as you scale three things: <b>N</b> (parameters), <b>D</b> (training tokens) and <b>C</b> (compute). The loss falls as a smooth power law in each — this is what makes it worth spending money, because gains are forecastable rather than random.',
      'A useful rule of thumb is that training compute is roughly <code>C ≈ 6 · N · D</code> FLOPs (six floating-point operations per parameter per token, covering the forward and backward pass). Given a fixed compute budget, how should you split it between a bigger model and more data?',
      'The <b>Chinchilla</b> result (DeepMind, 2022) showed that most early large models were badly over-parameterised and under-trained. For compute-optimal training you should scale N and D <b>together</b> — roughly <b>20 tokens per parameter</b>. A 70B model wants ~1.4T tokens; a 7B model wants ~140B. Beyond that ratio you are better off making the model bigger, not just training the same model longer (though for cheap <i>inference</i>, deliberately over-training a smaller model — as Llama does — is a rational trade).'],
      eqn: 'L(N,D) = E + A/N^α + B/D^β        C ≈ 6·N·D        Chinchilla-optimal: D ≈ 20·N',
      ex: [{ h: 'Sizing a compute-optimal run', p: ['Suppose you can afford <code>C = 1e22</code> FLOPs. Using <code>C = 6ND</code> and the Chinchilla ratio <code>D = 20N</code>, substitute to solve for N: <code>C = 6·N·(20N) = 120·N²</code>, so <code>N = sqrt(C/120)</code>. That gives the parameter count, and D follows.'],
        eqn: 'N = sqrt(1e22 / 120) ≈ 9.1e9  (~9B params)     D = 20·N ≈ 1.8e11  (~180B tokens)',
        code: 'import math\nC = 1e22                     # FLOP budget\nN = math.sqrt(C / 120)       # ~9.1e9 params\nD = 20 * N                   # ~1.8e11 tokens\nprint(f"{N/1e9:.1f}B params, {D/1e9:.0f}B tokens")\n# check: 6 * N * D  ~= C' }],
      note: 'Power laws eventually bend — data quality, repetition, and architecture set floors. Scaling laws forecast trends, not miracles.' },

    { h: 'Instruction tuning (SFT): from completer to assistant', p: [
      'A base model completes text; it does not naturally follow instructions or answer questions helpfully. <b>Supervised fine-tuning (SFT)</b>, also called instruction tuning, fixes this by continuing training on a curated dataset of <code>(instruction, ideal response)</code> pairs — often formatted with a <b>chat template</b> that marks system, user and assistant turns.',
      'The objective is unchanged — still next-token prediction — but now the model imitates <i>demonstrations</i> of the desired behaviour. Crucially, the loss is usually <b>masked</b> so it is computed only on the assistant tokens: the model is graded on its answers, not on repeating the prompt. A few tens of thousands of high-quality examples can transform a base model into a usable assistant.'],
      terms: [['SFT', 'supervised fine-tuning on demonstration data.'], ['Chat template', 'the special-token format (e.g. system/user/assistant roles) the model was tuned on — mismatching it degrades quality.'], ['Loss masking', 'zeroing the loss on prompt tokens so only the response is learned.'], ['Instruct / chat model', 'a base model after SFT (and usually alignment).']],
      ex: [{ h: 'A single SFT training example', p: ['One training row is a full conversation rendered with the model chat template. Only the tokens after the final assistant marker contribute to the loss.'],
        code: '<|system|>\nYou are a concise assistant.\n<|user|>\nWhat is the boiling point of water at sea level?\n<|assistant|>\n100 degrees Celsius (212 F) at 1 atm.<|end|>\n\n# loss is computed ONLY on the assistant response tokens' }],
      note: 'SFT teaches format and helpfulness by imitation. It cannot easily teach the model to prefer better answers over merely plausible ones — that is what alignment adds.' },

    { h: 'Alignment: RLHF, DPO & Constitutional AI', p: [
      'SFT imitates demonstrations, but we often can not write the ideal answer — yet we can <i>compare</i> two answers and say which is better. Alignment turns those preferences into a training signal so the model produces responses humans actually prefer (helpful, honest, harmless).',
      '<b>RLHF</b> (Reinforcement Learning from Human Feedback) has two stages. First, collect human rankings of model outputs and train a <b>reward model</b> R(x,y) to predict which response a human prefers. Second, use reinforcement learning — typically <b>PPO</b> — to update the policy (the LLM) to maximise reward, with a <b>KL penalty</b> that keeps it from drifting too far from the SFT model (which would let it "hack" the reward with gibberish).',
      '<b>DPO</b> (Direct Preference Optimization) achieves the same goal without training a separate reward model or running RL: it derives a simple classification-style loss directly on preference pairs <code>(y_win, y_lose)</code>, making it far simpler and more stable to implement. <b>Constitutional AI</b> (Anthropic) reduces human labelling further: the model critiques and revises its own outputs against a written set of principles (a "constitution"), generating AI feedback (RLAIF) that supplements or replaces human preference labels.'],
      eqn: 'RLHF:  max_θ  E[ R(x,y) ] − β·KL( π_θ(y|x) ‖ π_ref(y|x) )\nDPO loss:  −log σ( β·[ log π_θ(y_w|x)/π_ref(y_w|x) − log π_θ(y_l|x)/π_ref(y_l|x) ] )',
      table: { cols: ['Method', 'Needs reward model?', 'Needs RL loop?', 'Trade-off'], rows: [
        ['RLHF (PPO)', 'Yes', 'Yes', 'Powerful and flexible, but complex and finicky to tune'],
        ['DPO', 'No', 'No', 'Simple, stable, offline; slightly less flexible than online RL'],
        ['Constitutional AI (RLAIF)', 'Optional', 'Yes/No', 'Cuts human labelling by using AI feedback against written principles']] },
      ex: [{ h: 'How a reward model is trained', p: ['The reward model sees a prompt and two responses labelled "chosen" and "rejected" by a human, and learns to score the chosen one higher. The loss is a simple pairwise logistic (Bradley-Terry) objective.'],
        code: 'import torch, torch.nn.functional as F\n# r_chosen, r_rejected: scalar reward-model scores for one pair\nr_chosen   = reward_model(prompt, chosen)\nr_rejected = reward_model(prompt, rejected)\n# want chosen > rejected:\nloss = -F.logsigmoid(r_chosen - r_rejected).mean()\nloss.backward()' }],
      note: 'The KL term (RLHF) and the reference-model ratio (DPO) play the same role: anchor the tuned model to its starting point so alignment does not destroy fluency.' },

    { h: 'Inference memory math: params, bytes & the KV cache', p: [
      'To run a model you must fit it in memory (VRAM on a GPU, or RAM/unified memory locally). The dominant cost is the <b>weights</b>: <code>memory ≈ params × bytes-per-param</code>. In FP16/BF16 each parameter is 2 bytes; in INT8, 1 byte; in INT4, roughly 0.5 bytes. So a 7B model needs about <b>14 GB</b> in FP16 but only ~<b>3.5 GB</b> in INT4 — the difference between "needs a data-centre GPU" and "runs on a laptop".',
      'On top of the weights you pay for the <b>KV cache</b>: to avoid recomputing attention over the whole prompt at every step, the model caches the key and value vectors of every past token, in every layer. This grows <b>linearly with sequence length</b> and is why long contexts are expensive. A rough estimate: <code>KV bytes ≈ 2 · layers · seq_len · d_model · bytes</code> (the 2 is keys+values).',
      'A practical planning formula is therefore <code>VRAM ≈ weights + KV-cache + a ~15-20% overhead</code> for activations, CUDA context and fragmentation.'],
      eqn: 'weights_bytes = N_params × bytes_per_param\nKV_bytes ≈ 2 × n_layers × seq_len × d_model × bytes_per_elem\nVRAM ≈ (weights + KV) × ~1.2',
      ex: [{ h: 'A 7B model: FP16 vs INT4', p: ['Weights: 7e9 params. In <b>FP16</b> that is <code>7e9 × 2 = 14 GB</code>; in <b>INT4</b> it is <code>7e9 × 0.5 ≈ 3.5 GB</code>. Now add a KV cache for a 4096-token context on a typical 7B config (32 layers, d_model 4096), in FP16: <code>2 × 32 × 4096 × 4096 × 2 bytes ≈ 2.1 GB</code>. So FP16 needs ~16 GB before overhead (a 24 GB card); INT4 fits in ~7 GB (a laptop GPU).'],
        code: 'def vram_gb(params, bytes_per_param, layers, d_model, seq_len, kv_bytes=2):\n    weights = params * bytes_per_param\n    kv = 2 * layers * seq_len * d_model * kv_bytes   # keys + values\n    return (weights + kv) * 1.2 / 1e9                # +20% overhead\n\nvram_gb(7e9, 2.0, 32, 4096, 4096)   # FP16  -> ~19 GB\nvram_gb(7e9, 0.5, 32, 4096, 4096)   # INT4  -> ~7-8 GB' }],
      note: 'Rule of thumb: FP16 needs ~2 GB of VRAM per billion parameters (plus KV cache); INT4 needs ~0.5 GB per billion. Always leave headroom for the growing KV cache on long chats.' },

    { h: 'Quantization: FP16 → INT8 → INT4 and the file formats', p: [
      '<b>Quantization</b> stores weights (and sometimes activations) in fewer bits, trading a small accuracy loss for large savings in memory and bandwidth. Because LLMs are usually <b>memory-bandwidth-bound</b> at inference, smaller weights also mean <i>faster</i> generation, not just a smaller footprint.',
      'Going from FP16 to INT8 halves memory with almost no quality loss; INT4 halves it again with a modest, usually acceptable, degradation. Modern methods quantize in <b>groups</b> with per-group scales, and protect the most salient weights, so 4-bit models stay remarkably strong.',
      'The ecosystem has three dominant schemes. <b>GPTQ</b> and <b>AWQ</b> are calibration-based post-training methods aimed at GPU inference (AWQ preserves activation-important channels). <b>GGUF</b> is the file format used by <code>llama.cpp</code> for CPU/GPU inference on consumer hardware, with a family of quant levels (e.g. Q4_K_M) that mix bit-widths across tensors.'],
      table: { cols: ['Precision', 'Bytes/param', '7B model size', 'Quality impact'], rows: [
        ['FP32', '4', '~28 GB', 'reference, rarely used for inference'],
        ['FP16 / BF16', '2', '~14 GB', 'baseline for serving'],
        ['INT8', '1', '~7 GB', 'near-lossless'],
        ['INT4', '~0.5', '~3.5 GB', 'small but usually acceptable loss']] },
      terms: [['GPTQ', 'post-training, layer-wise error-minimising 4-bit quantization for GPUs.'], ['AWQ', 'activation-aware weight quantization; protects salient channels.'], ['GGUF', 'llama.cpp container format with mixed-precision quant levels (Q4_K_M, Q5_K_M, Q8_0…).'], ['Group size', 'weights share a scale in blocks (e.g. 128); smaller groups = better accuracy, more overhead.']],
      ex: [{ h: 'Loading a 4-bit model with bitsandbytes', p: ['Transformers can quantize on the fly to 4-bit (NF4) so a large model fits on a small GPU. This is also the foundation of QLoRA fine-tuning.'],
        code: 'from transformers import AutoModelForCausalLM, BitsAndBytesConfig\nimport torch\nqcfg = BitsAndBytesConfig(\n    load_in_4bit=True,\n    bnb_4bit_quant_type="nf4",          # NormalFloat4\n    bnb_4bit_compute_dtype=torch.bfloat16,\n    bnb_4bit_use_double_quant=True,     # quantize the quant constants too\n)\nmodel = AutoModelForCausalLM.from_pretrained(\n    "meta-llama/Llama-2-7b-hf", quantization_config=qcfg, device_map="auto")' }] },

    { h: 'The KV cache & why long context is expensive', p: [
      'Attention lets every token look at every previous token. Naively, generating token <i>t</i> would require recomputing keys and values for all <i>t−1</i> prior tokens — quadratic work. The <b>KV cache</b> avoids this by storing each token key and value the first time they are computed, so each new token only computes its own K/V and attends against the cache. This makes generation linear per step, but the cache itself grows with every token.',
      'Two costs follow. <b>Memory</b>: the cache size is proportional to <code>layers × seq_len × d_model</code>, so doubling the context doubles KV memory (see the memory section). <b>Compute</b>: attention is still O(seq_len) per new token, so later tokens in a long context are slower to produce. This is the fundamental reason context length is a first-class cost driver, and why techniques like <b>grouped-query attention (GQA)</b>, <b>paged attention</b>, and <b>sliding-window attention</b> exist — they shrink or better-manage the KV cache.'],
      eqn: 'KV_cache_bytes = 2 × n_layers × seq_len × d_model × bytes_per_elem\n(2 = keys + values;  grows linearly in seq_len)',
      ex: [{ h: 'KV cache growth for a long chat', p: ['Take a 32-layer, d_model-4096 model in FP16. Per token the cache costs <code>2 × 32 × 4096 × 2 = 512 KB</code>. A 32k-token context therefore holds <code>512 KB × 32768 ≈ 16 GB</code> of KV cache — more than the model weights themselves at 4-bit. Long context, not model size, is often the binding constraint.'],
        code: 'def kv_gb(layers, d_model, seq_len, bytes_per_elem=2):\n    per_token = 2 * layers * d_model * bytes_per_elem\n    return per_token * seq_len / 1e9\n\nkv_gb(32, 4096, 4096)    # ~2.1 GB\nkv_gb(32, 4096, 32768)   # ~16.8 GB  (dominates!)' }],
      note: 'Grouped-query attention (GQA) shares K/V heads across query heads, cutting KV memory several-fold — a big reason modern 7B-class models handle long contexts affordably.' },

    { h: 'Running models locally: llama.cpp, Ollama, vLLM, TGI', p: [
      'You do not train models to use them — you <b>serve</b> them. The right runtime depends on hardware and goal. For <b>local/consumer</b> use, <code>llama.cpp</code> runs GGUF-quantized models efficiently on CPU, Apple Silicon (Metal) and consumer GPUs, and <b>Ollama</b> wraps it in a friendly <code>ollama run</code> CLI plus a local REST API with a model library.',
      'For <b>production serving</b>, throughput and concurrency matter. <b>vLLM</b> uses <b>PagedAttention</b> (KV cache managed like OS virtual memory) plus continuous batching to serve many users at high throughput. <b>TGI</b> (Text Generation Inference, from Hugging Face) is a comparable production server with tensor parallelism and streaming. Both expose OpenAI-compatible HTTP endpoints so client code is portable.'],
      table: { cols: ['Runtime', 'Best for', 'Key feature'], rows: [
        ['llama.cpp', 'Laptops, CPU, Apple Silicon', 'GGUF quant, tiny footprint, no GPU required'],
        ['Ollama', 'Local dev & prototyping', 'One-line model pull/run + local API'],
        ['vLLM', 'High-throughput GPU serving', 'PagedAttention + continuous batching'],
        ['TGI', 'Production GPU serving', 'Tensor parallelism, streaming, HF integration']] },
      ex: [{ h: 'Serving and calling a model with Ollama', p: ['Ollama pulls a quantized model and exposes a local endpoint. The same OpenAI-style client works against Ollama, vLLM or TGI by swapping the base URL.'],
        code: '# terminal\nollama run llama3            # pulls + chats\n# or start the server and call the API:\n\nimport requests\nr = requests.post("http://localhost:11434/api/chat", json={\n    "model": "llama3",\n    "messages": [{"role": "user", "content": "Explain the KV cache in one line."}],\n    "stream": False,\n})\nprint(r.json()["message"]["content"])' }] },

    { h: 'Fine-tuning: full vs PEFT, LoRA & QLoRA', p: [
      'Sometimes prompting is not enough and you need to change the weights. <b>Full fine-tuning</b> updates every parameter — highest ceiling, but it needs enough memory to hold the model plus optimizer state (roughly 4× the weights for Adam), and it produces a full-size copy per task. Usually overkill.',
      '<b>PEFT</b> (Parameter-Efficient Fine-Tuning) freezes the base model and trains a tiny number of new parameters. The dominant method is <b>LoRA</b>: for a weight matrix <code>W</code> (shape d×k), instead of updating W directly you learn a low-rank correction <code>ΔW = B·A</code>, where <code>A</code> is r×k and <code>B</code> is d×r with rank <code>r</code> tiny (8–64). The forward pass becomes <code>h = Wx + (α/r)·BAx</code>. Only A and B train — often <b>&lt;1%</b> of parameters — and the adapter is a few megabytes you can hot-swap per task.',
      '<b>QLoRA</b> combines LoRA with a 4-bit (NF4) frozen base model: the huge base weights sit in 4-bit, gradients flow only through the small LoRA adapters in higher precision. This lets you fine-tune a 7B–70B model on a single consumer/pro GPU.'],
      eqn: 'h = W x + (α/r) · (B A) x        A ∈ ℝ^{r×k},  B ∈ ℝ^{d×r},  r ≪ min(d,k)\ntrainable params per matrix = r·(d + k)   vs   full = d·k',
      ex: [{ h: 'Counting LoRA parameters', p: ['Take an attention projection of shape <code>d = k = 4096</code>. Full fine-tuning of this one matrix trains <code>4096 × 4096 ≈ 16.8M</code> params. LoRA with rank <code>r = 8</code> trains only <code>r·(d + k) = 8 × (4096 + 4096) = 65,536</code> params — about <b>0.4%</b>. Across a whole model that is the difference between updating billions vs a few million weights.'],
        eqn: 'full = 4096·4096 = 16,777,216      LoRA(r=8) = 8·(4096+4096) = 65,536   (~0.39%)',
        code: 'd, k, r = 4096, 4096, 8\nfull = d * k\nlora = r * (d + k)\nprint(full, lora, f"{100*lora/full:.2f}%")\n# 16777216 65536 0.39%' }],
      code: 'from peft import LoraConfig, get_peft_model\nlora_cfg = LoraConfig(\n    r=8, lora_alpha=16, lora_dropout=0.05,\n    target_modules=["q_proj", "k_proj", "v_proj", "o_proj"],\n    bias="none", task_type="CAUSAL_LM",\n)\nmodel = get_peft_model(base_model, lora_cfg)\nmodel.print_trainable_parameters()\n# trainable: ~4M || all: ~7B || trainable%: 0.06',
      note: 'alpha/r is a scaling factor on the adapter; a common heuristic is alpha = 2·r. Higher rank = more capacity but more params and more overfitting risk on small datasets.' },

    { h: 'RAG vs fine-tuning: when to use which', p: [
      'Two very different tools get confused. <b>Fine-tuning</b> changes the model behaviour, tone, format and skills — it teaches the model <i>how</i> to act. <b>Retrieval-Augmented Generation (RAG)</b> changes what the model <i>knows at answer time</i> by fetching relevant documents from a vector store and injecting them into the prompt — it teaches the model <i>what</i> facts to use, without touching the weights.',
      'The default guidance: if you need <b>current, private, or frequently-changing knowledge</b> with citations, use RAG. If you need a <b>consistent style, output schema, domain skill, or lower latency/cost</b>, fine-tune. They compose well — fine-tune a model to reliably follow your format, then feed it retrieved context for facts.',
      'RAG works by embedding your documents into vectors, storing them in a vector database, embedding the user query, retrieving the nearest chunks by cosine similarity, and prepending them to the prompt as grounding.'],
      table: { cols: ['Dimension', 'RAG', 'Fine-tuning'], rows: [
        ['Best for', 'Fresh / private / factual knowledge', 'Behaviour, style, format, skills'],
        ['Update cost', 'Cheap — just re-index documents', 'Expensive — retrain per change'],
        ['Citations', 'Natural (you have the source chunks)', 'None inherent'],
        ['Reduces hallucination', 'Yes, by grounding in sources', 'Not directly'],
        ['Latency / cost', 'Higher (retrieval + long prompt)', 'Lower per call once trained'],
        ['Data needed', 'A document corpus', 'Labelled examples of desired behaviour']] },
      ex: [{ h: 'A minimal RAG retrieval step', p: ['Embed the query, find the closest document chunks by cosine similarity, and stuff them into the prompt. The generation call then answers grounded in retrieved text.'],
        code: 'import numpy as np\n\ndef retrieve(query, chunks, embed, k=3):\n    q = embed(query)\n    scored = [(c, np.dot(q, embed(c)) /\n                 (np.linalg.norm(q) * np.linalg.norm(embed(c)))) for c in chunks]\n    scored.sort(key=lambda t: t[1], reverse=True)\n    return [c for c, _ in scored[:k]]\n\ncontext = "\\n".join(retrieve(user_q, docs, embed))\nprompt = f"Answer using ONLY this context:\\n{context}\\n\\nQ: {user_q}"' }],
      note: 'RAG cannot fix a model that is bad at following instructions, and fine-tuning cannot inject facts the model has never seen without heavy repetition. Diagnose the problem first, then pick.' },

    { h: 'Prompt engineering (in brief) & structured output', p: [
      'Before fine-tuning or RAG, the cheapest lever is the <b>prompt</b>. Clear instructions, worked examples (<b>few-shot</b>), explicit output schemas, and step-by-step reasoning requests (<b>chain-of-thought</b>) often close most of the gap for free. Because it changes nothing about the model, it is the first thing to try and the last thing to stop iterating on.',
      'Key techniques in one breath: <b>zero-shot</b> (just ask), <b>few-shot</b> (show examples), <b>chain-of-thought</b> ("think step by step"), <b>role/system prompts</b> (set persona and constraints), and <b>output formatting</b> (demand JSON or a schema so results are machine-parseable). For anything nontrivial, pin the output format explicitly — it is the difference between a demo and a pipeline.'],
      ex: [{ h: 'Forcing structured JSON output', p: ['Specifying the exact schema and asking for JSON-only makes the response parseable and reliable downstream. Pair it with a validation/retry loop for production.'],
        code: 'prompt = """Extract the fields as JSON. Output JSON only, no prose.\nSchema: {"name": string, "age": integer, "city": string}\n\nText: "Maria is a 29-year-old designer living in Lisbon."\n"""\n\nimport json\nresp = call_llm(prompt)          # returns a string\ndata = json.loads(resp)          # {"name":"Maria","age":29,"city":"Lisbon"}' }],
      note: 'This section is deliberately short — see the dedicated Prompt Engineering module for the full treatment of patterns, evaluation and failure modes.' },

    { h: 'Agents: the plan → act → observe loop & tool calling', p: [
      'An <b>agent</b> is an LLM placed in a loop with tools and a goal. Instead of emitting one answer, it repeatedly: <b>plans</b> the next step, <b>acts</b> by calling a tool (search, code execution, an API, a database), <b>observes</b> the result, and continues until the goal is met or a stop condition triggers. The LLM is the reasoning engine; tools give it hands.',
      '<b>Function / tool calling</b> is the mechanism. You describe available tools as JSON schemas; the model, instead of answering in prose, emits a structured request naming a tool and its arguments. Your code executes the tool and feeds the result back as a new message. The <b>ReAct</b> pattern (Reason + Act) interleaves explicit reasoning traces with these tool calls, which improves reliability on multi-step tasks.',
      '<b>Memory</b> has two forms: short-term memory is just the <b>context window</b> (the running conversation), and long-term memory is an external <b>vector store</b> the agent can write to and retrieve from — the same RAG machinery, used as the agent notebook. <b>Multi-agent</b> systems decompose a problem across specialised agents (e.g. a planner, a coder, a critic) that pass messages, trading more coordination overhead for better division of labour.'],
      eqn: 'loop:  state → LLM plans → tool call → execute → observation → append to context → repeat\n       until  final answer  OR  step limit  OR  stop token',
      terms: [['Tool / function calling', 'the model emits a structured JSON call; your code runs it and returns the result.'], ['ReAct', 'interleave Reasoning traces with Actions (tool calls) for multi-step tasks.'], ['Short-term memory', 'the context window holding the current conversation.'], ['Long-term memory', 'an external vector store the agent reads/writes across sessions.'], ['Multi-agent', 'several specialised agents (planner, worker, critic) coordinating via messages.']],
      ex: [{ h: 'A tool call the model emits', p: ['Given a weather tool schema, the model does not answer in prose — it returns a structured call. Your runtime executes <code>get_weather(city="Paris")</code>, then returns the observation as a tool message for the model to use in its final reply.'],
        code: '// tool definition given to the model\n{\n  "name": "get_weather",\n  "description": "Get current weather for a city",\n  "parameters": {\n    "type": "object",\n    "properties": { "city": { "type": "string" } },\n    "required": ["city"]\n  }\n}\n\n// what the model emits instead of prose:\n{ "tool_call": { "name": "get_weather",\n                 "arguments": { "city": "Paris" } } }' }],
      code: 'import json\n\ntools = {"get_weather": lambda city: f"{city}: 21C, clear"}\n\ndef agent_step(messages, model):\n    out = model(messages, tools=tool_schemas)     # model may request a tool\n    if out.get("tool_call"):\n        call = out["tool_call"]\n        result = tools[call["name"]](**call["arguments"])   # ACT\n        messages.append({"role": "tool", "name": call["name"],\n                         "content": json.dumps(result)})     # OBSERVE\n        return agent_step(messages, model)         # loop: plan again\n    return out["content"]                          # final answer',
      note: 'Give agents the fewest, clearest tools that cover the task, hard step limits, and validation on tool outputs. Unbounded loops and vague tools are the top causes of runaway cost and failure.' },

    { h: 'Evaluating LLMs: benchmarks, LLM-as-judge & hallucination', p: [
      'You cannot improve what you cannot measure, and LLM evaluation is genuinely hard because outputs are open-ended. Three complementary approaches are standard. <b>Benchmarks</b> give comparable numbers on fixed tasks — MMLU (knowledge), GSM8K (math), HumanEval (coding), and others — useful for tracking capability but prone to <b>contamination</b> (test data leaking into training) and to not reflecting your real use case.',
      '<b>LLM-as-judge</b> uses a strong model to score or compare outputs against a rubric — scalable and surprisingly well-correlated with human preference, but biased (toward longer answers, its own style, or the first option shown), so it needs careful rubric design and position-swapping. <b>Human evaluation</b> remains the gold standard for nuanced quality but is slow and costly.',
      '<b>Hallucination</b> — confident, fluent, false statements — is the signature failure mode. Mitigations: ground answers with RAG and demand citations, ask the model to say "I do not know", lower temperature for factual tasks, and add a verification pass. For anything high-stakes, measure hallucination explicitly rather than assuming fluency implies correctness.'],
      table: { cols: ['Method', 'Scales?', 'Strength', 'Weakness'], rows: [
        ['Static benchmarks', 'Yes', 'Comparable, cheap, repeatable', 'Contamination; may miss your task'],
        ['LLM-as-judge', 'Yes', 'Fast, decent human correlation', 'Position/length/self bias'],
        ['Human eval', 'No', 'Gold standard for nuance', 'Slow, expensive, subjective'],
        ['Task metrics (exact match, unit tests)', 'Yes', 'Objective when applicable', 'Only for verifiable outputs']] },
      ex: [{ h: 'A pairwise LLM-as-judge prompt', p: ['Ask a strong model to pick the better of two answers against a rubric, and swap the order on a second call to cancel position bias. Aggregate over many prompts for a win-rate.'],
        code: 'judge_prompt = """You are grading two answers to a question.\nCriteria: correctness, then helpfulness, then concision.\nReply with only "A" or "B".\n\nQuestion: {q}\nAnswer A: {a}\nAnswer B: {b}\n"""\n# run once as (A,B) and once as (B,A); if they disagree -> call it a tie' }],
      note: 'Build a small, task-specific eval set of real prompts with known-good answers early. A 100-example internal eval beats a leaderboard number for deciding whether a change actually helped.' },

    { h: 'Cost & latency: what you actually pay for', p: [
      'Serving LLMs has a distinctive cost profile driven by <b>tokens</b>. Hosted APIs bill per input and output token (output usually costs more), so cost scales with prompt length × calls — which is why stuffing giant RAG contexts or long agent histories into every request gets expensive fast. Self-hosting trades per-token fees for GPU rental, where the metric is throughput (tokens/second) per dollar.',
      'Latency has two components. <b>Time-to-first-token (TTFT)</b> is dominated by <b>prefill</b> — processing the whole prompt — so it grows with input length. <b>Time-per-output-token</b> (the <b>decode</b> phase) is memory-bandwidth-bound and roughly constant per token, so total latency ≈ TTFT + tokens × per-token time. Long prompts hurt TTFT; long answers hurt total time.',
      'The main levers: <b>prompt caching</b> (reuse the KV cache of a shared prefix across calls to slash prefill cost), <b>quantization</b> and <b>smaller/distilled models</b> for cheaper decode, <b>batching</b> (vLLM/TGI) to raise throughput, <b>streaming</b> to improve perceived latency, and trimming context (summarise old turns, retrieve fewer chunks) to cut both cost and TTFT. <b>Routing</b> — a cheap model for easy queries, a strong model only when needed — is often the single biggest cost win.'],
      terms: [['TTFT', 'time-to-first-token; set by prefill, grows with prompt length.'], ['Prefill vs decode', 'compute-bound prompt processing vs bandwidth-bound token-by-token generation.'], ['Prompt caching', 'reuse a shared prefix KV cache to skip re-prefilling it.'], ['Model routing', 'send easy queries to a cheap model, hard ones to a strong model.'], ['Distillation', 'train a small model to mimic a large one for cheaper inference.']],
      ex: [{ h: 'Estimating API cost per request', p: ['Cost is just input and output tokens times their per-token prices. A RAG call with a 6,000-token context and a 400-token answer at ($0.50, $1.50) per million tokens costs about a third of a cent — trivial once, but multiply by millions of requests and prompt size becomes the budget.'],
        eqn: 'cost = (in_tok/1e6)·price_in + (out_tok/1e6)·price_out',
        code: 'def request_cost(in_tok, out_tok, price_in, price_out):\n    return in_tok/1e6*price_in + out_tok/1e6*price_out\n\nrequest_cost(6000, 400, 0.50, 1.50)   # ~$0.0036 per call\n# 1,000,000 calls/month -> ~$3,600  (context length dominates)' }],
      note: 'The cheapest token is the one you do not send. Trimming context and caching shared prefixes usually beats chasing a marginally cheaper model.' },
  ]
});
