/* Deep dive — MLOps */
window.AtlasRef && window.AtlasRef.register('mlops', {
  color: '#34D399',
  title: 'Shipping and running models in production',
  lead: 'MLOps is DevOps for machine learning — the practices that take a model from a notebook to a reliable, monitored, reproducible service. The twist: unlike ordinary software, an ML system changes along three axes at once — data, model, and code — so every discipline (versioning, testing, deployment, monitoring) has to account for all three.',
  sections: [

    { h: 'What MLOps is, and why ML is harder than software', p: [
      '<b>MLOps</b> applies DevOps ideas — automation, continuous integration, continuous delivery, observability — to machine-learning systems. The goal is the same: ship reliably and often, catch regressions early, and recover fast. But a classic software system has only one moving part that changes: <b>code</b>. An ML system has <b>three</b>: the <b>code</b>, the <b>model</b> (weights learned from data), and the <b>data</b> itself. Any one can drift while the other two stand still, and a "green" test suite can sit on top of a model that is quietly rotting because the world changed.',
      'This is why the well-known observation that ML systems accumulate <b>hidden technical debt</b> holds: the code is a small box inside a much larger system of data pipelines, feature stores, monitoring, and retraining loops. A change to an upstream data source — a currency, a units change, a new app version emitting different logs — can degrade a model with no code change at all. MLOps exists to make that entire system reproducible, testable, and observable.'],
      terms: [['Training–serving skew', 'features computed differently in training vs production, giving silently wrong predictions.'], ['CACE principle', '"Changing Anything Changes Everything" — ML models entangle all inputs, so no feature is truly independent.'], ['Pipeline jungle', 'organically-grown glue code between data sources; a classic ML debt smell.'], ['Feedback loop', 'the model influences the data it is later trained on (e.g. a recommender shaping clicks).']],
      note: 'A useful mental model: in software you version code; in ML you must version code AND data AND the model together, because a bug can hide in any of the three.' },

    { h: 'Reproducibility: pin data, code, seeds and environment', p: [
      'A result is <b>reproducible</b> when re-running the same pipeline yields the same model (or a statistically equivalent one). Four things must be pinned. <b>Code</b>: a git commit SHA. <b>Data</b>: an immutable snapshot or content hash of the exact rows used. <b>Environment</b>: exact library versions and hardware (a CUDA or cuDNN bump can change numerics). <b>Randomness</b>: every seed — Python, NumPy, the framework, the data-loader shuffling, and dropout.',
      'Even with all seeds fixed, GPU operations can be nondeterministic because floating-point reductions are order-sensitive across parallel threads. Frameworks expose a "deterministic mode" that trades a little speed for bit-exact runs — worth it for debugging and audits, not always for production training.'],
      ex: [{ h: 'A seed-everything helper', p: ['Set every source of randomness in one call at the top of a run, and record the seed alongside the run so it can be replayed. Determinism flags force cuDNN to pick reproducible kernels.'],
        code: 'import os, random, numpy as np, torch\n\ndef seed_everything(seed=42):\n    os.environ[\'PYTHONHASHSEED\'] = str(seed)\n    random.seed(seed)\n    np.random.seed(seed)\n    torch.manual_seed(seed)\n    torch.cuda.manual_seed_all(seed)\n    # trade speed for bit-exact reproducibility\n    torch.backends.cudnn.deterministic = True\n    torch.backends.cudnn.benchmark = False\n\nseed_everything(42)' }],
      terms: [['Immutable snapshot', 'data written once and never edited; new data becomes a new version.'], ['Content hash', 'a fingerprint (e.g. md5/sha256) of the data so any change is detectable.'], ['Lockfile', 'pinned exact dependency versions (requirements.txt, poetry.lock, conda env).'], ['Deterministic mode', 'framework flag forcing reproducible GPU kernels at some speed cost.']] },

    { h: 'Experiment tracking (MLflow, Weights & Biases)', p: [
      'Training is an experimental science: dozens of runs with different hyperparameters, features, and data slices. <b>Experiment tracking</b> records, for every run, the <b>parameters</b>, <b>metrics</b>, <b>artifacts</b> (the model file, plots), and the <b>code version</b> — so you can compare runs, reproduce the winner, and never again ask "which config produced that 0.94 model?". Tools like <b>MLflow</b> (open-source, self-hostable) and <b>Weights &amp; Biases</b> (hosted, rich dashboards) provide this out of the box.',
      'The discipline is simple: log <i>everything</i> that could explain a difference between runs. A metric without its parameters and data version is an anecdote, not a result.'],
      ex: [{ h: 'Tracking a run with MLflow', p: ['Wrap training in an MLflow run. Parameters and metrics are logged as key–values; the trained model is logged as a versioned artifact you can later load or deploy. The git SHA ties the run back to exact code.'],
        code: 'import mlflow, mlflow.sklearn\nfrom sklearn.ensemble import RandomForestClassifier\n\nmlflow.set_experiment(\'churn-model\')\nwith mlflow.start_run(run_name=\'rf-v3\'):\n    params = {\'n_estimators\': 300, \'max_depth\': 12}\n    mlflow.log_params(params)\n    mlflow.set_tag(\'git_sha\', \'c04f133\')\n    mlflow.set_tag(\'data_version\', \'2026-07-01\')\n\n    clf = RandomForestClassifier(**params).fit(X_train, y_train)\n    auc = roc_auc_score(y_val, clf.predict_proba(X_val)[:, 1])\n\n    mlflow.log_metric(\'val_auc\', auc)\n    mlflow.sklearn.log_model(clf, \'model\',\n                             registered_model_name=\'churn\')' }],
      note: 'Weights & Biases uses a near-identical shape: wandb.init(config=params), then wandb.log({\'val_auc\': auc}) inside the loop. The concept — params in, metrics/artifacts out, tied to a run id — is universal.' },

    { h: 'Versioning data and models (DVC, model registry)', p: [
      'Git is built for text-sized code, not multi-gigabyte datasets or model checkpoints. <b>DVC</b> (Data Version Control) solves this: it stores small pointer files in git while the large blobs live in object storage (S3, GCS), so <code>git checkout</code> of an old commit restores the exact data and model that went with it. Now "the data" is versioned like code.',
      'Trained models get a parallel home: a <b>model registry</b> (in MLflow, SageMaker, Vertex, etc.). A model version is promoted through <b>stages</b> — typically <b>None → Staging → Production → Archived</b> — with the transition to Production gated by approval and evaluation. The registry becomes the single source of truth for "what is live right now", decoupling the deploy from any one training run.'],
      ex: [{ h: 'Versioning a dataset with DVC', p: ['Track the raw dataset with DVC, commit the tiny .dvc pointer to git, and push the actual bytes to remote storage. Anyone who clones the repo and runs dvc pull gets the exact same data.'],
        code: '# one-time: point DVC at remote object storage\ndvc remote add -d storage s3://my-bucket/dvcstore\n\n# track a large dataset (git tracks only data/train.csv.dvc)\ndvc add data/train.csv\ngit add data/train.csv.dvc data/.gitignore\ngit commit -m \'data: churn training set v2026-07-01\'\ndvc push        # upload bytes to S3\n\n# later, reproduce an old experiment exactly\ngit checkout <old-sha> && dvc pull' }],
      terms: [['Pointer file', 'a small .dvc/git-tracked file holding the hash + storage location of a big blob.'], ['Model registry', 'catalog of model versions with stages, lineage and approvals.'], ['Stage transition', 'promoting a version None→Staging→Production, usually gated by tests/approval.'], ['Lineage', 'the chain: data version → run → model version → deployment.']] },

    { h: 'CI/CD for ML: test the data and the model, not just the code', p: [
      'Continuous integration for ML keeps the software checks (unit tests, linting) but adds two categories software never needed. <b>Data tests</b> validate the inputs: schema (right columns and types), ranges (ages are 0–120), nulls within tolerance, category sets, and distribution checks against a reference. <b>Model tests</b> validate behaviour: a minimum metric on a held-out set, no regression versus the current production model, performance on critical slices (does accuracy hold for every region?), and behavioural/invariance checks (negating a sentence should flip sentiment).',
      'The <b>CD</b> half is a <b>continuous training</b> pipeline: on a trigger it retrains, evaluates against gates, registers the model if it passes, and rolls it out progressively. The deliverable is not just code — it is code + data + a validated model, promoted together.'],
      ex: [{ h: 'A model-quality gate in CI', p: ['Before a candidate can be promoted, CI asserts it clears an absolute bar and does not regress the champion on a frozen evaluation set. Failing either check fails the build, so a worse model can never reach production silently.'],
        code: 'import mlflow, sys\n\nMIN_AUC = 0.85\ncandidate_auc = evaluate(candidate, X_test, y_test)   # 0.0-1.0\nchampion = mlflow.sklearn.load_model(\'models:/churn/Production\')\nchampion_auc = evaluate(champion, X_test, y_test)\n\nif candidate_auc < MIN_AUC:\n    sys.exit(f\'FAIL: {candidate_auc:.3f} < floor {MIN_AUC}\')\nif candidate_auc < champion_auc - 0.005:\n    sys.exit(f\'FAIL: regresses champion {champion_auc:.3f}\')\nprint(\'PASS: promoting candidate\')' }],
      code: '# .github/workflows/ml-ci.yml — a minimal ML CI pipeline\nname: ml-ci\non: [push]\njobs:\n  validate:\n    runs-on: ubuntu-latest\n    steps:\n      - uses: actions/checkout@v4\n      - run: pip install -r requirements.txt\n      - run: pytest tests/unit            # code tests\n      - run: python validate_data.py       # schema + range + drift\n      - run: python train.py --fast        # train candidate\n      - run: python quality_gate.py        # metric + no-regression\n      - run: python register_if_passed.py  # -> registry Staging' },

    { h: 'Deployment patterns: batch vs online, and safe rollout', p: [
      'The first decision is <b>batch vs online</b>. <b>Batch (offline)</b> scoring runs on a schedule over a big table and writes predictions to a store to be read later — cheap, high-throughput, and fine when freshness of minutes-to-hours is acceptable (churn scores, nightly recommendations). <b>Online (real-time)</b> serving answers a request per call with tight latency budgets — needed for fraud checks, search ranking, and anything user-facing.',
      'The second decision is <b>how to release a new version safely</b>. Never flip 100% of traffic to an unproven model. The table below is the standard toolkit; they compose (a canary can also be a shadow first).'],
      table: { cols: ['Pattern', 'How it works', 'Best for'], rows: [
        ['<b>Batch</b>', 'score a whole dataset on a schedule; store results', 'no strict latency; large volumes; periodic refresh'],
        ['<b>Online / real-time</b>', 'one prediction per request behind an API, low latency', 'user-facing, fraud, ranking, personalization'],
        ['<b>Shadow</b>', 'new model receives real traffic but its output is logged, not served', 'validating a model on live data with zero user risk'],
        ['<b>Canary</b>', 'route a small % of traffic to the new version, watch metrics, ramp up', 'gradual, reversible rollout with a small blast radius'],
        ['<b>A/B test</b>', 'split traffic between versions to measure a business KPI', 'proving the new model actually moves the metric that matters'],
        ['<b>Blue-green</b>', 'stand up full new (green) stack, switch traffic, keep blue for instant rollback', 'zero-downtime cutover with a fast escape hatch']] },
      note: 'Shadow answers "does it work on live data?"; canary answers "is it safe to expand?"; A/B answers "is it actually better?". They target different questions and are often used in sequence.' },

    { h: 'Serving, containerization and orchestration', p: [
      'Serving wraps a model behind an interface. For a bespoke Python service, <b>FastAPI</b> gives a typed, async HTTP endpoint with automatic validation and docs — perfect for a custom predict route. For higher-scale or framework-native needs, purpose-built servers do more out of the box: <b>TorchServe</b> (PyTorch) and <b>TensorFlow Serving</b> handle model loading, versioning and batching; <b>NVIDIA Triton</b> serves multiple frameworks with GPU dynamic batching and concurrent model execution; <b>KServe</b> runs any of these on Kubernetes with a standard inference protocol, autoscaling (including scale-to-zero), and canary rollouts built in.',
      'However you serve, <b>Docker</b> packages the model, code, and exact dependencies into an immutable <b>image</b> that runs identically on a laptop, CI, and the cluster — killing "works on my machine" and locking the environment for reproducibility. The image is the unit of deployment. <b>Kubernetes</b> then <b>orchestrates</b> many containers: it schedules them onto GPU-aware nodes, restarts crashed ones, load-balances traffic, and <b>autoscales</b> replicas with demand — while add-ons like KServe or Seldon layer inference-aware features (canary, scale-to-zero, request logging) on top. A key server-side trick throughout is <b>dynamic batching</b>: briefly buffering incoming requests to run them as one batch, trading a millisecond of latency for a large throughput gain on GPUs.'],
      ex: [{ h: 'A FastAPI predict endpoint', p: ['Load the model once at startup, validate the request body with a Pydantic schema, and return a typed response. The input schema is your first line of defence against training–serving skew and malformed calls.'],
        code: 'from fastapi import FastAPI\nfrom pydantic import BaseModel\nimport mlflow.pyfunc, pandas as pd\n\napp = FastAPI()\nmodel = mlflow.pyfunc.load_model(\'models:/churn/Production\')\n\nclass Features(BaseModel):\n    tenure: float\n    monthly_charges: float\n    contract: str\n\nclass Prediction(BaseModel):\n    churn_probability: float\n    model_version: str\n\n@app.get(\'/health\')\ndef health():\n    return {\'status\': \'ok\'}\n\n@app.post(\'/predict\', response_model=Prediction)\ndef predict(x: Features):\n    df = pd.DataFrame([x.dict()])\n    p = float(model.predict(df)[0])\n    return Prediction(churn_probability=p, model_version=\'churn/Production\')' },
        { h: 'Packaging and running the server on Kubernetes', p: ['Bake the FastAPI app into a Docker image, then run three replicas behind the Kubernetes scheduler with a CPU limit and a health probe so unhealthy pods are restarted. A HorizontalPodAutoscaler (omitted) then scales replicas on load.'],
        code: '# Dockerfile\nFROM python:3.11-slim\nWORKDIR /app\nCOPY requirements.txt .\nRUN pip install --no-cache-dir -r requirements.txt\nCOPY . .\nEXPOSE 8000\nCMD ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "8000"]\n---\n# deployment.yaml\napiVersion: apps/v1\nkind: Deployment\nmetadata: { name: churn-model }\nspec:\n  replicas: 3\n  selector: { matchLabels: { app: churn-model } }\n  template:\n    metadata: { labels: { app: churn-model } }\n    spec:\n      containers:\n        - name: server\n          image: registry/churn-model:v3\n          ports: [{ containerPort: 8000 }]\n          resources: { limits: { cpu: "1", memory: 1Gi } }\n          readinessProbe:\n            httpGet: { path: /health, port: 8000 }\n            initialDelaySeconds: 5' }],
      terms: [['Dynamic batching', 'group concurrent requests into one GPU batch for throughput.'], ['Model server', 'framework-native runtime (TorchServe/Triton) handling load, version, batch.'], ['Docker image', 'immutable package of code + deps; the unit of deployment.'], ['Orchestration', 'Kubernetes scheduling, self-healing and autoscaling of containers.']] },

    { h: 'Monitoring in production: system and ML-specific signals', p: [
      'A deployed model needs two layers of monitoring. The <b>system/service</b> layer is classic SRE: request <b>latency</b> tracked at percentiles (<b>p50</b> median, <b>p95</b>/<b>p99</b> tail — averages hide the tail that users feel), <b>throughput</b> (requests/sec), <b>error rate</b>, and resource saturation (CPU/GPU/memory). The <b>ML</b> layer watches the things software never had: the distribution of <b>inputs</b> (feature drift), the distribution of <b>predictions</b> (is the model suddenly predicting "fraud" 5× more?), and, when labels eventually arrive, live <b>accuracy/AUC</b>.',
      'The ML signals matter because a model can be perfectly healthy by every system metric — fast, no errors — while being <b>completely wrong</b> because the world moved. Prediction-distribution and label monitoring are the early-warning system.'],
      table: { cols: ['Signal', 'Layer', 'Why it matters'], rows: [
        ['Latency p50 / p95 / p99', 'system', 'tail latency is what users actually experience; SLOs live here'],
        ['Throughput (req/s)', 'system', 'capacity planning and autoscaling triggers'],
        ['Error rate', 'system', '5xx/timeouts signal an outage or a bad deploy'],
        ['Input feature distribution', 'ML', 'shifts vs training = data drift, the leading indicator'],
        ['Prediction distribution', 'ML', 'sudden class-balance shifts flag drift before labels arrive'],
        ['Live accuracy / AUC', 'ML', 'the ground truth of model health — once labels land']],
      },
      note: 'Rule of thumb: alert on system metrics for outages (minutes), and on ML metrics for degradation (hours to days). They fail on different timescales.' },

    { h: 'Drift: data, concept and label drift, and detecting it', p: [
      'Models decay because the statistical assumption behind them — that production data looks like training data — breaks over time. Three named failures. <b>Data (covariate) drift</b>: the input distribution P(X) changes (a new user demographic), even if the input→output rule is unchanged. <b>Concept drift</b>: the relationship P(Y|X) itself changes — the same inputs now imply a different answer (spending patterns after an economic shock). <b>Label drift</b>: the distribution of the target P(Y) shifts (fraud rate triples).',
      'Detection compares a recent production window against a training/reference baseline. For a single feature, the <b>Kolmogorov–Smirnov (KS) test</b> checks whether two continuous samples come from the same distribution. The <b>Population Stability Index (PSI)</b> bins a feature and sums the divergence between reference and current proportions — the industry-standard drift score, with rough thresholds <b>&lt;0.1</b> stable, <b>0.1–0.25</b> moderate shift, <b>&gt;0.25</b> significant drift.'],
      eqn: 'PSI = Σ (actual% − expected%) · ln(actual% / expected%)',
      ex: [{ h: 'A worked PSI drift check', p: ['Bin the reference and current feature into the same buckets, turn counts into proportions, and sum the PSI contribution per bin. Here the current data has shifted mass toward higher bins, pushing PSI into the "moderate drift — investigate" band.'],
        eqn: 'bin1: (.35 − .30)·ln(.35/.30) = .0077\nbin2: (.20 − .30)·ln(.20/.30) = .0405\nbin3: (.45 − .40)·ln(.45/.40) = .0059\nPSI ≈ 0.054   (< 0.1 -> still stable)',
        code: 'import numpy as np\n\ndef psi(expected, actual, bins=10):\n    # fix bin edges from the reference distribution\n    edges = np.quantile(expected, np.linspace(0, 1, bins + 1))\n    edges[0], edges[-1] = -np.inf, np.inf\n    e = np.histogram(expected, edges)[0] / len(expected)\n    a = np.histogram(actual,   edges)[0] / len(actual)\n    e, a = np.clip(e, 1e-6, None), np.clip(a, 1e-6, None)\n    return float(np.sum((a - e) * np.log(a / e)))\n\nscore = psi(reference_feature, live_feature)\nif score > 0.25:\n    trigger_retraining()      # significant drift' }],
      terms: [['Covariate drift', 'P(X) changes; the mapping X->Y is unchanged.'], ['Concept drift', 'P(Y|X) changes; yesterday\'s rule is now wrong.'], ['KS test', 'two-sample test on the max gap between empirical CDFs.'], ['PSI', 'binned reference-vs-current divergence; the standard drift metric.']] },

    { h: 'Retraining strategies: scheduled vs triggered', p: [
      'A drift signal is useless without a response: models that decay must be refreshed — the question is <i>when</i>. <b>Scheduled</b> retraining runs on a fixed cadence (nightly, weekly, monthly). It is simple and predictable, but it either wastes compute retraining a still-healthy model or reacts too slowly to a sudden shift. <b>Triggered</b> retraining fires on a condition: a drift metric (PSI &gt; 0.25 from the check above), a live-metric drop below an SLO, or the arrival of enough new labeled data. It is efficient and responsive but needs solid monitoring and guardrails to avoid retraining on a transient blip or a poisoned batch.',
      'Mature teams combine them: a scheduled floor guarantees freshness, and triggers catch fast breaks in between. Crucially, retraining is not automatically deploying — every retrained candidate re-enters the same CI quality gates and progressive rollout, so a bad refresh cannot reach users unchecked.'],
      table: { cols: ['Strategy', 'Trigger', 'Trade-off'], rows: [
        ['<b>Scheduled</b>', 'time cadence (e.g. weekly)', 'simple &amp; predictable; may retrain needlessly or lag a shock'],
        ['<b>Performance-triggered</b>', 'live metric drops below SLO', 'reacts to real harm but needs labels, which arrive late'],
        ['<b>Drift-triggered</b>', 'PSI / KS crosses a threshold', 'early, label-free signal; risks over-reacting to noise'],
        ['<b>Data-volume-triggered</b>', 'N new labeled examples collected', 'good for cold-start growth; ignores whether the model actually decayed']],
      },
      note: 'Always route a retrained model through the same gates as a human-authored one. "Automated retraining" must never mean "automated, unvalidated deployment".' },

    { h: 'Distributed and large-scale training', p: [
      'When a model or dataset outgrows one GPU, training goes distributed along two axes. <b>Data parallelism</b> replicates the whole model on every GPU, feeds each a different shard of the batch, and averages gradients across devices (all-reduce) — the default when the model fits in memory but data is large. <b>Model parallelism</b> splits the model itself across GPUs — needed when the weights alone do not fit; it comes in <b>tensor</b> (split individual layers) and <b>pipeline</b> (assign layer groups to stages) flavours.',
      'Modern large-model training leans on memory-sharding frameworks. <b>FSDP</b> (Fully Sharded Data Parallel) and <b>DeepSpeed ZeRO</b> shard the parameters, gradients, and optimizer states across GPUs instead of replicating them, cutting per-device memory dramatically and making billion-parameter training feasible. Orthogonally, <b>mixed-precision</b> training runs math in 16-bit (fp16/bf16) with a 32-bit master copy — roughly halving memory and speeding up compute on modern accelerators, using loss scaling to protect small gradients from underflow.'],
      table: { cols: ['Technique', 'Splits across GPUs', 'Use when'], rows: [
        ['<b>Data parallel (DDP)</b>', 'the batch (model replicated)', 'model fits on one GPU; you want throughput'],
        ['<b>Tensor parallel</b>', 'individual layers / matrices', 'a single layer is too big for one GPU'],
        ['<b>Pipeline parallel</b>', 'groups of layers into stages', 'a deep model exceeds one GPU\'s memory'],
        ['<b>FSDP / ZeRO</b>', 'params + grads + optimizer states', 'huge models; memory is the bottleneck'],
        ['<b>Mixed precision</b>', 'nothing — uses 16-bit math', 'almost always; free memory + speed win']],
      },
      ex: [{ h: 'Mixed precision with PyTorch AMP', p: ['Automatic Mixed Precision runs the forward and loss in 16-bit under autocast, while a GradScaler scales the loss to keep tiny gradients from underflowing to zero before the optimizer step. This is the cheapest large-model win available.'],
        code: 'import torch\nscaler = torch.cuda.amp.GradScaler()\n\nfor x, y in loader:\n    opt.zero_grad()\n    with torch.autocast(device_type=\'cuda\', dtype=torch.bfloat16):\n        loss = loss_fn(model(x), y)\n    scaler.scale(loss).backward()   # scale up to avoid fp16 underflow\n    scaler.step(opt)                # unscale + optimizer step\n    scaler.update()                 # adjust scale factor' }],
      terms: [['All-reduce', 'collective op averaging gradients across all data-parallel GPUs.'], ['ZeRO / FSDP', 'shard params/grads/optimizer states instead of replicating them.'], ['Loss scaling', 'multiply loss so small fp16 gradients survive; unscale before the step.'], ['bf16', 'brain-float 16: wider range than fp16, no loss scaling usually needed.']] },

    { h: 'Governance, cost and carbon', p: [
      '<b>Governance</b> makes an ML system accountable and auditable — increasingly a regulatory requirement, not just good hygiene. A <b>model card</b> documents a model\'s intended use, training data, evaluation results <i>broken down by subgroup</i>, known limitations, and ethical considerations — so a downstream user (or auditor) can judge fitness for a given purpose. <b>Lineage</b> records the full chain — which data version and code produced which model version, and where it is deployed — so any prediction can be traced to its origins.',
      'An <b>audit trail</b> logs who did what and when: who approved the Production promotion, when a model was rolled back, which config was live during an incident. <b>Approval gates</b> put a human (or a policy) in the loop before high-impact changes ship. Together these answer the questions a regulator or incident review will ask: what was live, who signed off, and can we reproduce and explain it?'],
      terms: [['Model card', 'a standardized doc: intended use, data, per-slice metrics, limitations, risks.'], ['Lineage / provenance', 'the traceable chain data->run->model->deployment.'], ['Audit trail', 'immutable log of actions, approvals, promotions and rollbacks.'], ['Approval gate', 'a required human/policy sign-off before a high-impact promotion.']],
      note: 'Fairness and reproducibility are governance concerns too: per-slice metrics in the model card surface disparate performance, and pinned lineage lets you reproduce any past decision under scrutiny.',
      ex: [{ h: 'Cost and carbon as first-class metrics', p: ['Training and serving cost real money and real energy, so mature teams track both. <b>Cost</b>: GPU-hours dominate training spend, and <b>inference</b> running 24/7 often outgrows training over a model\'s lifetime — so levers like spot instances, <b>scale-to-zero</b> idle endpoints, and model <b>compression</b> (quantization, distillation, pruning) matter. <b>Carbon</b>: energy × the grid\'s carbon intensity gives emissions, and because intensity varies by region and hour, scheduling a big job in a cleaner region can cut CO2e severalfold at no accuracy cost. Tools like CodeCarbon estimate CO2e so you can log it next to accuracy — turning an invisible externality into something optimizable.'],
        code: 'from codecarbon import EmissionsTracker\nimport mlflow\n\ntracker = EmissionsTracker(project_name=\'churn-train\')\ntracker.start()\ntry:\n    train_model()          # the expensive part\nfinally:\n    kg_co2 = tracker.stop()  # estimated emissions in kg CO2e\n\nmlflow.log_metric(\'co2e_kg\', kg_co2)\nprint(f\'run emitted ~{kg_co2:.3f} kg CO2e\')' }] },
  ]
});
