/* Deep dive — Natural Language Processing */
window.AtlasRef && window.AtlasRef.register('nlp', {
  color: '#A855F7',
  title: 'Teaching machines to read, write and understand',
  lead: 'Natural language processing turns messy human text into numbers a model can compute with, then turns numbers back into language. This is the full course: from cleaning and tokenizing raw text, through the vector representations (bag-of-words, TF-IDF, word2vec, contextual embeddings), to language models, decoding strategies, the classic tasks, and how we measure success — each with intuition, exact formulas, worked examples and code.',
  sections: [

    { h: 'What NLP is — and why language is hard', p: [
      '<b>Natural Language Processing (NLP)</b> is the field that lets computers work with human language: reading it, understanding structure and meaning, and generating it. Unlike numbers, language is <b>discrete, symbolic and wildly ambiguous</b> — the same string can mean different things, and different strings can mean the same thing.',
      'Three difficulties recur everywhere. <b>Ambiguity</b>: “I saw her duck” could mean a bird or a dodge. <b>Context dependence</b>: “bank” means a riverside or a financial institution depending on neighbours. <b>Compositionality and world knowledge</b>: “the trophy did not fit in the suitcase because it was too big” — <i>it</i> refers to the trophy, and you only know that from physics, not grammar.',
      'The core NLP pipeline is therefore: <b>text → tokens → vectors → model → prediction → text</b>. Almost every technique below is a way of doing one of those arrows well.'],
      terms: [['Lexical ambiguity', 'one word, many senses (bank, bat, lead).'], ['Syntactic ambiguity', 'one sentence, many parse trees (“visiting relatives can be boring”).'], ['Coreference', 'figuring out what pronouns refer to.'], ['Pragmatics', 'meaning that depends on speaker intent and situation, not just words.']],
      note: 'For how modern models actually read context with self-attention, see the <b>Transformers</b> module — this page covers everything up to and around it.' },

    { h: 'Text preprocessing: cleaning before modelling', p: [
      'Raw text is noisy: mixed case, punctuation, HTML, accents, whitespace. <b>Preprocessing</b> normalises it so that surface variations do not fragment your vocabulary. <b>Normalization</b> covers Unicode normalization, stripping accents, and collapsing whitespace. <b>Lowercasing</b> maps “The” and “the” to one token — useful for bag-of-words, but sometimes harmful (it erases “US” the country vs “us” the pronoun, and “Apple” the company vs “apple” the fruit).',
      '<b>Stop words</b> are ultra-frequent function words (the, is, of, a) that carry little topical signal; removing them shrinks the vocabulary for classic models. <b>Stemming</b> chops words to a crude root with rules (Porter stemmer): “running”, “runs”, “ran” → “run”, but “studies” → “studi” (not a real word). <b>Lemmatization</b> uses a dictionary and part-of-speech to return the true base form (the <i>lemma</i>): “studies” → “study”, “better” → “good”. Lemmatization is slower but linguistically correct.'],
      table: { cols: ['Step', 'What it does', 'Trade-off'], rows: [
        ['Lowercasing', 'the/The → the', 'loses proper-noun / acronym distinctions'],
        ['Stop-word removal', 'drop the, is, of…', 'great for BoW, harmful for meaning/negation'],
        ['<b>Stemming</b>', 'rule-chop to a stem (Porter)', 'fast, but stems can be non-words (studi)'],
        ['<b>Lemmatization</b>', 'dictionary base form + POS', 'accurate lemma (study, good), but slower'],
        ['Normalization', 'Unicode, accents, whitespace', 'must be consistent train vs inference']] },
      ex: [{ h: 'Stemming vs lemmatization on the same words', p: ['Notice how the stemmer produces the non-word “studi”, while the lemmatizer returns the real dictionary form “study”. For “better”, only the lemmatizer (told it is an adjective) recovers “good”.'],
        code: 'from nltk.stem import PorterStemmer, WordNetLemmatizer\nps, wnl = PorterStemmer(), WordNetLemmatizer()\n\nfor w in [\'studies\', \'running\', \'better\']:\n    print(w, ps.stem(w), wnl.lemmatize(w, pos=\'v\'))\n# studies  studi   study\n# running  run     run\n# better   better  good   (lemmatize with pos=\'a\')' }],
      note: 'Modern transformer pipelines do far less of this: subword tokenizers handle morphology, and lowercasing / stop-word removal are usually skipped because the model learns what to ignore.' },

    { h: 'Tokenization: word, character & subword', p: [
      '<b>Tokenization</b> splits text into the units a model consumes. Three granularities exist. <b>Word tokens</b> are intuitive but produce huge vocabularies and choke on unseen words (every typo or rare name is <code>&lt;UNK&gt;</code>). <b>Character tokens</b> have a tiny vocabulary and never hit unknown words, but sequences get very long and each unit carries little meaning.',
      '<b>Subword tokenization</b> is the modern compromise used by essentially every LLM: common words stay whole, rare words split into meaningful pieces. This bounds the vocabulary (~30k–100k) while still representing <i>any</i> string. The two dominant algorithms are <b>Byte-Pair Encoding (BPE)</b> and <b>WordPiece</b>.'],
      terms: [['Vocabulary', 'the fixed set of tokens the model knows.'], ['<code>&lt;UNK&gt;</code>', 'the fallback token for anything out-of-vocabulary.'], ['Special tokens', '<code>[CLS]</code>, <code>[SEP]</code>, <code>&lt;/s&gt;</code>, padding — structural markers.'], ['Token ≠ word', 'on average ~1.3 tokens per English word for GPT-style BPE.']],
      note: 'Token count is what you pay for and what fills the context window — “tokens”, not words, is the unit of LLM cost and length.' },

    { h: 'BPE & WordPiece: splitting a rare word', p: [
      '<b>Byte-Pair Encoding (BPE)</b> is trained by starting from characters and <b>greedily merging the most frequent adjacent pair</b> over and over, each merge becoming a new token. After thousands of merges, frequent chunks (“ing”, “tion”, whole common words) exist as single tokens, while rare words remain splittable into those chunks. Encoding a new word applies the learned merges in order.',
      '<b>WordPiece</b> (used by BERT) is similar but chooses each merge to <b>maximise the likelihood of the training corpus</b> rather than raw frequency, and marks word-internal continuation pieces with <code>##</code>. Both guarantee no <code>&lt;UNK&gt;</code>: worst case, a word falls back to individual characters.'],
      eqn: 'BPE merge rule:  pick argmax over pairs of  count(a, b)\nWordPiece merge rule:  pick argmax of  count(a,b) / ( count(a) * count(b) )',
      ex: [{ h: 'Tokenizing the rare word “unhappiness”', p: ['A word-level model that never saw “unhappiness” emits <code>&lt;UNK&gt;</code> and loses all meaning. A subword model splits it into known pieces it <i>has</i> seen — the negation prefix, the root, and the noun suffix — so the model can still compose the meaning. BPE (GPT-style) and WordPiece (BERT-style) mark the split differently:'],
        eqn: 'word-level:   unhappiness            -> [<UNK>]                 (meaning lost)\nBPE (GPT):    unhappiness            -> [\'un\', \'happ\', \'iness\']\nWordPiece:    unhappiness            -> [\'un\', \'##happi\', \'##ness\']  (## = continues a word)',
        code: 'from tokenizers import Tokenizer, models, trainers, pre_tokenizers\ntok = Tokenizer(models.BPE(unk_token=\'[UNK]\'))\ntok.pre_tokenizer = pre_tokenizers.Whitespace()\ntrainer = trainers.BpeTrainer(vocab_size=5000, special_tokens=[\'[UNK]\'])\ntok.train_from_iterator(corpus, trainer)   # corpus: iterable of strings\nprint(tok.encode(\'unhappiness\').tokens)    # e.g. [\'un\', \'happ\', \'iness\']' }],
      note: 'GPT models use byte-level BPE, so the true alphabet is 256 bytes — meaning literally any Unicode string, emoji included, is representable with zero unknown tokens.' },

    { h: 'Bag-of-words: text as a count vector', p: [
      'The <b>bag-of-words (BoW)</b> model represents a document as a vector of word counts, <b>ignoring order entirely</b> — “dog bites man” and “man bites dog” get the identical vector. You fix a vocabulary of size V, and each document becomes a length-V vector whose i-th entry is how many times word i appeared. Most entries are zero, so these are <b>sparse</b> vectors.',
      'BoW is crude but a shockingly strong baseline for topic and sentiment classification, because word <i>presence</i> already carries a lot of signal. Its weaknesses: it loses order and syntax, treats every word as unrelated (no notion that “great” ≈ “excellent”), and over-weights common words — which TF-IDF fixes next.'],
      ex: [{ h: 'Two tiny documents to vectors', p: ['Vocabulary = {cat, sat, on, mat, dog}. “the cat sat on the mat” and “the dog sat” become count vectors over that shared vocabulary. Distance/similarity between documents is then just vector arithmetic.'],
        eqn: 'vocab:  [cat, sat, on, mat, dog]\nd1 = "cat sat on the mat"  -> [1, 1, 1, 1, 0]\nd2 = "dog sat"             -> [0, 1, 0, 0, 1]',
        code: 'from sklearn.feature_extraction.text import CountVectorizer\ndocs = [\'the cat sat on the mat\', \'the dog sat\']\ncv = CountVectorizer()\nX = cv.fit_transform(docs)\nprint(cv.get_feature_names_out())  # [\'cat\' \'dog\' \'mat\' \'on\' \'sat\' \'the\']\nprint(X.toarray())\n# [[1 0 1 1 1 2]\n#  [0 1 0 0 1 1]]' }] },

    { h: 'TF-IDF: weighting words by informativeness', p: [
      '<b>TF-IDF (Term Frequency–Inverse Document Frequency)</b> improves bag-of-words by down-weighting words that appear in <i>every</i> document (like “the”) and up-weighting words that are rare across the corpus but frequent in <i>this</i> document — those are the discriminative ones. It is the product of two factors:',
      '<b>Term frequency</b> tf(t,d) is how often term t occurs in document d (often normalised). <b>Inverse document frequency</b> idf(t) is a log of how rare t is across the N documents. A word that appears in all documents has idf ≈ 0 and is effectively cancelled; a word in just a few documents gets a large idf.'],
      eqn: 'tf(t,d)  = count of t in d  (optionally / |d|)\nidf(t)   = log( N / df(t) )        # df(t) = number of docs containing t\ntfidf(t,d) = tf(t,d) * idf(t)\n\n# sklearn smoothed variant:  idf(t) = log( (1+N)/(1+df(t)) ) + 1',
      ex: [{ h: 'Worked numeric example', p: ['Corpus of N = 3 documents. The word <b>“cat”</b> appears in 1 document; the word <b>“the”</b> appears in all 3. Compute the idf for each (natural log), then the TF-IDF weight of “cat” in a document where it occurs twice.'],
        eqn: 'N = 3\ndf(the) = 3  ->  idf(the) = ln(3/3) = ln(1)   = 0.000\ndf(cat) = 1  ->  idf(cat) = ln(3/1) = ln(3)   = 1.099\n\ntf(cat, d) = 2\ntfidf(cat, d) = 2 * 1.099 = 2.197\ntfidf(the, d) = tf * 0    = 0.000   # "the" contributes nothing',
        code: 'from sklearn.feature_extraction.text import TfidfVectorizer\ndocs = [\'the cat sat\', \'the dog ran\', \'the bird flew\']\ntv = TfidfVectorizer()\nX = tv.fit_transform(docs)\nvocab = tv.get_feature_names_out()\nweights = dict(zip(vocab, tv.idf_))\nprint(round(weights[\'the\'], 2))  # ~1.0  (in every doc -> smallest idf)\nprint(round(weights[\'cat\'], 2))  # ~1.69 (rare -> largest idf)' }],
      note: 'TF-IDF vectors + a linear classifier (logistic regression / linear SVM) remain a strong, cheap, interpretable baseline that new deep models must justify beating.' },

    { h: 'N-grams: putting a little order back', p: [
      'Pure bag-of-words throws away word order, which loses meaning — “not good” becomes just {not, good}. <b>N-grams</b> recover local order by treating contiguous runs of n tokens as single features. A <b>unigram</b> is one word, a <b>bigram</b> two adjacent words, a <b>trigram</b> three. Adding bigrams lets a model see “not good” and “New York” as units.',
      'The cost is <b>explosion</b>: the number of possible n-grams grows roughly like V<sup>n</sup>, making vectors huge and sparse, and most higher n-grams are never seen (data sparsity). In practice people use unigrams + bigrams (sometimes trigrams) and stop there. N-grams also underpin classic <b>count-based language models</b> (next section).'],
      ex: [{ h: 'Extracting n-grams and why they matter', p: ['The sentence “the movie was not good” has the unigram “good” (positive-looking) but the bigram “not good” (clearly negative). A bigram model captures the negation a unigram BoW model misses.'],
        eqn: 'sentence: "the movie was not good"\nunigrams: the, movie, was, not, good\nbigrams : the movie, movie was, was not, not good',
        code: 'from sklearn.feature_extraction.text import CountVectorizer\ncv = CountVectorizer(ngram_range=(1, 2))   # unigrams + bigrams\nX = cv.fit_transform([\'the movie was not good\'])\nprint([f for f in cv.get_feature_names_out() if \'not\' in f])\n# [\'not\', \'not good\', \'was not\']' }] },

    { h: 'Word embeddings: word2vec & GloVe', p: [
      'Bag-of-words and TF-IDF treat words as isolated symbols: “king” and “queen” are as unrelated as “king” and “banana”. <b>Word embeddings</b> instead map each word to a dense vector (~50–300 dims) so that <b>semantically similar words sit close together</b>. They are learned from the <b>distributional hypothesis</b>: words appearing in similar contexts have similar meanings.',
      '<b>word2vec</b> comes in two flavours. <b>Skip-gram</b> predicts the surrounding context words from a centre word (great for rare words); <b>CBOW</b> (Continuous Bag-of-Words) predicts the centre word from its context (faster). <b>GloVe</b> instead factorises a global word-word co-occurrence count matrix so that the dot product of two word vectors approximates the log of how often they co-occur.',
      'The famous result: embeddings encode analogies as <b>linear directions</b>. The vector from “man” to “woman” is roughly the same as “king” to “queen”, so <b>king − man + woman ≈ queen</b>.'],
      eqn: 'Skip-gram objective:  maximise  Σ  log P(context word | centre word)\nGloVe objective:      w_i · w_j + b_i + b_j  ≈  log( X_ij )   # X_ij = co-occurrence count\nAnalogy:              vec(king) - vec(man) + vec(woman) ≈ vec(queen)',
      ex: [{ h: 'Solving the king − man + woman analogy', p: ['Take the pretrained vector for “king”, subtract “man”, add “woman”, then find the nearest known word by cosine similarity. The answer is “queen”. This works because gender is encoded as a consistent direction across many word pairs.'],
        code: 'import gensim.downloader as api\nwv = api.load(\'glove-wiki-gigaword-100\')   # pretrained GloVe\nprint(wv.most_similar(positive=[\'king\', \'woman\'],\n                      negative=[\'man\'], topn=1))\n# [(\'queen\', 0.77)]\nprint(round(wv.similarity(\'cat\', \'dog\'), 2))   # ~0.66  (related)\nprint(round(wv.similarity(\'cat\', \'car\'), 2))   # ~0.30  (unrelated)' }],
      terms: [['Dense vector', 'few dimensions, all non-zero — opposite of sparse BoW.'], ['Distributional hypothesis', '“you shall know a word by the company it keeps.”'], ['Negative sampling', 'word2vec trick: contrast real context words against random ones.'], ['Analogy arithmetic', 'relations become vector offsets you can add and subtract.']] },

    { h: 'Static vs contextual embeddings (ELMo, BERT)', p: [
      'word2vec and GloVe are <b>static</b>: “bank” has one vector no matter the sentence, so “river bank” and “savings bank” collapse to the same point. That is a fundamental limit — polysemy cannot be represented by a single vector.',
      '<b>Contextual embeddings</b> fix this: the vector for a word is computed <i>from its whole sentence</i>, so “bank” gets different vectors in different contexts. <b>ELMo</b> (2018) did this with stacked bidirectional LSTMs. <b>BERT</b> (2018) did it with a Transformer trained on <b>masked language modelling</b> (predict hidden words from both sides), producing deep bidirectional representations that dramatically improved nearly every NLP task and kicked off the pretrain-then-fine-tune era.'],
      table: { cols: ['Property', 'Static (word2vec/GloVe)', 'Contextual (ELMo/BERT)'], rows: [
        ['One vector per…', 'word type', 'word occurrence (per sentence)'],
        ['Handles polysemy', 'no — “bank” fixed', 'yes — “bank” varies by context'],
        ['Architecture', 'shallow, table lookup', 'deep LSTM / Transformer'],
        ['Direction', 'context ignored at use time', 'ELMo bi-LSTM, BERT bidirectional attention'],
        ['Typical use', 'features / init', 'fine-tune or extract per-token states']] },
      ex: [{ h: 'Same word, different vectors', p: ['With a contextual model, encode two sentences using “bank” in different senses and compare the token vectors — they are far apart, whereas a static model would give them identical vectors. Conceptually:'],
        eqn: 'static:      vec("bank" | river bank)  ==  vec("bank" | savings bank)\ncontextual:  vec("bank" | river bank)  !=  vec("bank" | savings bank)\n             cosine(river-bank, savings-bank)  ~ 0.4   (clearly different)',
        code: 'from transformers import AutoTokenizer, AutoModel\nimport torch\ntok = AutoTokenizer.from_pretrained(\'bert-base-uncased\')\nmodel = AutoModel.from_pretrained(\'bert-base-uncased\')\n\ndef embed(sentence):\n    ids = tok(sentence, return_tensors=\'pt\')\n    return model(**ids).last_hidden_state[0]   # per-token contextual vectors\n# vectors for "bank" differ between "river bank" and "savings bank"' }],
      note: 'BERT-style bidirectional context is powered by self-attention — the mechanism explained end-to-end in the <b>Transformers</b> module.' },

    { h: 'Measuring similarity with cosine', p: [
      'Once text is a vector — TF-IDF, word2vec, or a sentence embedding — comparing meaning becomes comparing vectors. The standard measure is <b>cosine similarity</b>: the cosine of the angle between two vectors, which ignores their magnitude and captures only <b>direction</b>. This is why a long and a short document about the same topic still score as similar.',
      'Cosine ranges from −1 (opposite) through 0 (unrelated / orthogonal) to 1 (identical direction). It is preferred over raw Euclidean distance for text because document/word vectors vary a lot in length, and we care about <i>what</i> they are about, not how many words they contain.'],
      eqn: 'cosine_sim(a, b) = (a · b) / ( ||a|| * ||b|| ) = Σ aᵢbᵢ / ( √Σaᵢ² · √Σbᵢ² )',
      ex: [{ h: 'Cosine similarity from scratch in numpy', p: ['Compute cosine between two small vectors. The second is a scaled copy of the first, so despite different magnitudes the cosine is 1.0 — exactly what we want when comparing texts of different lengths.'],
        code: 'import numpy as np\n\ndef cosine(a, b):\n    return (a @ b) / (np.linalg.norm(a) * np.linalg.norm(b))\n\nq  = np.array([1., 0., 1., 0.])        # query BoW/TF-IDF vector\nd1 = np.array([2., 0., 2., 0.])        # same topic, twice the length\nd2 = np.array([0., 1., 0., 1.])        # disjoint words\nprint(round(cosine(q, d1), 2))   # 1.0  (identical direction)\nprint(round(cosine(q, d2), 2))   # 0.0  (nothing in common)' }],
      note: 'Semantic search and RAG retrieval (last section) are, at heart, nearest-neighbour search by cosine similarity over an index of embedding vectors.' },

    { h: 'Language models & next-word prediction', p: [
      'A <b>language model (LM)</b> assigns probabilities to sequences of tokens. The dominant form is the <b>autoregressive</b> model, which factorises the probability of a sentence into a product of next-token predictions: predict token t given all tokens before it. Training maximises the probability of real text, i.e. minimises cross-entropy — the model becomes very good at “what word comes next”.',
      'Classic n-gram LMs estimated P(next | previous n−1 words) from counts, but suffered from sparsity and a tiny context. Neural LMs (RNNs, then Transformers) learn distributed representations and long-range context, which is why today’s LLMs can stay coherent over thousands of tokens. Everything a generative LLM does — chat, code, summarise — is repeated next-token prediction.'],
      eqn: 'P(w₁ … w_T) = Π P(w_t | w₁ … w_{t-1})        # autoregressive factorisation\nn-gram approx:  P(w_t | w₁…w_{t-1}) ≈ P(w_t | w_{t-n+1}…w_{t-1})',
      ex: [{ h: 'The model outputs a distribution, not a word', p: ['Given “The cat sat on the”, the model produces a probability over the <i>entire</i> vocabulary. Decoding (next section) chooses an actual token from that distribution. A logit vector becomes probabilities via softmax.'],
        eqn: 'context: "The cat sat on the ___"\nP(mat)  = 0.41\nP(floor)= 0.22\nP(sofa) = 0.15\nP(roof) = 0.06\n...        (sums to 1 over the whole vocabulary)',
        code: 'import torch, torch.nn.functional as F\nlogits = torch.tensor([3.2, 2.1, 1.7, 0.4])   # model output over 4 tokens\nprobs  = F.softmax(logits, dim=-1)\nprint([round(float(p), 2) for p in probs])    # [0.6, 0.2, 0.13, 0.06]' }] },

    { h: 'Decoding: greedy, beam, temperature, top-k, top-p', p: [
      'A language model gives a probability distribution over the next token; <b>decoding</b> is the strategy for turning that into text. <b>Greedy</b> always takes the single highest-probability token — fast but repetitive and often bland. <b>Beam search</b> keeps the k most probable <i>partial sequences</i> at each step and expands them, finding higher-probability whole sentences — good for translation, but tends toward safe, generic text.',
      'For open-ended generation we add controlled randomness. <b>Temperature</b> T rescales the logits before softmax: T&lt;1 sharpens (more deterministic), T&gt;1 flattens (more random), T→0 becomes greedy. <b>Top-k</b> samples only from the k most likely tokens. <b>Nucleus / top-p</b> sampling keeps the smallest set of tokens whose cumulative probability exceeds p (e.g. 0.9) and samples from those — adapting the candidate set to how confident the model is.'],
      eqn: 'softmax with temperature:  P(i) = exp(zᵢ / T) / Σⱼ exp(zⱼ / T)\ntop-k:      restrict to the k tokens with the largest zᵢ, then renormalise\ntop-p:      smallest set V_p with  Σ_{i∈V_p} P(i) ≥ p,  then renormalise',
      table: { cols: ['Method', 'How it picks', 'Good for'], rows: [
        ['<b>Greedy</b>', 'argmax every step', 'short factual answers; can loop'],
        ['<b>Beam search</b>', 'keep k best full sequences', 'translation, summarization'],
        ['<b>Temperature</b>', 'scale randomness of softmax', 'global creativity dial'],
        ['<b>Top-k</b>', 'sample from k likeliest', 'cap the tail, fixed budget'],
        ['<b>Top-p (nucleus)</b>', 'sample from smallest mass ≥ p', 'adaptive, quality open-ended text']] },
      ex: [{ h: 'How temperature reshapes a distribution', p: ['Take fixed logits and apply softmax at low, neutral, and high temperature. Low T concentrates mass on the top token (near-greedy); high T spreads it out (more diverse, riskier). Top-k / top-p then trim which tokens are even eligible.'],
        code: 'import numpy as np\ndef softmax_T(z, T):\n    z = np.array(z) / T\n    e = np.exp(z - z.max())\n    return e / e.sum()\n\nz = [2.0, 1.0, 0.1]\nprint(np.round(softmax_T(z, 0.5), 2))  # [0.85 0.11 0.02] sharp (near greedy)\nprint(np.round(softmax_T(z, 1.0), 2))  # [0.66 0.24 0.10] baseline\nprint(np.round(softmax_T(z, 2.0), 2))  # [0.5  0.3  0.2 ] flat (more random)' }],
      note: 'Typical chat defaults combine them: temperature ≈ 0.7 with top-p ≈ 0.9. For deterministic tasks (extraction, code), set temperature near 0.' },

    { h: 'The classic NLP tasks', p: [
      'Most practical NLP reduces to a handful of task shapes. <b>Text classification</b> assigns a label to a whole document — the flagship example being <b>sentiment analysis</b> (positive/negative/neutral). <b>Sequence labelling</b> tags each token: <b>Named Entity Recognition (NER)</b> marks people/places/organisations, and <b>Part-of-Speech (POS) tagging</b> marks noun/verb/adjective. <b>Parsing</b> recovers grammatical structure (a dependency or constituency tree).',
      'The generative tasks map text to text: <b>summarization</b> (long → short), <b>machine translation</b> (one language → another), and <b>question answering (QA)</b> (question + context → answer, either extracted as a span or generated). Modern LLMs handle all of these with the same underlying next-token engine, often via a prompt instead of a task-specific model.'],
      table: { cols: ['Task', 'Input → Output', 'Example'], rows: [
        ['Classification / Sentiment', 'document → label', '“loved it!” → positive'],
        ['NER', 'tokens → entity tags', '“Apple in Paris” → ORG, LOC'],
        ['POS tagging', 'tokens → grammar tags', '“run” → VERB or NOUN'],
        ['Parsing', 'sentence → tree', 'subject–verb–object structure'],
        ['Summarization', 'long text → short text', 'article → 3 sentences'],
        ['Translation', 'text (L1) → text (L2)', 'English → French'],
        ['Question answering', 'question + context → answer', 'SQuAD-style span extraction']] },
      ex: [{ h: 'Sentiment classification with TF-IDF + logistic regression', p: ['A complete, strong baseline: vectorise text with TF-IDF, fit a linear classifier. This still beats many heavier models on small datasets and is fully interpretable (you can read off which words push positive vs negative).'],
        code: 'from sklearn.feature_extraction.text import TfidfVectorizer\nfrom sklearn.linear_model import LogisticRegression\nfrom sklearn.pipeline import make_pipeline\n\nX = [\'i loved this movie\', \'awful and boring\', \'best film ever\', \'a total waste\']\ny = [1, 0, 1, 0]                        # 1 = positive, 0 = negative\nclf = make_pipeline(TfidfVectorizer(), LogisticRegression())\nclf.fit(X, y)\nprint(clf.predict([\'a wonderful film\']))   # -> [1]  (positive)' }] },

    { h: 'Sequence-to-sequence & encoder–decoder', p: [
      'Many tasks map an input sequence to an <i>output sequence of different length</i> — translation, summarization, QA. The <b>sequence-to-sequence (seq2seq)</b> framework solves this with two parts. The <b>encoder</b> reads the entire input and compresses it into a context representation; the <b>decoder</b> generates the output token by token, conditioned on that representation and on what it has produced so far.',
      'Early seq2seq used RNNs and squeezed the whole input into a single fixed vector — a bottleneck that hurt long inputs. <b>Attention</b> removed the bottleneck by letting the decoder look back at <i>all</i> encoder states and focus on the relevant ones at each step. The Transformer took this to its conclusion (attention only, no recurrence). Note the split: encoder-only models (BERT) excel at understanding, decoder-only models (GPT) at generation, encoder–decoder models (T5, translation) at input→output rewriting.'],
      eqn: 'encoder:  h = Encoder(x₁ … x_n)                     # read the source\ndecoder:  y_t = Decoder(y₁ … y_{t-1}, h)            # emit target, one token at a time\nattention: contextᵗ = Σᵢ αᵢᵗ hᵢ ,  αᵗ = softmax(scores over encoder states)',
      ex: [{ h: 'Translation as encode-then-decode', p: ['To translate “I am happy” → “Je suis heureux”, the encoder builds a representation of the English sentence, then the decoder emits French tokens one at a time, attending to the relevant source words. Special <code>&lt;s&gt;</code>/<code>&lt;/s&gt;</code> tokens mark start and end of generation.'],
        eqn: 'source:  [<s>] I  am  happy  [</s>]\n            |  encoder builds context h\n            v\ntarget:  [<s>] -> Je -> suis -> heureux -> [</s>]   (decoder, autoregressive)',
        code: 'from transformers import pipeline\ntranslate = pipeline(\'translation_en_to_fr\')   # a seq2seq (encoder-decoder) model\nprint(translate(\'I am happy\')[0][\'translation_text\'])\n# -> \'Je suis heureux\'' }],
      note: 'The attention mechanism named here is the heart of the Transformer — see the <b>Transformers</b> module for the full query/key/value derivation.' },

    { h: 'Evaluation metrics: F1, BLEU, ROUGE, perplexity', p: [
      'Different tasks need different yardsticks. For <b>classification</b>, plain <b>accuracy</b> misleads on imbalanced data (99% “not spam” gets 99% by always guessing “not spam”), so we use <b>precision</b> (of predicted positives, how many were right), <b>recall</b> (of true positives, how many we caught), and their harmonic mean, the <b>F1 score</b>.',
      'For <b>generation</b> there is no single right answer, so we compare against references. <b>BLEU</b> (translation) measures n-gram <i>precision</i> of the output against reference translations, with a brevity penalty for being too short. <b>ROUGE</b> (summarization) measures n-gram <i>recall</i> — how much of the reference’s content the summary covered. For <b>language models</b>, <b>perplexity</b> measures how “surprised” the model is by real text — the exponential of the average cross-entropy; lower is better, and it equals the effective number of equally-likely choices the model is deciding among per token.'],
      eqn: 'precision = TP / (TP + FP)     recall = TP / (TP + FN)\nF1 = 2 · precision · recall / (precision + recall)\nBLEU = BP · exp( Σ wₙ log pₙ )        # pₙ = n-gram precision, BP = brevity penalty\nperplexity = exp( − (1/N) Σ log P(w_t | w_<t) ) = 2^(cross-entropy in bits)',
      table: { cols: ['Metric', 'Task', 'Measures'], rows: [
        ['Accuracy', 'balanced classification', 'fraction correct (misleads if imbalanced)'],
        ['<b>F1</b>', 'classification, NER', 'balance of precision & recall'],
        ['<b>BLEU</b>', 'translation', 'n-gram precision vs references (+brevity)'],
        ['<b>ROUGE</b>', 'summarization', 'n-gram recall vs reference summary'],
        ['<b>Perplexity</b>', 'language modelling', 'avg surprise; lower = better predictor']] },
      ex: [{ h: 'Computing precision, recall, F1', p: ['Suppose a spam filter flags 8 emails as spam; 6 are truly spam (TP), 2 are not (FP), and it missed 4 real spam (FN). Precision and recall pull in opposite directions, and F1 summarises the trade-off in one number.'],
        eqn: 'TP=6, FP=2, FN=4\nprecision = 6/(6+2) = 0.75\nrecall    = 6/(6+4) = 0.60\nF1 = 2·0.75·0.60/(0.75+0.60) = 0.667',
        code: 'from sklearn.metrics import precision_score, recall_score, f1_score\ny_true = [1,1,1,1,1,1,1,1,1,1, 0,0]   # 10 real spam, 2 ham\ny_pred = [1,1,1,1,1,1,0,0,0,0, 1,1]   # 6 caught, 4 missed, 2 false alarms\nprint(round(precision_score(y_true, y_pred), 3))  # 0.75\nprint(round(recall_score(y_true, y_pred), 3))     # 0.6\nprint(round(f1_score(y_true, y_pred), 3))         # 0.667' }],
      note: 'Automatic generation metrics correlate only loosely with human judgement — BLEU/ROUGE reward word overlap, not meaning, so paraphrases score poorly. Human eval and model-based scoring remain important.' },

    { h: 'Retrieval-Augmented Generation (RAG)', p: [
      'A language model only knows what was in its training data, frozen at training time — so it cannot cite your private documents and will <b>hallucinate</b> facts it never saw. <b>Retrieval-Augmented Generation (RAG)</b> fixes this by combining <b>retrieval</b> (search) with <b>generation</b>: before answering, fetch relevant documents and feed them into the prompt as context, so the model answers <i>from</i> real, up-to-date, attributable sources.',
      'The pipeline: (1) <b>index</b> — split your documents into chunks, embed each into a vector, store them in a vector database; (2) <b>retrieve</b> — embed the user’s question and pull the top-k most similar chunks by cosine similarity; (3) <b>generate</b> — put those chunks plus the question into the LLM’s prompt and let it compose a grounded answer. This is why RAG ties together everything on this page: embeddings, cosine similarity, and a language model.'],
      eqn: 'index:     chunkᵢ  ->  vᵢ = embed(chunkᵢ)          # stored in a vector DB\nretrieve:  q = embed(question);  top-k by cosine_sim(q, vᵢ)\ngenerate:  answer = LLM( prompt = question + retrieved chunks )',
      ex: [{ h: 'A minimal RAG retrieval step', p: ['The retrieval half of RAG is just embedding + cosine nearest-neighbour. Embed a small knowledge base and a question, then pick the most similar chunk to hand to the LLM. In production the loop over documents is replaced by a vector index (FAISS, pgvector, etc.) for speed.'],
        code: 'import numpy as np\nfrom sentence_transformers import SentenceTransformer\nenc = SentenceTransformer(\'all-MiniLM-L6-v2\')\n\ndocs = [\'The Eiffel Tower is in Paris.\',\n        \'Python is a programming language.\',\n        \'Mount Everest is the tallest mountain.\']\nD = enc.encode(docs, normalize_embeddings=True)\nq = enc.encode(\'Where is the Eiffel Tower?\', normalize_embeddings=True)\n\nsims = D @ q                       # cosine (vectors are normalized)\ntop = int(np.argmax(sims))\nprint(docs[top])                   # -> \'The Eiffel Tower is in Paris.\'\n# this retrieved chunk is then inserted into the LLM prompt' }],
      note: 'RAG reduces hallucination and lets a model use fresh or private data without retraining — but answer quality is capped by retrieval quality: if the right chunk is not retrieved, the model cannot use it.' },
  ]
});
