/* Deep dive — Programming & tooling for AI */
window.AtlasRef && window.AtlasRef.register('programming', {
  color: '#F59E0B',
  title: 'The programming stack that ships AI',
  lead: 'Models are only as good as the code and infrastructure around them. This is the practitioner\'s toolchain: Python and its scientific stack, the deep-learning frameworks, the data stores, and the environment, versioning and performance discipline that turns a notebook into a system.',
  sections: [

    { h: 'Why Python dominates machine learning', p: [
      'Python won not because it is fast — it is one of the <b>slowest</b> mainstream languages — but because the heavy lifting happens in compiled code underneath. NumPy, PyTorch and TensorFlow are thin Python layers over hand-optimised <b>C, C++, Fortran and CUDA</b> kernels. You get the readability of Python and the speed of C, as long as the hot loop lives inside a library call rather than in a Python <code>for</code> loop.',
      'The second reason is <b>gravity</b>: the entire research and data ecosystem — Jupyter, NumPy, Pandas, scikit-learn, Hugging Face, every paper\'s reference implementation — is written in Python. Network effects compound. A new model ships as a <code>pip install</code> away, and glue code is trivial to write.',
      'Python is a <b>glue language</b>: dynamically typed, interpreted, with first-class functions and a REPL that makes exploration cheap. That is exactly the shape of data work — iterate fast, inspect often, then hand the number-crunching to a fast backend.'],
      terms: [['CPython', 'the reference interpreter; the GIL serialises Python bytecode across threads.'], ['GIL', 'Global Interpreter Lock — why CPU-bound Python uses processes, not threads.'], ['Vectorization', 'pushing loops down into C so Python overhead is paid once, not per element.'], ['Ecosystem lock-in', 'the practical reason: every model and dataset lands in Python first.']],
      note: 'The rule of thumb: Python for orchestration and glue, compiled kernels for the arithmetic. When your loop is in Python, you are leaving 10-100x on the table.' },

    { h: 'Core Python for data: comprehensions, generators, typing', p: [
      'Three language features do most of the day-to-day work. <b>Comprehensions</b> build lists, dicts and sets in one expressive line and are faster than an equivalent <code>append</code> loop. <b>Generators</b> produce values lazily, one at a time, so you can stream a 100 GB file through constant memory. <b>Type hints</b> document intent and let tools like <code>mypy</code> and your editor catch bugs before runtime.',
      'None of these change what the program computes — they change how <i>readable, memory-safe and maintainable</i> it is. In a codebase that others (or future you) will extend, that is the difference between a script and software.'],
      terms: [['List comp', '<code>[f(x) for x in xs if p(x)]</code> — build and filter in one pass.'], ['Generator', 'lazy iterator; <code>yield</code> or <code>(x for x in xs)</code>; memory is O(1).'], ['Type hint', '<code>def f(x: int) -> str</code>; checked by tooling, ignored at runtime.'], ['Dataclass', 'boilerplate-free typed record with <code>@dataclass</code>.']],
      ex: [{ h: 'Comprehensions, a streaming generator, and typed code', p: ['The comprehension transforms and filters in one line. The generator reads a huge file lazily — memory stays flat regardless of file size. The dataclass gives a typed, self-documenting record.'],
        code: 'from dataclasses import dataclass\nfrom typing import Iterator\n\n# comprehension: transform + filter in one pass\nsquares = [x * x for x in range(10) if x % 2 == 0]   # [0, 4, 16, 36, 64]\nlabels = {name: i for i, name in enumerate(["cat", "dog", "bird"])}\n\n# generator: stream a huge file through constant memory\ndef read_lengths(path: str) -> Iterator[int]:\n    with open(path) as f:\n        for line in f:            # lazy: one line at a time\n            yield len(line.rstrip())\n\ntotal = sum(read_lengths("huge.log"))  # never loads the file at once\n\n@dataclass\nclass Sample:\n    text: str\n    label: int\n    weight: float = 1.0' }] },

    { h: 'NumPy: ndarrays, vectorization and broadcasting', p: [
      'NumPy\'s <b>ndarray</b> is the foundation of the entire scientific stack — a contiguous block of memory with a shape and a dtype. Operations are <b>vectorized</b>: <code>a + b</code> runs a single C loop over the whole array instead of a Python loop over each element. This is the single most important performance idea in numerical Python.',
      '<b>Broadcasting</b> is NumPy\'s rule for combining arrays of different shapes without copying: dimensions are aligned from the right, and any axis of size 1 is stretched to match. It lets you subtract a per-column mean from a whole matrix, or add a bias vector to a batch, with no explicit loop.'],
      eqn: '(m, n) op (n,)  -> (m, n)      # row vector broadcasts down\n(m, 1) op (1, n) -> (m, n)      # outer-product-style stretch',
      ex: [{ h: 'Vectorization vs a Python loop — the speed gap', p: ['Both compute the same dot product. The loop pays Python\'s per-element interpreter cost; the vectorized call pays it once and runs C underneath. On a million-element array the vectorized version is typically <b>50-200x faster</b>.'],
        code: 'import numpy as np, time\na = np.random.rand(1_000_000)\nb = np.random.rand(1_000_000)\n\nt = time.perf_counter()\ns = 0.0\nfor x, y in zip(a, b):      # pure-Python loop\n    s += x * y\nprint("loop:      ", time.perf_counter() - t)   # ~0.15 s\n\nt = time.perf_counter()\ns = np.dot(a, b)            # vectorized: one C call\nprint("vectorized:", time.perf_counter() - t)   # ~0.001 s' },
        { h: 'Broadcasting away the loops', p: ['The mental model: align shapes from the right; a dimension is compatible if the sizes are equal or one of them is 1; a size-1 axis is virtually repeated. Column standardisation subtracts a shape-<code>(n_features,)</code> mean from a <code>(n_samples, n_features)</code> matrix — the mean broadcasts across rows. Pairwise distances use a <code>(n,1,d)</code> vs <code>(1,m,d)</code> broadcast to form every difference at once.'],
        code: 'X = np.random.randn(1000, 20)\n\n# standardise each column (mean broadcasts down the rows)\nXs = (X - X.mean(axis=0)) / X.std(axis=0)\n\n# all pairwise squared distances without a loop\nA = np.random.randn(50, 3)\nB = np.random.randn(80, 3)\ndiff = A[:, None, :] - B[None, :, :]     # (50, 80, 3)\ndist = np.sqrt((diff ** 2).sum(axis=-1)) # (50, 80)' }],
      note: 'Rule: if you write a Python for-loop over a NumPy array, ask whether a vectorized expression, broadcasting, or <code>np.einsum</code> can replace it. Almost always, yes.' },

    { h: 'Pandas & Polars: filter, groupby, merge, pivot', p: [
      'A <b>DataFrame</b> is a table with named, typed columns — the workhorse for tabular data. <b>Pandas</b> is the incumbent, universally known and documented. <b>Polars</b> is the fast challenger: written in Rust, multi-threaded, with a <b>lazy</b> query engine that optimises the whole pipeline before executing, and it handles larger-than-RAM data far better.',
      'The core verbs are the same everywhere: <b>filter</b> rows by a boolean mask, <b>groupby</b>-then-aggregate to summarise, <b>merge/join</b> to combine tables on a key, and <b>pivot</b> to reshape long data into wide. Master these four and you can wrangle almost any dataset.'],
      ex: [{ h: 'The four core verbs in Pandas', p: ['Filter, group-and-aggregate, join to another table, then pivot to a wide summary. This is 80% of real data-prep work.'],
        code: 'import pandas as pd\ndf = pd.read_csv("sales.csv")   # cols: region, product, month, revenue\n\n# 1. filter\nbig = df[df["revenue"] > 1000]\n\n# 2. groupby + aggregate\nby_region = df.groupby("region")["revenue"].agg(["sum", "mean", "count"])\n\n# 3. merge with a lookup table\ntargets = pd.read_csv("targets.csv")           # cols: region, target\njoined = df.merge(targets, on="region", how="left")\n\n# 4. pivot: months become columns\nwide = df.pivot_table(index="region", columns="month",\n                      values="revenue", aggfunc="sum", fill_value=0)' }],
      table: { cols: ['Aspect', 'Pandas', 'Polars'], rows: [
        ['Backend', 'C / Cython, single-threaded core', '<b>Rust</b>, multi-threaded'],
        ['Execution', 'eager (runs each step)', 'eager <i>or</i> <b>lazy</b> (whole-query optimised)'],
        ['Memory', 'often 2-5x data size', 'columnar Arrow, much leaner'],
        ['Larger-than-RAM', 'struggles', 'streaming engine handles it'],
        ['Ecosystem', 'huge, mature, everywhere', 'growing fast, Arrow-native']] },
      note: 'The same pipeline in Polars\' lazy API: <code>pl.scan_csv("sales.csv").filter(pl.col("revenue") &gt; 1000).group_by("region").agg(pl.col("revenue").sum()).collect()</code> — the engine reorders and fuses operations before touching data.' },

    { h: 'scikit-learn: the estimator API that everyone copied', p: [
      'scikit-learn\'s genius is a <b>consistent interface</b>. Every model is an <i>estimator</i> with <code>.fit(X, y)</code>. Predictors add <code>.predict(X)</code>; transformers add <code>.transform(X)</code> (and <code>.fit_transform</code>). Because every object speaks the same protocol, you can swap a <code>RandomForest</code> for a <code>LogisticRegression</code> by changing one line, and compose steps into a <b>Pipeline</b>.',
      'A <b>Pipeline</b> chains transformers and a final estimator so preprocessing is learned on the training fold only — this is how you avoid <b>data leakage</b> during cross-validation. A <b>ColumnTransformer</b> applies different preprocessing to different columns (scale the numbers, one-hot the categories) and slots into the same pipeline.'],
      eqn: 'estimator.fit(X, y)            # learn parameters\ntransformer.transform(X)       # produce new features\npredictor.predict(X)           # produce outputs',
      ex: [{ h: 'A leak-free Pipeline with ColumnTransformer', p: ['Numeric columns get imputed and scaled; categorical columns get one-hot encoded; the combined features feed a classifier. Because it is one Pipeline object, cross-validation refits every step per fold — no leakage.'],
        code: 'from sklearn.pipeline import Pipeline\nfrom sklearn.compose import ColumnTransformer\nfrom sklearn.preprocessing import StandardScaler, OneHotEncoder\nfrom sklearn.impute import SimpleImputer\nfrom sklearn.ensemble import RandomForestClassifier\nfrom sklearn.model_selection import cross_val_score\n\nnum = ["age", "income"]\ncat = ["city", "plan"]\n\npre = ColumnTransformer([\n    ("num", Pipeline([("imp", SimpleImputer(strategy="median")),\n                      ("sc", StandardScaler())]), num),\n    ("cat", OneHotEncoder(handle_unknown="ignore"), cat),\n])\n\nclf = Pipeline([\n    ("pre", pre),\n    ("model", RandomForestClassifier(n_estimators=300, random_state=0)),\n])\n\nscores = cross_val_score(clf, X, y, cv=5, scoring="roc_auc")\nprint(scores.mean())' }],
      note: 'The fit/transform/predict trinity is so successful that PyTorch pipelines, XGBoost and even parts of Hugging Face mimic it. Learn it once, reuse it everywhere.' },

    { h: 'Deep-learning frameworks: PyTorch vs TensorFlow/Keras vs JAX', p: [
      'Three families dominate. <b>PyTorch</b> is the research and default-production standard: eager, Pythonic, define-by-run, with an autograd engine that records operations into a graph as they execute. <b>TensorFlow/Keras</b> pairs a high-level model API (Keras) with a mature production and mobile/edge deployment story. <b>JAX/Flax</b> is the functional newcomer: NumPy-compatible, with composable transforms — <code>grad</code>, <code>jit</code>, <code>vmap</code>, <code>pmap</code> — that give razor-sharp control and TPU-scale performance.',
      'All three rest on <b>reverse-mode automatic differentiation</b>: you write the forward computation, the framework computes exact gradients by walking the graph backward. That is what makes training arbitrary architectures possible without hand-deriving a single derivative.'],
      table: { cols: ['', 'PyTorch', 'TensorFlow / Keras', 'JAX / Flax'], rows: [
        ['Style', 'eager, define-by-run', 'Keras high-level; graph via <code>tf.function</code>', 'functional, pure functions'],
        ['Autodiff', 'tape-based autograd', 'GradientTape', '<code>grad</code> transform'],
        ['Killer feature', 'Pythonic, huge ecosystem', 'deployment (TF Serving, Lite, JS)', '<code>jit</code>/<code>vmap</code>/<code>pmap</code> composability'],
        ['Hardware', 'GPU, some TPU', 'GPU, TPU', 'GPU, <b>TPU-first</b>'],
        ['Best for', 'research, most production', 'mobile/edge, enterprise pipelines', 'large-scale, HPC, research']] },
      ex: [{ h: 'Autograd in a few lines of PyTorch', p: ['Mark tensors <code>requires_grad=True</code>, run a forward computation, call <code>.backward()</code>, and the exact partial derivatives appear in <code>.grad</code>. This tiny example is the same machinery that trains a billion-parameter model.'],
        code: 'import torch\n\nx = torch.tensor([1.0, 2.0, 3.0], requires_grad=True)\nw = torch.tensor([0.5, -1.0, 2.0], requires_grad=True)\n\ny = (w * x).sum()          # forward: a scalar\ny.backward()               # reverse-mode autodiff\n\nprint(x.grad)              # dy/dx = w  -> [ 0.5, -1.0, 2.0]\nprint(w.grad)              # dy/dw = x  -> [ 1.0,  2.0, 3.0]' },
        { h: 'A real PyTorch training loop', p: ['Every PyTorch model trains with the same five-step rhythm: <b>forward</b> to get predictions, compute the <b>loss</b>, <code>zero_grad</code> to clear stale gradients, <b>backward</b> to fill <code>.grad</code>, and <code>optimizer.step()</code> to update the weights. Note <code>.to(device)</code> — the one line that moves computation to the GPU.'],
        code: 'import torch, torch.nn as nn\n\ndevice = "cuda" if torch.cuda.is_available() else "cpu"\n\nmodel = nn.Sequential(\n    nn.Linear(20, 64), nn.ReLU(),\n    nn.Linear(64, 3),\n).to(device)\n\nloss_fn = nn.CrossEntropyLoss()\nopt = torch.optim.AdamW(model.parameters(), lr=1e-3)\n\nfor epoch in range(10):\n    for xb, yb in train_loader:               # batches from a DataLoader\n        xb, yb = xb.to(device), yb.to(device)\n        pred = model(xb)                      # 1. forward\n        loss = loss_fn(pred, yb)              # 2. loss\n        opt.zero_grad()                       # 3. clear old grads\n        loss.backward()                       # 4. backprop\n        opt.step()                            # 5. update weights' }],
      note: 'Forgetting <code>opt.zero_grad()</code> is the classic beginner bug: PyTorch <i>accumulates</i> gradients by default, so without it, gradients from every batch pile up and training silently diverges.' },

    { h: 'The Hugging Face ecosystem', p: [
      'Hugging Face turned "download a pretrained model" into three lines. <b>transformers</b> hosts hundreds of thousands of models with a uniform API and the <code>pipeline</code> helper for instant inference. <b>datasets</b> streams and memory-maps huge corpora with Arrow so they never blow up RAM. <b>tokenizers</b> provides fast Rust-backed subword tokenizers (BPE, WordPiece, Unigram) that turn text into the integer IDs models consume.',
      'The <b>Hub</b> ties it together: models, datasets and demos are versioned Git repos you pull with an identifier. It is the npm/PyPI of machine-learning artifacts, and the reason a new state-of-the-art model is usable the day it drops.'],
      ex: [{ h: 'From raw text to a prediction in a few lines', p: ['The high-level <code>pipeline</code> for zero-config inference, then the lower-level tokenizer-plus-model path when you need control over batching, truncation and the raw logits.'],
        code: 'from transformers import pipeline, AutoTokenizer, AutoModelForSequenceClassification\nimport torch\n\n# high level: one line to a working classifier\nclf = pipeline("sentiment-analysis")\nclf("This library is delightful.")   # [{"label": "POSITIVE", "score": 0.9998}]\n\n# low level: full control\nname = "distilbert-base-uncased-finetuned-sst-2-english"\ntok = AutoTokenizer.from_pretrained(name)\nmodel = AutoModelForSequenceClassification.from_pretrained(name)\n\nbatch = tok(["great!", "terrible."], padding=True, truncation=True, return_tensors="pt")\nwith torch.no_grad():\n    logits = model(**batch).logits\nprobs = logits.softmax(dim=-1)' }],
      note: 'Related libraries round it out: <code>accelerate</code> (multi-GPU/distributed), <code>peft</code> (LoRA and other parameter-efficient fine-tuning), and <code>safetensors</code> (a fast, safe weight format).' },

    { h: 'Beyond Python: the right language for the job', p: [
      'Python is the hub, but production systems are polyglot. <b>R</b> remains superb for classical statistics, experimental design and publication-quality graphics (ggplot2). <b>SQL</b> is non-negotiable — it is how you actually query the warehouse where the data lives. <b>Go</b> and <b>Rust</b> build the fast, concurrent services that <i>serve</i> models. <b>C++ and CUDA</b> are where the custom kernels and the frameworks themselves are written.',
      'The pattern: prototype and train in Python, then push the latency-critical or memory-critical pieces down to a compiled language. Rust in particular is increasingly the choice for tokenizers, data loaders and inference servers because it is fast without a garbage collector.'],
      table: { cols: ['Language', 'Sweet spot in AI', 'Why'], rows: [
        ['Python', 'training, glue, research', 'ecosystem + readability'],
        ['R', 'statistics, biostat, viz', 'stats depth, ggplot2, tidyverse'],
        ['SQL', 'querying & aggregating data', 'the data lives in databases'],
        ['Go', 'model-serving microservices', 'simple concurrency, fast deploys'],
        ['Rust', 'tokenizers, data loaders, inference', 'C-speed, memory-safe, no GC'],
        ['C++', 'framework internals, latency', 'raw performance, control'],
        ['CUDA', 'GPU kernels', 'direct hardware parallelism']] },
      ex: [{ h: 'SQL is still where most data work starts', p: ['Before any model, you pull and shape data with SQL. Window functions, group-bys and joins do server-side what you\'d otherwise drag into Pandas.'],
        code: 'SELECT region,\n       COUNT(*)              AS orders,\n       SUM(revenue)          AS total,\n       AVG(revenue)          AS avg_order,\n       RANK() OVER (ORDER BY SUM(revenue) DESC) AS rank\nFROM   sales\nWHERE  order_date >= \'2026-01-01\'\nGROUP  BY region\nHAVING SUM(revenue) > 10000\nORDER  BY total DESC;' }] },

    { h: 'Reproducible environments & version control', p: [
      '"It works on my machine" is a bug. Reproducibility means anyone can recreate the exact same environment. <b>venv</b> isolates pip packages per project. <b>conda</b> goes further, managing non-Python dependencies (CUDA toolkits, MKL, compilers) that ML needs. <b>Docker</b> captures the whole OS-level environment in an image that runs identically everywhere. A <b>lockfile</b> pins every transitive dependency to an exact version and hash, so <code>install</code> is deterministic.',
      'Alongside the environment, every project — code, configs, even prompts — belongs in <b>git</b>. It records snapshots (<b>commits</b>), lets you experiment on <b>branches</b>, and merges work back together via <b>pull requests</b> for review. Keep large data and model weights <i>out</i> of git — use <code>.gitignore</code> plus a dedicated store (git-LFS, DVC, or object storage) so the repo stays lean.'],
      ex: [{ h: 'From loose requirements to a pinned, containerised build', p: ['A minimal reproducible setup: a virtual environment, a compiled lockfile, and a Dockerfile that bakes the exact dependencies into an image.'],
        code: '# create an isolated env and pin exact versions\npython -m venv .venv && source .venv/bin/activate\npip install -r requirements.txt\npip freeze > requirements.lock    # exact versions of everything\n\n# --- Dockerfile ---------------------------------\n# FROM python:3.12-slim\n# WORKDIR /app\n# COPY requirements.lock .\n# RUN pip install --no-cache-dir -r requirements.lock\n# COPY . .\n# CMD ["python", "serve.py"]' },
        { h: 'The everyday git workflow', p: ['Branch, make a change, snapshot it, and push it for review. This is the loop you\'ll run dozens of times a day. Commit messages are documentation: "fix" tells future-you nothing; "Handle empty input in batch collate" tells the whole story.'],
        code: 'git checkout -b feature/better-tokenizer   # branch off main\n\n# ...edit files...\ngit status                    # what changed?\ngit add tokenizer.py          # stage specific files\ngit commit -m "Add BPE fallback for OOV tokens"\n\ngit pull --rebase origin main # bring in others\' work\ngit push -u origin feature/better-tokenizer\n# ...then open a pull request for review' }],
      terms: [['venv', 'lightweight per-project pip isolation, stdlib.'], ['conda', 'manages Python + native deps (CUDA, MKL).'], ['Docker image', 'the whole environment, portable and versioned.'], ['Lockfile', 'exact pinned versions + hashes for determinism.']] },

    { h: 'Data stores: SQL, NoSQL, and the CAP/ACID trade-offs', p: [
      'There is no universal database — you pick by access pattern. <b>Relational (SQL)</b> stores enforce a schema and offer <b>ACID</b> transactions: ideal when correctness and relationships matter (orders, payments). <b>Document</b> stores hold flexible JSON; <b>key-value</b> stores are dead-simple fast caches; <b>columnar</b> stores crush analytical scans over billions of rows; <b>graph</b> stores make relationship queries first-class. Each optimises a different shape of query.',
      'Distributed systems face the <b>CAP theorem</b>: under a network <b>P</b>artition you must choose <b>C</b>onsistency (reject reads/writes that might be stale) or <b>A</b>vailability (answer, possibly with stale data). This drives the split between <b>ACID</b> (strong, transactional) and <b>BASE</b> (Basically Available, Soft state, Eventually consistent) systems that trade strict consistency for scale and uptime.'],
      eqn: 'CAP:  under Partition, pick Consistency OR Availability (not both)\nACID: Atomic, Consistent, Isolated, Durable   (strong)\nBASE: Basically Available, Soft state, Eventual  (scalable)',
      table: { cols: ['Type', 'Model', 'Guarantees', 'When to use'], rows: [
        ['Relational', 'tables + joins (Postgres, MySQL)', 'ACID, strong schema', 'transactions, relationships, correctness'],
        ['Document', 'JSON docs (MongoDB)', 'flexible, often BASE', 'evolving schemas, nested objects'],
        ['Key-value', 'map (Redis, DynamoDB)', 'fast, simple', 'caching, sessions, counters'],
        ['Columnar', 'column store (ClickHouse, BigQuery)', 'analytical, append-heavy', 'aggregations over huge tables'],
        ['Graph', 'nodes + edges (Neo4j)', 'traversal-optimised', 'social graphs, recommendations, fraud'],
        ['Vector', 'embeddings + ANN (see below)', 'similarity search', 'semantic search, RAG']] },
      note: 'A real system usually combines several: Postgres for the source of truth, Redis for hot caches, a columnar warehouse for analytics, and a vector store for semantic retrieval.' },

    { h: 'Vector databases for embeddings and RAG', p: [
      'Modern AI runs on <b>embeddings</b> — dense vectors where semantic similarity is geometric closeness. A <b>vector database</b> (FAISS, Qdrant, Pinecone, pgvector, Milvus, Weaviate) stores millions of these and answers "find the k nearest vectors to this query" in milliseconds using <b>Approximate Nearest Neighbour (ANN)</b> indexes like HNSW — trading a sliver of recall for enormous speed.',
      'This is the retrieval half of <b>Retrieval-Augmented Generation (RAG)</b>: chunk your documents, embed each chunk, and store the vectors. At query time, embed the question, retrieve the closest chunks, and stuff them into the LLM\'s prompt as context. The model answers from <i>your</i> data instead of hallucinating, and you can update knowledge by re-indexing rather than retraining.'],
      eqn: 'similarity(q, d) = cos(q, d) = (q . d) / (|q| |d|)   # nearest = most relevant',
      ex: [{ h: 'Build a tiny RAG retriever', p: ['Embed a corpus, index it for fast similarity search, then retrieve the most relevant chunks for a query. Those chunks become the context you hand to a generator.'],
        code: 'from sentence_transformers import SentenceTransformer\nimport numpy as np, faiss\n\nembedder = SentenceTransformer("all-MiniLM-L6-v2")\ndocs = ["Cats purr when content.",\n        "Python is a programming language.",\n        "The GIL limits CPU-bound threads."]\n\nvecs = embedder.encode(docs, normalize_embeddings=True)\nindex = faiss.IndexFlatIP(vecs.shape[1])   # inner product = cosine (normalized)\nindex.add(np.asarray(vecs, dtype="float32"))\n\nq = embedder.encode(["Why is Python slow with threads?"],\n                    normalize_embeddings=True)\nscores, ids = index.search(np.asarray(q, dtype="float32"), k=1)\nprint(docs[ids[0][0]])   # -> "The GIL limits CPU-bound threads."' }],
      note: 'pgvector is often the pragmatic first choice: it adds vector search to the Postgres you already run, so retrieval lives next to your relational data with no new service.' },

    { h: 'Performance: vectorize, batch, use the GPU, profile', p: [
      'Fast AI code follows four habits. <b>Vectorize</b>: replace Python loops with array operations so the arithmetic runs in C/CUDA. <b>Batch</b>: process many items per call — a GPU processing 256 examples at once is vastly more efficient than 256 calls of one, because it hides memory latency behind parallel compute. <b>Use the GPU</b>: move tensors and models to the device and keep them there; the killer cost is shuffling data back and forth across the CPU-GPU boundary. <b>Profile</b>: measure before optimising — intuition about bottlenecks is usually wrong.',
      'The order matters: profile to find the real hot spot, then vectorize and batch it, then reach for the GPU. Optimising code that isn\'t the bottleneck is wasted effort — a routine that runs 1% of the time can\'t be sped up by more than 1%.'],
      ex: [{ h: 'Profile first, then batch on the GPU', p: ['A one-line profiler finds where time actually goes. Then batched GPU inference under <code>no_grad</code> replaces a per-item Python loop — often a 10-100x throughput win.'],
        code: 'import cProfile, torch\n\ncProfile.run("train_one_epoch()", sort="cumtime")  # find the real bottleneck\n\n# batched GPU inference: many items in one call, gradients off\nmodel.eval()\nresults = []\nwith torch.no_grad():                      # skip the autograd graph\n    for xb in batched(data, size=256):     # big batches feed the GPU\n        xb = xb.to("cuda", non_blocking=True)\n        results.append(model(xb).cpu())    # move back only the results\nout = torch.cat(results)' }],
      terms: [['Vectorize', 'loops become array ops running in C/CUDA.'], ['Batch', 'amortise overhead; saturate the GPU\'s parallelism.'], ['Device transfer', 'CPU<->GPU copies are slow; minimise them.'], ['Profile', 'measure with cProfile / torch.profiler before optimising.']],
      note: 'Amdahl\'s law in one sentence: your speedup is capped by the fraction of time you did NOT optimise. Always profile first.' },
  ]
});
