/* Deep dive — Research methodology & evaluation for AI */
window.AtlasRef && window.AtlasRef.register('research', {
  color: '#8B8CF6',
  title: 'How we actually know a model is better',
  lead: 'Machine learning is an empirical science, and its progress rests entirely on rigorous evaluation. This is the methodology course: the scientific method applied to ML, generalization theory, honest validation and cross-validation, the bootstrap and confidence intervals, hypothesis testing done right, benchmarks and their traps, ablations, and the reproducibility practices that separate real results from noise.',
  sections: [

    { h: 'The scientific method applied to ML', p: [
      'A machine-learning experiment is a scientific experiment. You start with a <b>hypothesis</b> stated precisely enough to be falsified — not <i>"attention is nice"</i> but <i>"adding cross-attention lowers validation perplexity on this corpus by more than run-to-run noise"</i>. You then design a test with <b>controls</b>: hold everything fixed except the one thing you are studying, so any measured difference can be attributed to it.',
      'The three pillars are <b>controlled comparison</b> (change one variable at a time), <b>ablation</b> (remove a component to see if it mattered), and <b>replication</b> (repeat with new seeds and data to show the effect is real). A result that only appears with one lucky seed, one dataset split, or one hyperparameter setting is not yet a finding — it is a conjecture.'],
      terms: [['Hypothesis', 'a falsifiable, quantitative claim about a mechanism or effect.'], ['Control', 'the baseline held identical except for the studied change.'], ['Confound', 'a hidden variable (e.g. more compute) that co-varies with your change and could explain the result instead.'], ['Ablation', 'deliberately removing a component to test its contribution.']],
      ex: [{ h: 'A controlled comparison', p: ['Claim: <i>"our new positional encoding helps."</i> A fair test trains two models identical in parameters, data, optimizer, budget and seeds — differing <b>only</b> in the encoding — and compares validation loss across several seeds. If the new model also secretly got 2x compute, compute is a <b>confound</b> and the experiment proves nothing.'],
        code: 'for seed in [0, 1, 2, 3, 4]:\n    baseline = train(encoding=\'sinusoidal\', seed=seed, budget=B)\n    variant  = train(encoding=\'rope\',       seed=seed, budget=B)\n    # everything else identical; compare the paired distributions\n    log(seed, baseline.val_loss, variant.val_loss)' }],
      note: 'The single most common methodological error in ML papers is an uncontrolled comparison: the proposed method also got more data, more tuning, or a bigger budget than the baseline.' },

    { h: 'Generalization & the bias–variance tradeoff', p: [
      'The whole point of learning is <b>generalization</b>: low error on unseen data, not on the training set. The gap between training and test error is the <b>generalization gap</b>. Expected test error decomposes into three parts, and understanding this decomposition explains almost every failure mode in ML.',
      '<b>Bias</b> is error from wrong assumptions — the model is too simple to capture the signal (underfitting). <b>Variance</b> is error from sensitivity to the particular training sample — the model changes wildly if you resample the data (overfitting). <b>Irreducible noise</b> is the floor you can never beat. The classic tradeoff: simple models have high bias and low variance; complex models have low bias and high variance. The sweet spot minimizes their sum.'],
      eqn: 'E[(y - f̂(x))²] = Bias[f̂(x)]² + Var[f̂(x)] + σ²\n  Bias   = E[f̂(x)] - f(x)        (systematic error)\n  Var    = E[(f̂(x) - E[f̂(x)])²]   (sensitivity to sample)\n  σ²     = irreducible noise floor',
      ex: [{ h: 'Seeing the decomposition empirically', p: ['Fit polynomials of increasing degree to many resampled datasets. Degree 1 is biased (misses the curve, but stable across samples). Degree 15 has low bias but huge variance (each fit wiggles differently). Estimate bias² and variance by averaging predictions across resamples at a fixed test point.'],
        code: 'import numpy as np\ndef bias_var(degree, x0, n_sets=200, n=30):\n    preds = []\n    for _ in range(n_sets):\n        x = np.random.uniform(-1, 1, n)\n        y = np.sin(3*x) + np.random.normal(0, 0.2, n)\n        c = np.polyfit(x, y, degree)\n        preds.append(np.polyval(c, x0))\n    preds = np.array(preds)\n    bias2 = (preds.mean() - np.sin(3*x0))**2\n    var   = preds.var()\n    return bias2, var\nbias_var(1, 0.5)   # high bias, low var\nbias_var(15, 0.5)  # low bias, high var' }],
      note: 'More training data mostly reduces variance, not bias. A biased (underfit) model will not improve much with more data — you need a richer model or better features.' },

    { h: 'Overfitting, underfitting & regularization', p: [
      '<b>Underfitting</b>: high training error and high test error — the model lacks capacity or has not trained enough. <b>Overfitting</b>: low training error but high test error — the model memorized noise. You diagnose them from <b>learning curves</b>: plot train and validation error vs training progress or dataset size and read the gap.',
      '<b>Regularization</b> is any technique that trades a little training fit for better generalization by constraining the model. L2 (weight decay) shrinks weights toward zero; L1 (Lasso) drives them to exactly zero for sparsity; <b>dropout</b> randomly zeros activations so no neuron can rely on a specific partner; <b>early stopping</b> halts before validation loss turns back up; <b>data augmentation</b> expands the effective dataset. All of them reduce variance at the cost of a small increase in bias — moving you back toward the sweet spot.'],
      eqn: 'L2:  L(θ) + λ‖θ‖²        L1:  L(θ) + λ‖θ‖₁\nlarge λ ⇒ more constraint ⇒ higher bias, lower variance',
      table: { cols: ['Symptom', 'Train err', 'Val err', 'Diagnosis', 'Fix'], rows: [
        ['<b>Underfit</b>', 'high', 'high (≈ train)', 'too little capacity', 'bigger model, more features, train longer, less regularization'],
        ['<b>Good fit</b>', 'low', 'low (small gap)', 'balanced', 'ship it'],
        ['<b>Overfit</b>', 'very low', 'high (big gap)', 'memorizing noise', 'regularize, more data, augment, early-stop']] },
      ex: [{ h: 'Reading a learning curve', p: ['Train a model and log both curves each epoch. While both fall together you are underfitting — keep going. The moment validation loss flattens and starts to rise while training loss keeps dropping, the gap is overfitting; <b>early stopping</b> saves the checkpoint at the validation minimum.'],
        code: 'best, patience, wait = 1e9, 5, 0\nfor epoch in range(200):\n    train_one_epoch(model)\n    v = validate(model)\n    if v < best:\n        best, wait = v, 0\n        save_checkpoint(model)      # keep the val-optimal weights\n    else:\n        wait += 1\n        if wait >= patience:\n            break                   # early stop' }] },

    { h: 'Double descent & no free lunch', p: [
      'The classic bias–variance U-curve is not the whole story. <b>Double descent</b>: as model size (or training time) grows past the <b>interpolation threshold</b> — the point where the model can exactly fit the training data — test error first rises (classical overfitting), peaks, and then <i>falls again</i>, often below the earlier minimum. Very overparameterized models can generalize well, which is why enormous neural nets work at all. Modern deep learning largely lives in this second descent.',
      'The <b>no-free-lunch theorem</b> is the counterweight: averaged over <i>all possible</i> problems, every learning algorithm has identical performance. There is no universally best model. Any method that beats another does so only by matching the structure of the specific problems we care about. Inductive biases (convolutions for images, attention for sequences) are not free lunches — they are bets that the data has a particular structure.'],
      eqn: 'test error vs capacity:\n  small ── U-curve ──▶ peak at interpolation threshold ──▶ second descent (falls again)',
      terms: [['Interpolation threshold', 'capacity at which the model can fit the training set to zero error.'], ['Overparameterization', 'more parameters than training points — the regime of the second descent.'], ['No free lunch', 'no learner is best on average across all problems; superiority is always problem-specific.'], ['Inductive bias', 'built-in assumptions that make a model good on some problem families and worse on others.']],
      note: 'Practical takeaway: the folk rule "more parameters always overfit" is false for modern nets. But NFL means benchmarks and domain match still decide everything — you cannot escape choosing assumptions.' },

    { h: 'Honest validation & cross-validation', p: [
      'A single train/test split wastes data and gives a noisy estimate. <b>k-fold cross-validation</b> splits the data into k parts, trains on k−1 and tests on the held-out fold, rotating k times, then averages — every point is used for both training and testing, and you get a spread (mean ± std) rather than one number.',
      'Choose the variant to match your data. <b>Stratified</b> k-fold preserves class proportions in each fold (essential for imbalanced classification). <b>Grouped</b> k-fold keeps all rows from the same entity (patient, user, document) in a single fold — otherwise near-duplicate rows leak between train and test and inflate scores. The cardinal rule: <b>the test fold must never touch anything used to fit the model or choose its settings.</b>'],
      table: { cols: ['Scheme', 'Use when', 'Guards against'], rows: [
        ['<b>k-fold</b>', 'plain i.i.d. data', 'noisy single-split estimates'],
        ['<b>Stratified</b>', 'imbalanced classes', 'folds missing rare classes'],
        ['<b>Grouped</b>', 'repeated measures per entity', 'leakage of the same subject across folds'],
        ['<b>Time-series split</b>', 'temporal order matters', 'training on the future to predict the past'],
        ['<b>Nested</b>', 'you also tune hyperparameters', 'optimistic bias from tuning on the test fold']] },
      ex: [{ h: 'Grouped k-fold prevents leakage', p: ['A medical dataset has 5 scans per patient. Plain k-fold can put patient A\'s scans 1–3 in train and 4–5 in test; the model recognizes the patient, not the disease, and scores look great — then collapse in the clinic. <b>GroupKFold</b> keyed on patient id forces every patient entirely into one fold.'],
        code: 'from sklearn.model_selection import GroupKFold, cross_val_score\ngkf = GroupKFold(n_splits=5)\nscores = cross_val_score(model, X, y, groups=patient_id, cv=gkf)\nprint(f\'{scores.mean():.3f} +/- {scores.std():.3f}\')  # honest estimate' }] },

    { h: 'Nested cross-validation for honest tuning', p: [
      'Here is the subtle trap that ruins many results. If you use cross-validation to <b>choose</b> hyperparameters and then report that same cross-validation score, the number is optimistically biased: you peeked at every fold while selecting, so the "test" folds secretly influenced the model. The reported score is a training score in disguise.',
      '<b>Nested cross-validation</b> fixes this with two loops. The <b>inner</b> loop selects hyperparameters on the training portion only; the <b>outer</b> loop then evaluates the fully-tuned pipeline on a fold it has never seen during selection. The outer scores are an honest estimate of generalization <i>including the cost of model selection</i>. Use it whenever you both tune and want a trustworthy performance number.'],
      eqn: 'outer fold i:\n   train_i ──▶ INNER CV picks best hyperparams θ*_i\n   refit on train_i with θ*_i ──▶ score on test_i (untouched)\nhonest estimate = mean over outer test folds',
      ex: [{ h: 'Nested CV in scikit-learn', p: ['GridSearchCV is itself an estimator that does the inner loop; wrapping it in cross_val_score adds the outer loop. The outer scores reflect real deployment performance; the inner best-params may differ across outer folds, and that variability is itself informative about tuning stability.'],
        code: 'from sklearn.model_selection import GridSearchCV, StratifiedKFold, cross_val_score\nfrom sklearn.svm import SVC\ninner = StratifiedKFold(5, shuffle=True, random_state=0)\nouter = StratifiedKFold(5, shuffle=True, random_state=1)\ngrid  = {\'C\': [0.1, 1, 10], \'gamma\': [1e-2, 1e-3]}\nsearch = GridSearchCV(SVC(), grid, cv=inner)     # inner: selection\nnested = cross_val_score(search, X, y, cv=outer) # outer: honest eval\nprint(f\'honest accuracy = {nested.mean():.3f} +/- {nested.std():.3f}\')' }],
      note: 'Rule of thumb: any decision you make by looking at a score must be evaluated on data that score never saw. Nested CV enforces this automatically.' },

    { h: 'The bootstrap & confidence intervals', p: [
      'The <b>bootstrap</b> estimates the uncertainty of almost any statistic without formulas or distributional assumptions. You resample your data <i>with replacement</i> to the same size, recompute the metric, and repeat thousands of times. The spread of those recomputed values approximates the sampling distribution — so you can read off a standard error or a confidence interval directly.',
      'A <b>95% confidence interval</b> is a range constructed so that, under repeated sampling, 95% of such intervals would contain the true value. The <b>percentile bootstrap CI</b> is simply the 2.5th and 97.5th percentiles of the bootstrap replicates. It answers the question every result needs: <i>"is 84% accuracy meaningfully above 82%, or within noise?"</i>'],
      eqn: 'for b in 1..B:  sample* = resample(data, replace=True); θ*_b = stat(sample*)\nSE ≈ std(θ*)      95% CI ≈ [percentile(θ*, 2.5), percentile(θ*, 97.5)]',
      ex: [{ h: 'Bootstrap CI for test accuracy', p: ['You have per-example correct/incorrect flags on the test set. Resample those flags with replacement B=10,000 times, take the mean each time, and read the 2.5%/97.5% percentiles. If model A\'s CI is [0.81, 0.87] and model B\'s point estimate 0.82 sits inside it, the "improvement" is not distinguishable from noise on this test set.'],
        code: 'import numpy as np\ndef bootstrap_ci(correct, B=10000, alpha=0.05, seed=0):\n    rng = np.random.default_rng(seed)\n    n = len(correct)\n    stats = np.empty(B)\n    for b in range(B):\n        idx = rng.integers(0, n, n)        # resample with replacement\n        stats[b] = correct[idx].mean()\n    lo, hi = np.quantile(stats, [alpha/2, 1 - alpha/2])\n    return correct.mean(), (lo, hi)\n\ncorrect = np.array([1,1,0,1,1,1,0,1,1,0] * 20)  # per-example flags\nacc, (lo, hi) = bootstrap_ci(correct)\nprint(f\'accuracy {acc:.3f}  95% CI [{lo:.3f}, {hi:.3f}]\')' }],
      note: 'For paired model comparison, bootstrap the per-example difference (A_correct - B_correct). If that CI excludes zero, A is reliably better on this data.' },

    { h: 'Hypothesis testing done right', p: [
      'A significance test starts from a <b>null hypothesis</b> H₀ ("no difference") and asks: if H₀ were true, how surprising is data at least this extreme? That probability is the <b>p-value</b>. A small p (conventionally < 0.05) means the data would be unlikely under pure chance, so you reject H₀. That is all it says.',
      'What a p-value <b>does not</b> mean: it is <i>not</i> the probability that H₀ is true, <i>not</i> the probability your result was a fluke, and <i>not</i> a measure of effect size. A tiny p with a massive sample can accompany a trivially small, useless effect. Always report the <b>effect size</b> (how big the difference is, e.g. Cohen\'s d) and a confidence interval alongside any p-value.'],
      eqn: 'p = P(observe data this extreme | H₀ true)\nCohen\'s d = (mean₁ - mean₂) / pooled_std      (effect size, unit-free)\np < 0.05  ⇏  large effect      p > 0.05  ⇏  no effect (maybe low power)',
      ex: [{ h: 'A paired test between two models', p: ['Two models were evaluated on the same test examples, so the samples are <b>paired</b>. A paired t-test (or its non-parametric cousin, Wilcoxon signed-rank) on the per-example scores tells you whether the mean difference is distinguishable from zero. Report the p-value <i>and</i> the mean gap with its CI, not the p-value alone.'],
        code: 'from scipy import stats\nimport numpy as np\nacc_a = np.array(scores_model_a)   # per-example, same order\nacc_b = np.array(scores_model_b)\nt, p = stats.ttest_rel(acc_a, acc_b)          # paired t-test\nd = (acc_a - acc_b).mean() / (acc_a - acc_b).std(ddof=1)  # effect size\nprint(f\'mean gap {(acc_a-acc_b).mean():+.4f}, p={p:.4g}, d={d:.2f}\')' }],
      terms: [['Null hypothesis H₀', 'the default "nothing is going on" claim you try to reject.'], ['Type I error', 'a false positive — rejecting H₀ when it is true (rate α).'], ['Type II error', 'a false negative — failing to detect a real effect (rate β).'], ['Statistical power', '1 − β; the chance of detecting a real effect, driven by sample size and effect size.']] },

    { h: 'Multiple comparisons & significance vs importance', p: [
      'Run one test at α = 0.05 and you accept a 5% false-positive rate. Run 20 tests and you expect one "significant" result by pure chance even if nothing is real — this is the <b>multiple-comparisons problem</b>, and it is rampant when you sweep many hyperparameters, metrics, or dataset slices and report only the winners. The more you look, the more noise you mistake for signal.',
      'Corrections restore honesty. <b>Bonferroni</b> divides the threshold by the number of tests (α/m) — simple and conservative. The <b>Benjamini–Hochberg</b> procedure controls the false discovery rate and is less strict when you run many tests. Separately, remember that <b>statistical significance ≠ practical significance</b>: with enough data almost any difference becomes "significant," so ask whether the effect is large enough to matter for your application, not merely whether p crossed a line.'],
      eqn: 'family-wise error with m tests:  1 − (1 − α)^m   (grows fast with m)\nBonferroni:  reject if  pᵢ < α / m',
      ex: [{ h: 'Bonferroni on a metric sweep', p: ['You compare your model to a baseline on 10 datasets and find p = 0.03 on one of them. With 10 tests, the Bonferroni threshold is 0.05/10 = 0.005, so p = 0.03 is <b>not</b> significant after correction — that lone win is plausibly chance. Report all 10 comparisons, not just the flattering one.'],
        code: 'import numpy as np\nfrom statsmodels.stats.multitest import multipletests\npvals = np.array([0.03, 0.20, 0.44, 0.09, 0.51, 0.88, 0.30, 0.12, 0.66, 0.40])\nrej_bonf, p_bonf, _, _ = multipletests(pvals, alpha=0.05, method=\'bonferroni\')\nrej_bh,   p_bh,   _, _ = multipletests(pvals, alpha=0.05, method=\'fdr_bh\')\nprint(\'Bonferroni survivors:\', rej_bonf.sum())   # -> 0\nprint(\'Benjamini-Hochberg  :\', rej_bh.sum())' }],
      note: 'A difference of 0.1% accuracy can be statistically significant on a million-example test set and completely irrelevant in practice. Significance answers "is it real?", not "does it matter?"' },

    { h: 'Benchmarks, leaderboards & their pitfalls', p: [
      'Shared benchmarks let the field measure progress on a common yardstick. <b>GLUE</b> and its harder successor <b>SuperGLUE</b> measure language understanding; <b>MMLU</b> tests broad knowledge across 57 subjects; <b>ImageNet</b> anchored the vision revolution; <b>HELM</b> evaluates language models <i>holistically</i> across many scenarios and metrics (accuracy, robustness, bias, efficiency) rather than a single score.',
      'Leaderboards are also a trap. <b>Contamination</b>: the test set leaked into pretraining data, so the model has literally seen the answers — a growing crisis as models train on the whole web. <b>Overfitting to the benchmark</b>: thousands of researchers tuning against the same public test set collectively overfit it, so leaderboard gains stop transferring to real use (Goodhart\'s law — "when a measure becomes a target, it ceases to be a good measure"). <b>Saturation</b>: once scores approach the human ceiling, differences are noise. Always check for contamination, hold out a truly private test set, and treat a single benchmark number with suspicion.'],
      table: { cols: ['Benchmark', 'Domain', 'Watch out for'], rows: [
        ['<b>GLUE / SuperGLUE</b>', 'language understanding', 'saturated; models exceed human baselines'],
        ['<b>MMLU</b>', '57-subject knowledge QA', 'train-set contamination; a few mislabeled items'],
        ['<b>ImageNet</b>', 'image classification', 'label errors; overfit from years of tuning'],
        ['<b>HELM</b>', 'holistic LM evaluation', 'many metrics — no single ranking, by design'],
        ['<b>Any public leaderboard</b>', 'all', 'contamination, community overfitting, Goodhart']] },
      ex: [{ h: 'A quick contamination check', p: ['Before trusting a benchmark score, probe whether the model memorized the test set. One cheap heuristic: show the first half of a test question and see if the model completes the canonical second half verbatim, or ask it to reproduce a test item from its id. High verbatim recall is a red flag that the score is inflated by contamination.'],
        code: 'suspect = 0\nfor item in benchmark_test_set:\n    prompt = item[\'question\'][: len(item[\'question\']) // 2]\n    completion = model.generate(prompt, max_new_tokens=64)\n    if normalized(item[\'question\'][len(prompt):]) in normalized(completion):\n        suspect += 1        # model reproduced held-out text verbatim\nprint(f\'possible contamination: {suspect}/{len(benchmark_test_set)}\')' }] },

    { h: 'Ablation studies', p: [
      'An <b>ablation</b> answers the question a proposed system rarely does honestly: <i>which parts actually matter?</i> You take the full model and remove or disable one component at a time — a loss term, an attention head, a data-augmentation, a module — retrain, and measure how much performance drops. A component that can be removed with no loss was decorative; the size of the drop is the evidence for its contribution.',
      'Good ablations are controlled (change one thing, keep budget and everything else fixed), report variance across seeds (a 0.1-point drop inside the noise band proves nothing), and include the informative extremes: the full model, the model minus each piece, and a stripped baseline. Ablation is the ML analogue of a controlled lesion experiment — it converts "we added many tricks and it got better" into "trick X is responsible for this much of the gain."'],
      eqn: 'Δ_component = score(full) − score(full − component)\nlarge, robust Δ ⇒ the component earns its place',
      ex: [{ h: 'Ablating components of a model', p: ['Suppose a system stacks three additions: an auxiliary loss, data augmentation, and a residual connection. Train the full model plus one variant per removed piece, each over several seeds, and tabulate the mean drop with its spread. A component whose removal costs less than the seed-to-seed standard deviation is not doing real work.'],
        code: 'import numpy as np\nconfigs = {\n    \'full\':       dict(aux=True,  aug=True,  res=True),\n    \'-aux_loss\':  dict(aux=False, aug=True,  res=True),\n    \'-augment\':   dict(aug=False, aux=True,  res=True),\n    \'-residual\':  dict(res=False, aux=True,  aug=True),\n}\nfor name, cfg in configs.items():\n    accs = [train(**cfg, seed=s).test_acc for s in range(5)]\n    print(f\'{name:12s} {np.mean(accs):.3f} +/- {np.std(accs):.3f}\')' }],
      note: 'Beware ablation interactions: two components may only help together, so removing either alone looks harmless. When suspected, ablate combinations, not just singletons.' },

    { h: 'Reproducibility & reading papers', p: [
      'ML has a <b>reproducibility crisis</b>: many published gains vanish when reproduced, because they came from lucky seeds, undocumented tricks, unfair baselines, or tuning on the test set. Good practice is unglamorous but decisive: fix and report random <b>seeds</b>, report <b>variance across multiple runs</b> (mean ± std over seeds, never a single cherry-picked number), pin software and hardware, log all hyperparameters, and <b>release code, configs, and data splits</b> so others can rerun exactly. A result you cannot reproduce yourself twice is not a result.',
      'To <b>read a paper efficiently</b>, do not read linearly. First pass (5 min): title, abstract, figures, and conclusion — what is claimed and does the headline plot support it? Second pass: the method and the <b>experimental setup</b> — is the comparison controlled, are baselines tuned as hard as the proposed method, is there an ablation, are error bars shown? Third pass, only if it matters to you: reproduce the key equation or result. Read critically for the <b>frontier themes</b> that recur — <b>scaling laws</b> (performance as a smooth power law in compute, data, and parameters), <b>mixture-of-experts</b> (route each token to a few sub-networks for more capacity at fixed compute), <b>distillation</b> (train a small student to mimic a large teacher), and <b>emergent abilities</b> (capabilities that appear abruptly at scale, though partly an artifact of discontinuous metrics).'],
      terms: [['Seed', 'the value that fixes all randomness; report it and vary it.'], ['Variance across runs', 'std over multiple seeds — the honest error bar on any claim.'], ['Scaling law', 'loss falls as a power law in compute/data/params: L ≈ a·N^(−α).'], ['Distillation', 'compress a large teacher into a small student that mimics its outputs.'], ['Mixture-of-experts', 'sparse routing to sub-networks: more parameters at similar compute.'], ['Emergent ability', 'a skill that appears sharply beyond a scale threshold.']],
      ex: [{ h: 'Making a run reproducible', p: ['Seed every source of randomness (Python, NumPy, the framework, and — where possible — the GPU), then log the exact config and library versions with the results. Report metrics as a mean and standard deviation over several seeds so readers see the noise band, not a single fortunate run.'],
        code: 'import os, random, numpy as np, torch\ndef set_seed(seed):\n    os.environ[\'PYTHONHASHSEED\'] = str(seed)\n    random.seed(seed); np.random.seed(seed)\n    torch.manual_seed(seed); torch.cuda.manual_seed_all(seed)\n    torch.backends.cudnn.deterministic = True\n\nresults = []\nfor seed in [0, 1, 2, 3, 4]:\n    set_seed(seed)\n    results.append(train_and_eval())      # fully reproducible per seed\nprint(f\'{np.mean(results):.3f} +/- {np.std(results):.3f} over 5 seeds\')' }],
      note: 'Checklist for trustworthy results: fixed+varied seeds, mean±std over runs, controlled baselines, at least one ablation, uncertainty on every headline number, and released code + configs.' },
  ]
});
