/* Deep dive — Reinforcement Learning */
window.AtlasRef && window.AtlasRef.register('rl', {
  color: '#FB7185',
  title: 'Learning to act by trial, error and reward',
  lead: 'Reinforcement learning is the science of decision-making. An agent interacts with an environment, receives rewards, and learns a policy that maximises long-term return. This is the full course — the MDP formalism, Bellman equations, dynamic programming, bandits, Monte-Carlo and temporal-difference methods, Q-learning and SARSA, Deep Q-Networks, policy gradients and actor-critic, PPO, and how RLHF aligns modern LLMs — each with intuition, exact formulas, worked examples and code.',
  sections: [

    { h: 'The RL problem: agent, environment, reward', p: [
      'Reinforcement learning frames learning as a <b>loop of interaction</b>. At each step <i>t</i> the <b>agent</b> observes a <b>state</b> sₜ, chooses an <b>action</b> aₜ, and the <b>environment</b> returns a scalar <b>reward</b> rₜ₊₁ and the next state sₜ₊₁. The agent has no labelled examples — only the reward signal — and must discover which actions pay off through <b>trial and error</b>.',
      'This differs fundamentally from other learning paradigms. <b>Supervised</b> learning is given the right answer for each input; <b>unsupervised</b> learning finds structure with no feedback at all. RL sits between: feedback exists but it is <b>evaluative</b> (how good was that action) rather than <b>instructive</b> (what the correct action was), it is often <b>delayed</b>, and the agent\'s own choices shape the data it sees. The goal is not to fit a dataset but to maximise <b>cumulative</b> reward over time.'],
      terms: [['Agent', 'the learner and decision-maker.'], ['Environment', 'everything outside the agent that it interacts with.'], ['State sₜ', 'the situation the agent observes at time t.'], ['Action aₜ', 'a choice the agent makes from the allowed set A.'], ['Reward rₜ₊₁', 'scalar feedback signalling the immediate value of the transition.'], ['Policy π', 'the agent\'s strategy: a mapping from states to actions.']],
      table: { cols: ['Paradigm', 'Feedback', 'Goal'], rows: [
        ['Supervised', 'correct label per example (instructive)', 'match the labels'],
        ['Unsupervised', 'none', 'find structure / density'],
        ['Reinforcement', 'delayed, evaluative reward', 'maximise long-run return']] },
      ex: [{ h: 'The interaction loop as a gym-style program', p: ['Nearly every RL codebase reduces to this loop: reset the environment, then repeatedly act and observe. The agent\'s job is to pick <code>action</code> so that the sum of <code>reward</code> is as large as possible.'],
        code: 'state = env.reset()\ndone = False\nwhile not done:\n    action = agent.act(state)          # choose from policy\n    next_state, reward, done, info = env.step(action)\n    agent.learn(state, action, reward, next_state, done)\n    state = next_state                 # advance the loop' }],
      note: 'The credit-assignment problem — figuring out which of many past actions deserves credit for a reward that arrives much later — is the central difficulty RL algorithms are built to solve.' },

    { h: 'The Markov Decision Process (MDP)', p: [
      'The MDP is the mathematical skeleton of RL. It is the tuple <b>(S, A, P, R, γ)</b>: a set of <b>states</b> S, a set of <b>actions</b> A, a <b>transition function</b> P, a <b>reward function</b> R, and a <b>discount factor</b> γ. The defining assumption is the <b>Markov property</b>: the future depends only on the present state, not the full history — <code>P(sₜ₊₁ | sₜ, aₜ) = P(sₜ₊₁ | s₀,a₀,…,sₜ,aₜ)</code>. A well-chosen state makes this true.',
      'The <b>transition</b> P(s\' | s, a) gives the probability of landing in s\' after taking a in s (the environment can be stochastic). The <b>reward</b> R(s, a) (or R(s,a,s\')) gives the expected immediate reward. Solving the MDP means finding a policy that maximises expected discounted return from every state.'],
      eqn: 'MDP = (S, A, P, R, γ)\nP(s′ | s, a) = Pr[ sₜ₊₁ = s′ | sₜ = s, aₜ = a ]\nR(s, a) = E[ rₜ₊₁ | sₜ = s, aₜ = a ]        γ ∈ [0, 1]',
      terms: [['Markov property', 'the state is a sufficient statistic — history adds nothing.'], ['Transition P', 'stochastic dynamics of the world.'], ['Reward R', 'expected scalar payoff of a transition.'], ['Episode', 'a trajectory s₀,a₀,r₁,s₁,… until a terminal state.'], ['POMDP', 'partially observable MDP: the agent sees observations, not the true state.']],
      ex: [{ h: 'A tiny 2-state MDP', p: ['States {Sunny, Rainy}, actions {Stay, Move}. From Sunny, action Stay keeps you Sunny with probability 0.8 (reward +1) and slips to Rainy with 0.2. Encoding P as a table of probabilities and R as a table of rewards is all an environment needs to be fully specified — every planning algorithm below reads from exactly these two tables.'],
        eqn: 'P(Sunny | Sunny, Stay) = 0.8    P(Rainy | Sunny, Stay) = 0.2\nR(Sunny, Stay) = +1' }] },

    { h: 'Return, and the discount factor γ', p: [
      'The agent does not maximise immediate reward — it maximises the <b>return</b> Gₜ, the total future reward from time t onward. Because a reward now is usually worth more than the same reward later (and to keep sums finite in continuing tasks), we <b>discount</b> future rewards by γ per step. With γ near 0 the agent is myopic (grabs immediate reward); with γ near 1 it is far-sighted (plans for the long run).',
      'The discounted return telescopes neatly: <code>Gₜ = rₜ₊₁ + γ Gₜ₊₁</code>. That recursive identity is the seed of every Bellman equation below.'],
      eqn: 'Gₜ = rₜ₊₁ + γ rₜ₊₂ + γ² rₜ₊₃ + … = Σ (k=0→∞) γᵏ rₜ₊ₖ₊₁\nGₜ = rₜ₊₁ + γ Gₜ₊₁            (recursive form)',
      ex: [{ h: 'Computing a discounted return', p: ['Rewards of [1, 0, 2, −1] over four steps with γ = 0.9. Later rewards count less. The helper below folds from the end of the trajectory, which is exactly how Monte-Carlo methods compute returns in practice.'],
        code: 'def discounted_return(rewards, gamma=0.9):\n    G = 0.0\n    for r in reversed(rewards):     # fold from the tail\n        G = r + gamma * G\n    return G\n\ndiscounted_return([1, 0, 2, -1])   # -> 1 + .9*(0 + .9*(2 + .9*-1)) = 2.61' }],
      note: 'γ also acts as a soft horizon: the effective number of steps that matter is roughly 1/(1−γ). γ = 0.99 ≈ a 100-step horizon.' },

    { h: 'Policy π, value V(s) and action-value Q(s,a)', p: [
      'A <b>policy</b> π defines behaviour: π(a | s) is the probability of taking action a in state s (deterministic policies pick one action). The three central functions all measure expected return <b>under a policy</b>. The <b>state-value</b> Vπ(s) is the expected return starting from s and following π. The <b>action-value</b> Qπ(s, a) is the expected return from taking a in s, then following π. Their difference, the <b>advantage</b> A(s,a) = Q(s,a) − V(s), says how much better an action is than the policy\'s average — the quantity actor-critic methods key on.',
      'V and Q are linked: V is the policy-weighted average of Q over actions, and knowing Q makes control trivial — just act greedily, argmax over a.'],
      eqn: 'Vπ(s) = Eπ[ Gₜ | sₜ = s ]\nQπ(s, a) = Eπ[ Gₜ | sₜ = s, aₜ = a ]\nVπ(s) = Σₐ π(a|s) Qπ(s, a)        A(s,a) = Q(s,a) − V(s)',
      terms: [['Deterministic policy', 'a = π(s); one action per state.'], ['Stochastic policy', 'π(a|s) is a distribution — needed for exploration and continuous control.'], ['Value V(s)', 'how good it is to be in a state.'], ['Q-value Q(s,a)', 'how good a specific action is in a state.'], ['Advantage A(s,a)', 'action-value relative to the state\'s baseline.'], ['Greedy policy', 'π(s) = argmaxₐ Q(s,a).']],
      ex: [{ h: 'From Q to a policy', p: ['If Q(s, ·) = [left: 2.0, right: 5.0, up: 3.1], the greedy policy picks <code>right</code>. Every value-based method (Q-learning, DQN) learns Q and derives the policy this way; the only subtlety is exploring enough to trust those numbers.'],
        code: 'import numpy as np\nQ_s = np.array([2.0, 5.0, 3.1])   # Q(s, a) for 3 actions\ngreedy_action = int(np.argmax(Q_s))  # -> 1  (\'right\')\nV_s = Q_s.max()                    # value of s under greedy policy = 5.0' }] },

    { h: 'Bellman expectation & optimality equations', p: [
      'The <b>Bellman equations</b> turn the recursive return into a self-consistency condition on value functions. The <b>expectation</b> equations describe a <i>fixed</i> policy π: a state\'s value equals the immediate reward plus the discounted value of where you land, averaged over π and the dynamics. The <b>optimality</b> equations describe the <i>best</i> policy: replace the average-over-actions with a <b>max</b> over actions. V*(s) is the value of acting optimally forever after; the optimal policy is greedy w.r.t. Q*.',
      'These equations are the foundation of everything that follows. Dynamic programming solves them exactly when P and R are known; TD and Q-learning solve them approximately from samples when they are not.'],
      eqn: 'Bellman expectation:\n  Vπ(s) = Σₐ π(a|s) Σ_s′ P(s′|s,a) [ R(s,a) + γ Vπ(s′) ]\n  Qπ(s,a) = Σ_s′ P(s′|s,a) [ R(s,a) + γ Σ_a′ π(a′|s′) Qπ(s′,a′) ]\n\nBellman optimality:\n  V*(s) = maxₐ Σ_s′ P(s′|s,a) [ R(s,a) + γ V*(s′) ]\n  Q*(s,a) = Σ_s′ P(s′|s,a) [ R(s,a) + γ max_a′ Q*(s′,a′) ]',
      note: 'The optimality equations are non-linear (the max), so there is no closed-form solve — but the max makes the Bellman operator a contraction, which is why the iterative methods below are guaranteed to converge.' },

    { h: 'Dynamic programming: policy & value iteration', p: [
      'When the MDP is fully known (P and R given), <b>dynamic programming</b> solves it exactly by turning the Bellman equations into update rules. <b>Policy evaluation</b> computes Vπ for a fixed policy by sweeping the expectation update until values stop changing. <b>Policy iteration</b> alternates evaluation with <b>policy improvement</b> (make the policy greedy w.r.t. the current V) and provably converges to the optimal policy. <b>Value iteration</b> is the shortcut: apply the Bellman <i>optimality</i> update directly, folding improvement into every sweep, until V converges — then read off the greedy policy.',
      'Both are <b>bootstrapping</b> methods: they update estimates from other estimates. DP needs a model and sweeps the whole state space, so it does not scale to huge or unknown environments — but it is the conceptual template for the sample-based methods that do.'],
      eqn: 'Policy evaluation:  V(s) ← Σₐ π(a|s) Σ_s′ P(s′|s,a)[R + γ V(s′)]\nValue iteration:    V(s) ← maxₐ Σ_s′ P(s′|s,a)[R + γ V(s′)]\nGreedy policy:      π(s) = argmaxₐ Σ_s′ P(s′|s,a)[R + γ V(s′)]',
      ex: [{ h: 'One value-iteration step by hand', p: ['State s has two actions. Action A: reward 1, leads to s′ with V(s′)=10. Action B: reward 5, leads to s″ with V(s″)=2. With γ=0.9 we back up both and take the max. Action A wins (10.0 > 6.8), so V(s) updates to 10.0 and the greedy policy at s becomes A — even though B\'s immediate reward is larger, because A leads somewhere far more valuable.'],
        eqn: 'Q(s,A) = 1 + 0.9·10 = 10.0\nQ(s,B) = 5 + 0.9·2  = 6.8\nV(s) ← max(10.0, 6.8) = 10.0    π(s) = A' }],
      code: 'import numpy as np\n\ndef value_iteration(P, R, gamma=0.9, theta=1e-6):\n    # P[s,a,s2] transition probs, R[s,a] rewards\n    nS, nA, _ = P.shape\n    V = np.zeros(nS)\n    while True:\n        delta = 0\n        for s in range(nS):\n            q = np.array([R[s,a] + gamma * P[s,a] @ V for a in range(nA)])\n            v_new = q.max()                 # Bellman optimality backup\n            delta = max(delta, abs(v_new - V[s]))\n            V[s] = v_new\n        if delta < theta:                   # converged (contraction)\n            break\n    policy = np.array([ (R[s] + gamma * P[s] @ V).argmax() for s in range(nS)])\n    return V, policy' },

    { h: 'Exploration vs exploitation & multi-armed bandits', p: [
      'Every RL agent faces a dilemma: <b>exploit</b> the action it currently believes is best, or <b>explore</b> others that might turn out better. Pure exploitation gets stuck on the first decent option; pure exploration never cashes in. The <b>multi-armed bandit</b> is the purest form of this trade-off — a single state, k actions ("arms"), each paying from an unknown reward distribution. Performance is measured by <b>regret</b>: the cumulative gap between the reward you got and the reward of the best arm in hindsight; good strategies achieve regret that grows only <b>logarithmically</b> in time.',
      'Classic strategies span a spectrum. <b>ε-greedy</b> exploits the best-known arm but picks randomly with probability ε. <b>Optimistic initialisation</b> seeds every value high so the agent is driven to try each arm at least once. <b>UCB</b> (Upper Confidence Bound) adds an uncertainty bonus, favouring arms that are either good or under-tried. <b>Thompson sampling</b> keeps a Bayesian posterior per arm and samples from it, exploring in proportion to the probability that an arm is best.'],
      eqn: 'Regret_T = Σ (t=1→T) [ μ* − μ(aₜ) ]        (want it sublinear in T)\nε-greedy:   aₜ = argmaxₐ Q(a)  w.p. 1−ε,  else random\nUCB1:       aₜ = argmaxₐ [ Q(a) + c·√( ln t / N(a) ) ]',
      table: { cols: ['Strategy', 'How it explores', 'Note'], rows: [
        ['ε-greedy', 'random with prob ε', 'simple; explores uniformly, even bad arms'],
        ['Optimistic init', 'high initial Q values', 'exploration fades once arms are tried'],
        ['UCB', 'uncertainty bonus √(ln t / N)', 'principled, log regret, needs counts'],
        ['Thompson sampling', 'sample from Bayesian posterior', 'strong in practice; naturally Bayesian']] },
      ex: [{ h: 'ε-greedy action selection', p: ['With ε = 0.1 the agent exploits its best estimate 90% of the time and explores randomly 10%. Decaying ε over training is common: explore hard early, exploit later once estimates are trustworthy.'],
        code: 'import numpy as np\n\ndef epsilon_greedy(Q, epsilon=0.1):\n    if np.random.rand() < epsilon:\n        return np.random.randint(len(Q))   # explore\n    return int(np.argmax(Q))               # exploit best-known' }] },

    { h: 'Monte-Carlo vs Temporal-Difference learning', p: [
      'When P and R are unknown, the agent must learn from experience. <b>Monte-Carlo (MC)</b> waits until an episode ends, computes the actual return G, and nudges each visited state\'s value toward it. MC is unbiased (it uses real returns) but high-variance and needs complete episodes. <b>Temporal-Difference (TD)</b> learning updates after <i>every step</i> using a bootstrapped estimate — it replaces the unknown future return with <code>r + γV(s′)</code>. The gap between the guess before and after the step is the <b>TD error</b> δ, the core learning signal in most modern RL.',
      'TD combines the best of DP (bootstrapping, online, no model) and MC (learns from raw experience). Its lower variance and step-by-step updates make it the workhorse; MC and TD are unified by <b>TD(λ)</b> and eligibility traces, which interpolate between the two.'],
      eqn: 'MC update:  V(s) ← V(s) + α [ Gₜ − V(s) ]\nTD(0):      V(s) ← V(s) + α [ r + γ V(s′) − V(s) ]\nTD error:   δ = r + γ V(s′) − V(s)',
      table: { cols: ['Aspect', 'Monte-Carlo', 'Temporal-Difference'], rows: [
        ['Update timing', 'end of episode', 'every step (online)'],
        ['Target', 'actual return Gₜ', 'bootstrapped r + γV(s′)'],
        ['Bias / variance', 'unbiased, high variance', 'biased, low variance'],
        ['Needs full episodes?', 'yes', 'no — works on continuing tasks']] },
      ex: [{ h: 'A single TD(0) update', p: ['V(s) currently 4.0. The agent takes a step, gets reward 2, and lands in s′ with V(s′)=5.0. With γ=0.9, α=0.1 the TD target is 2 + 0.9·5 = 6.5, the TD error is 2.5, and V(s) moves a fraction of that gap toward the target: 4.0 + 0.1·2.5 = 4.25.'],
        eqn: 'target = 2 + 0.9·5.0 = 6.5\nδ = 6.5 − 4.0 = 2.5\nV(s) ← 4.0 + 0.1·2.5 = 4.25' }] },

    { h: 'Q-learning (off-policy) vs SARSA (on-policy)', p: [
      'Two tabular TD control algorithms learn Q directly. <b>SARSA</b> is <b>on-policy</b>: it updates toward the Q-value of the action the policy <i>actually</i> takes next (the tuple State-Action-Reward-State-Action gives it its name). It learns the value of the policy it follows, exploration included, so it tends to be cautious. <b>Q-learning</b> is <b>off-policy</b>: it updates toward the <b>max</b> over next actions — the value of the <i>greedy</i> next action — regardless of what the exploratory policy did. So it learns the optimal policy while behaving with an exploratory one.',
      'The single-symbol difference — <code>max_a′ Q(s′,a′)</code> versus <code>Q(s′, a′)</code> for the chosen a′ — produces the classic split: on a cliff-walk, Q-learning finds the optimal risky path along the edge, while SARSA, accounting for the exploration that occasionally pushes it off, learns a safer detour.'],
      eqn: 'SARSA (on-policy):\n  Q(s,a) ← Q(s,a) + α [ r + γ Q(s′, a′) − Q(s,a) ]\n\nQ-learning (off-policy):\n  Q(s,a) ← Q(s,a) + α [ r + γ max_a′ Q(s′, a′) − Q(s,a) ]',
      ex: [{ h: 'Same transition, different targets', p: ['State s′ has Q(s′,·) = [1.0, 8.0]. ε-greedy exploration happens to pick action 0 next (value 1.0). SARSA bootstraps off that chosen action; Q-learning bootstraps off the max (8.0). With r=0, γ=0.9 the targets differ sharply — SARSA sees 0.9, Q-learning sees 7.2 — which is exactly why Q-learning converges to the optimal policy and SARSA to the safe on-policy one.'],
        eqn: 'SARSA target      = 0 + 0.9·Q(s′, a′=0) = 0.9\nQ-learning target = 0 + 0.9·max Q(s′, ·) = 7.2' }],
      code: 'import numpy as np\n\ndef q_learning(env, episodes=500, alpha=0.1, gamma=0.99, epsilon=0.1):\n    Q = np.zeros((env.n_states, env.n_actions))\n    for _ in range(episodes):\n        s = env.reset()\n        done = False\n        while not done:\n            # epsilon-greedy behaviour policy\n            a = (np.random.randint(env.n_actions) if np.random.rand() < epsilon\n                 else int(np.argmax(Q[s])))\n            s2, r, done, _ = env.step(a)\n            # off-policy update: bootstrap off the GREEDY next action\n            td_target = r + gamma * np.max(Q[s2]) * (not done)\n            Q[s, a] += alpha * (td_target - Q[s, a])\n            s = s2\n    return Q' },

    { h: 'Function approximation & Deep Q-Networks (DQN)', p: [
      'A lookup table for Q fails when states are images or high-dimensional continuous vectors — there are too many, and no generalisation between similar states. <b>Function approximation</b> replaces the table with a parametric model Q(s,a; θ) — a neural network — trained to minimise the squared TD error. But naively bootstrapping a network off itself is unstable: correlated samples and a moving target cause divergence.',
      '<b>Deep Q-Networks</b> (DQN, which cracked Atari from pixels) add two stabilisers. <b>Experience replay</b> stores transitions in a buffer and trains on random minibatches, breaking temporal correlation and reusing data. A <b>target network</b> — a slowly-updated copy θ⁻ used to compute the bootstrap target — keeps the target fixed for many steps so the network is not chasing a value that moves every gradient step. Extensions include Double DQN (decouple action-selection from evaluation to fight overestimation), Dueling DQN (separate V and advantage streams), and Prioritized Replay.'],
      eqn: 'Loss(θ) = E_(s,a,r,s′)~D [ ( r + γ max_a′ Q(s′,a′; θ⁻) − Q(s,a; θ) )² ]\n        ↑ target uses frozen θ⁻ ;  D = replay buffer',
      terms: [['Experience replay', 'sample past transitions randomly to decorrelate updates.'], ['Target network θ⁻', 'a periodically-synced copy that stabilises the bootstrap target.'], ['Double DQN', 'select the argmax with θ, evaluate it with θ⁻ to reduce overestimation.'], ['Dueling', 'split the head into V(s) and A(s,a).']],
      ex: [{ h: 'One DQN gradient step', p: ['Sample a minibatch from replay, compute targets with the frozen target network, and take one gradient step on the online network. Every C steps the target network is refreshed to the online weights. This decoupling is what turned unstable Q-learning-with-a-net into something that reliably learns from raw pixels.'],
        code: 'batch = replay.sample(32)                        # decorrelated minibatch\ns, a, r, s2, done = batch\nwith torch.no_grad():\n    target = r + gamma * q_target(s2).max(1).values * (1 - done)\npred = q_online(s).gather(1, a.unsqueeze(1)).squeeze(1)\nloss = F.smooth_l1_loss(pred, target)            # Huber TD loss\noptimizer.zero_grad(); loss.backward(); optimizer.step()\nif step % C == 0:\n    q_target.load_state_dict(q_online.state_dict())  # sync target' }] },

    { h: 'Policy-gradient methods, actor-critic, A2C/A3C, PPO', p: [
      'Value-based methods learn Q and act greedily; <b>policy-gradient</b> methods instead parameterise the policy πθ(a|s) directly and push its parameters up the gradient of expected return. This shines for <b>continuous or high-dimensional action spaces</b> and can learn genuinely <b>stochastic</b> policies. The <b>policy-gradient theorem</b> gives a gradient that does not require differentiating the environment, via the <b>log-likelihood (score-function) trick</b>: scale the gradient of the log-probability of each action by the return it earned. <b>REINFORCE</b> is the Monte-Carlo version — good actions (high return) get their probability raised, bad ones lowered.',
      'Raw REINFORCE is high-variance, so we subtract a <b>baseline</b> (typically V(s)), which turns the weight into the <b>advantage</b> A(s,a) without adding bias. Learning V alongside π gives <b>actor-critic</b>: the <i>actor</i> πθ chooses actions, the <i>critic</i> Vw evaluates them via the TD error. <b>A2C/A3C</b> run many parallel actors to decorrelate data (A3C asynchronously, A2C synchronously). <b>PPO</b> is today\'s default: it maximises a <b>clipped</b> surrogate objective that limits how far the policy moves in one update — capturing the stability of a trust region cheaply, which is why it is robust and easy to tune.'],
      eqn: 'Policy-gradient theorem:\n  ∇θ J(θ) = E[ ∇θ log πθ(a|s) · Qπ(s,a) ]\nREINFORCE:  ∇θ J ≈ Σₜ ∇θ log πθ(aₜ|sₜ) · Gₜ\nWith baseline (advantage):  Aₜ = Gₜ − V(sₜ)\nActor-critic TD error:  δ = r + γ V(s′) − V(s)\n\nPPO clipped objective (rₜ(θ) = πθ / π_old):\n  L = E[ min( rₜ(θ)·Aₜ ,  clip(rₜ(θ), 1−ε, 1+ε)·Aₜ ) ]',
      table: { cols: ['Method', 'What it adds', 'Trait'], rows: [
        ['REINFORCE', 'MC policy gradient', 'unbiased, very high variance'],
        ['+ baseline', 'subtract V(s) → advantage', 'lower variance, same expectation'],
        ['Actor-critic', 'learned critic, TD updates', 'online, lower variance'],
        ['A2C / A3C', 'parallel actors', 'decorrelated, scalable'],
        ['PPO', 'clipped surrogate objective', 'stable, robust — the default']] },
      ex: [{ h: 'A REINFORCE update step', p: ['Run an episode, compute the discounted return at each step, and take a gradient step that raises log πθ(aₜ|sₜ) weighted by that return (minus a baseline). Actions from high-return trajectories become more likely. The negative sign turns gradient ascent on return into gradient descent on a loss.'],
        code: 'logps, rewards = [], []\nstate = env.reset(); done = False\nwhile not done:                       # collect one episode\n    probs = policy(state)             # πθ(·|s)\n    a = torch.distributions.Categorical(probs).sample()\n    logps.append(torch.log(probs[a]))\n    state, r, done, _ = env.step(a.item()); rewards.append(r)\n\nG, returns = 0.0, []\nfor r in reversed(rewards):           # discounted returns\n    G = r + 0.99 * G; returns.insert(0, G)\nreturns = torch.tensor(returns)\nreturns = (returns - returns.mean()) / (returns.std() + 1e-8)  # baseline\nloss = -(torch.stack(logps) * returns).sum()   # ascend log π · G\nopt.zero_grad(); loss.backward(); opt.step()' }],
      note: 'PPO\'s clip keeps the new policy within a small trust region of the old one — the practical reason it rarely blows up, and why it was chosen for RLHF.' },

    { h: 'Reward shaping, sparse rewards & RLHF for LLMs', p: [
      'RL\'s hardest practical problem is the reward itself. Many real tasks have <b>sparse rewards</b> — a single +1 at the goal and nothing along the way — so the agent almost never stumbles onto signal. <b>Reward shaping</b> adds intermediate rewards to guide learning, but naive shaping can be gamed (the agent optimises the proxy, not the goal). <b>Potential-based shaping</b>, F = γΦ(s′) − Φ(s), is the safe form: it provably leaves the optimal policy unchanged while still densifying the signal. Related remedies include curiosity/intrinsic motivation and curriculum learning.',
      '<b>RLHF</b> (Reinforcement Learning from Human Feedback) is how RL aligns large language models — and where these ideas met the mainstream. The reward is not hand-coded but <b>learned</b> from human preferences. First, humans rank pairs of model outputs; a <b>reward model</b> rφ is trained (Bradley-Terry loss) to score responses so preferred ones score higher. Then the LLM policy is fine-tuned with <b>PPO</b> to maximise that learned reward, with a <b>KL penalty</b> to the original supervised model so it improves helpfulness/harmlessness without drifting into gibberish that games the reward. Variants like DPO skip the explicit RL loop by optimising the preference objective directly.'],
      eqn: 'Potential-based shaping (policy-invariant):\n  F(s, s′) = γ Φ(s′) − Φ(s)\n\nRLHF reward-model loss (Bradley-Terry on preference y_w ≻ y_l):\n  L(φ) = − E[ log σ( rφ(x, y_w) − rφ(x, y_l) ) ]\n\nRLHF PPO objective (with KL anchor to the SFT model):\n  max_θ  E[ rφ(x, y) − β · KL( πθ(y|x) ‖ π_SFT(y|x) ) ]',
      terms: [['Sparse reward', 'signal only at success — hard to learn from.'], ['Reward shaping', 'add intermediate rewards to guide the agent.'], ['Reward hacking', 'exploiting a flawed reward to score without solving the task.'], ['Reward model', 'a network trained to predict human preference scores.'], ['KL penalty β', 'keeps the tuned policy close to the base model.']],
      ex: [{ h: 'Why the KL anchor matters in RLHF', p: ['Without the KL term, PPO will push the LLM toward whatever text maximises the reward model — often degenerate, repetitive, or manipulative outputs that exploit blind spots in rφ (reward hacking). The KL penalty pins the policy near the trusted supervised model, so it climbs the reward only where doing so still looks like fluent, on-distribution language. β trades alignment gain against how far the model may drift.'],
        eqn: 'reward_per_token = rφ(x, y) − β · [ log πθ(y|x) − log π_SFT(y|x) ]' }],
      note: 'The same PPO algorithm that plays games and controls robots is what turns a raw next-token predictor into a helpful assistant — a striking example of one RL idea spanning very different domains.' },

    { h: 'Applications & challenges', p: [
      'RL has produced landmark results: superhuman play in <b>games</b> (TD-Gammon, DQN on Atari, AlphaGo/AlphaZero, and multi-agent systems in StarCraft II and Dota 2), <b>robotics</b> (locomotion, dexterous manipulation, sim-to-real transfer), <b>control and operations</b> (data-centre cooling, chip floorplanning, inventory and traffic control), recommendation, and — via RLHF — the alignment of large language models. The common thread is <b>sequential decision-making under a long-horizon objective</b> that is hard to specify with labels.',
      'The open challenges are equally real. <b>Sample efficiency</b>: model-free RL can need millions of interactions, impractical when each real-world step is slow or costly (motivating model-based RL and offline RL). <b>Stability and reproducibility</b>: deep RL is notoriously sensitive to seeds, hyperparameters and implementation details. <b>Exploration</b> in sparse, high-dimensional spaces remains hard. <b>Reward specification</b> is a safety problem — misspecified rewards get hacked. And <b>generalisation</b> beyond the training environment, plus safe exploration in the real world, are still frontier problems.'],
      table: { cols: ['Challenge', 'Why it is hard', 'Direction'], rows: [
        ['Sample efficiency', 'millions of steps needed', 'model-based, offline RL, replay'],
        ['Stability', 'sensitive to seeds/hyperparams', 'PPO, target nets, careful tuning'],
        ['Exploration', 'sparse rewards, huge spaces', 'curiosity, shaping, curricula'],
        ['Reward design', 'proxies get hacked', 'potential-based shaping, RLHF, oversight'],
        ['Generalisation', 'overfits one environment', 'domain randomisation, meta-RL']] },
      note: 'A useful mental model: supervised learning imitates a fixed dataset; RL optimises an objective by generating its own data — more powerful and more general, but far harder to make stable, sample-efficient and safe.' },
  ]
});
