/* Deep dive — Time-series analysis & forecasting */
window.AtlasRef && window.AtlasRef.register('timeseries', {
  color: '#34D399',
  title: 'Forecasting: learning from the order of things',
  lead: 'A time series is data indexed by time, and time changes everything. Order is information, neighbouring points are correlated, and the future must never leak into the past. This is the full course — decomposition, stationarity, ACF/PACF, ARIMA and SARIMA, exponential smoothing, Prophet, machine-learning and deep-learning forecasters, honest backtesting, and uncertainty — each with intuition, exact formulas, worked examples and code.',
  sections: [

    { h: 'What makes time-series data special', p: [
      'In ordinary tabular learning the rows are assumed <b>independent and identically distributed</b> and their order is meaningless — you can shuffle them freely. A time series breaks both assumptions. The index carries meaning: yesterday causes today, and a value is strongly correlated with its own recent past (<b>autocorrelation</b>). The single most important consequence is a hard rule: <b>never shuffle, and never let the future inform the past.</b>',
      'That rule reshapes everything downstream. You cannot use a random train/test split — the test set must be strictly <i>later</i> in time than the training set, or you get <b>look-ahead leakage</b> and wildly optimistic scores. Cross-validation becomes <b>rolling-origin</b> backtesting. Feature engineering must only reference <i>past</i> values (lags, trailing rolling stats). Even scaling parameters must be fit on the training window alone.',
      'Time series also exhibit structure that i.i.d. data does not: <b>trend</b> (long-run drift), <b>seasonality</b> (fixed-period cycles like weekly or yearly), <b>cyclicity</b> (non-fixed booms and busts), and changing variance (<b>heteroskedasticity</b>). Modelling well means naming and separating these forces.'],
      terms: [['Autocorrelation', 'correlation of a series with a lagged copy of itself.'], ['Stationarity', 'statistical properties (mean, variance, autocorrelation) do not change over time.'], ['Lag', 'a value shifted back k steps, <code>y(t−k)</code>.'], ['Look-ahead leakage', 'accidentally using future information when predicting the past — the cardinal sin.'], ['Horizon', 'how many steps ahead you forecast (h).'], ['Frequency', 'the sampling interval — hourly, daily, monthly.']],
      ex: [{ h: 'Why shuffling destroys the signal', p: ['If you random-split a series, a point from June ends up training a model tested on May. The model has effectively <i>seen the future</i>. Below, the correct split keeps time intact — everything before a cutoff trains, everything after tests.'],
        code: 'import pandas as pd\ny = pd.Series(sales, index=pd.date_range("2020-01-01", periods=len(sales), freq="D"))\n\n# WRONG: random split leaks the future\n# train, test = train_test_split(y, shuffle=True)   # never do this\n\n# RIGHT: chronological split\ncutoff = "2023-01-01"\ntrain = y[:cutoff]\ntest  = y[cutoff:]' }],
      note: 'A useful mantra: for time series, the validation scheme is a bigger source of error than the model choice. Get the split right first.' },

    { h: 'The four components: trend, seasonality, cyclicity, residual', p: [
      'Classical analysis views an observed series <code>y(t)</code> as a sum (or product) of unobserved components. <b>Trend (T)</b> is the smooth long-run direction — population growth, adoption curves. <b>Seasonality (S)</b> is a pattern that repeats over a <i>fixed, known</i> period: 7 days, 12 months, 24 hours. <b>Cyclicity (C)</b> also repeats but over a <i>variable, unknown</i> duration — business cycles lasting several years with no fixed length. <b>Residual / irregular (R)</b> is what is left: noise, shocks, and anything unexplained.',
      'The distinction between seasonality and cyclicity matters for modelling. Seasonality has a fixed frequency you can encode directly (month-of-year, day-of-week dummies or Fourier terms). Cyclicity has no fixed frequency, so it is usually folded into the trend or captured by autoregressive dynamics rather than a seasonal term.'],
      terms: [['Trend', 'monotone or smooth long-run movement.'], ['Seasonality', 'fixed-period repetition (period m known in advance).'], ['Cyclicity', 'wave-like movement of variable, unknown period.'], ['Residual', 'the unexplained remainder after removing T, S, C.'], ['Level', 'the local baseline value of the series at time t.']],
      ex: [{ h: 'Spotting the components', p: ['Monthly airline passengers rise year over year (trend), peak every summer (seasonality of period 12), and the peaks grow taller as the level rises — a sign the seasonal effect is <i>proportional</i> to the level, which points to a multiplicative model rather than additive.'] }],
      note: 'A quick diagnostic: if the seasonal swings stay the same absolute size as the series grows, use additive; if they grow with the level, use multiplicative (or log-transform first).' },

    { h: 'Additive vs multiplicative decomposition', p: [
      'Decomposition writes the series as a combination of the components. In the <b>additive</b> model the parts add; the seasonal amplitude is constant. In the <b>multiplicative</b> model they multiply; the seasonal and residual effects scale with the level. Taking logs of a multiplicative series turns it additive, which is why a log transform is such a common first step.',
      'Classical decomposition estimates the trend with a centred moving average of length equal to the seasonal period, subtracts (or divides) it out, then averages the detrended values by season to get the seasonal indices. <b>STL</b> (Seasonal-Trend decomposition using Loess) is the modern, robust alternative: it handles any seasonal period, lets seasonality evolve slowly, and resists outliers.'],
      eqn: 'Additive:        y(t) = T(t) + S(t) + R(t)\nMultiplicative:  y(t) = T(t) × S(t) × R(t)\nlog of multiplicative:  log y = log T + log S + log R   (now additive)',
      ex: [{ h: 'Decomposing with statsmodels', p: ['Given monthly data with yearly seasonality, choose the model from the diagnostic above, then read off the three component series. STL is preferred when seasonality drifts or outliers are present.'],
        code: 'from statsmodels.tsa.seasonal import seasonal_decompose, STL\n\n# classical, choose model="additive" or "multiplicative"\nres = seasonal_decompose(y, model="multiplicative", period=12)\nres.trend; res.seasonal; res.resid\nres.plot()\n\n# robust modern alternative\nstl = STL(y, period=12, robust=True).fit()\ntrend, seasonal, resid = stl.trend, stl.seasonal, stl.resid' }],
      note: 'Multiplicative decomposition is undefined when the series can be zero or negative — log-then-additive or STL on the raw scale sidesteps that.' },

    { h: 'Stationarity and why it matters', p: [
      'A series is <b>(weakly) stationary</b> when its mean, variance, and autocorrelation structure do not depend on time — statistically, the window you look through does not matter. Most classical forecasting theory (AR, MA, ARMA) is built on this assumption: if the rules of the game keep changing, a model fit on the past cannot generalise to the future.',
      'Real series are usually <i>non-stationary</i>: they trend, their variance grows, or their seasonality shifts. The strategy is to <b>transform the series into a stationary one</b> (by differencing and/or a variance-stabilising transform), model the stationary version, then invert the transforms to forecast on the original scale. The <code>d</code> in ARIMA(p,<b>d</b>,q) is exactly the number of differences needed.'],
      terms: [['Strict stationarity', 'the full joint distribution is time-invariant (rarely needed).'], ['Weak stationarity', 'constant mean and variance, autocovariance depends only on lag — the practical target.'], ['Unit root', 'a stochastic trend (random walk) that makes a series non-stationary and requires differencing.'], ['Trend-stationary', 'stationary after removing a deterministic trend, not after differencing.']],
      ex: [{ h: 'Visual and statistical checks', p: ['Plot the series and a rolling mean/variance — drifting statistics signal non-stationarity. Confirm with a hypothesis test (ADF below). A slowly-decaying ACF is another classic tell of a unit root.'],
        code: 'roll = y.rolling(12)\nax = y.plot()\nroll.mean().plot(ax=ax); roll.std().plot(ax=ax)\n# drifting mean/variance => not stationary => difference it' }],
      note: 'Stationarity is about the generating process, not any single realisation. Differencing removes stochastic trends; a log or Box-Cox stabilises a variance that grows with the level.' },

    { h: 'The Augmented Dickey-Fuller (ADF) test', p: [
      'The ADF test checks formally for a <b>unit root</b> (a stochastic trend). It regresses the change Δy(t) on the previous level y(t−1) plus lagged changes to soak up short-run autocorrelation, and asks whether the coefficient γ on y(t−1) is significantly negative. The hypotheses are: <b>H₀ = there is a unit root (non-stationary)</b>; <b>H₁ = the series is stationary</b>.',
      'Read it by the <b>p-value</b>: if p ≤ 0.05 you <i>reject</i> H₀ and conclude stationary; if p &gt; 0.05 you fail to reject and should difference the series and test again. The KPSS test flips the null (H₀ = stationary) and is a useful cross-check — the two together disambiguate trend-stationary from difference-stationary.'],
      eqn: 'Δy(t) = α + βt + γ·y(t−1) + Σᵢ δᵢ·Δy(t−i) + ε(t)\ntest statistic on γ ;  reject unit root (=> stationary) when p ≤ 0.05',
      ex: [{ h: 'Running ADF and acting on it', p: ['A raw sales series returns p ≈ 0.42 — non-stationary, do not model yet. After one difference, p ≈ 0.01 — stationary, so <code>d = 1</code>. This is the practical way to choose the differencing order.'],
        code: 'from statsmodels.tsa.stattools import adfuller\n\ndef adf(series):\n    stat, p, *_ = adfuller(series.dropna())\n    print(f"ADF stat={stat:.3f}  p={p:.3f}  -> "\n          f"{\'stationary\' if p <= 0.05 else \'NON-stationary\'}")\n\nadf(y)            # p=0.42  -> NON-stationary\nadf(y.diff())     # p=0.01  -> stationary, so d=1' }],
      note: 'ADF has low power on short or highly seasonal series. Difference out seasonality first, and treat borderline p-values with caution — combine with ACF inspection and KPSS.' },

    { h: 'Autocorrelation (ACF) and partial autocorrelation (PACF)', p: [
      'The <b>ACF</b> at lag k is the correlation between y(t) and y(t−k). It captures both direct and indirect links — if today depends on yesterday and yesterday on the day before, the ACF at lag 2 is inflated by that chain. The <b>PACF</b> at lag k strips out the intermediate lags, giving the <i>direct</i> correlation between y(t) and y(t−k) after controlling for lags 1…k−1.',
      'These two plots are how you read a model order off the data — the Box-Jenkins method. The signatures: a <b>pure AR(p)</b> process has a PACF that cuts off sharply after lag p and an ACF that decays gradually; a <b>pure MA(q)</b> process is the mirror image — ACF cuts off after lag q, PACF decays. A mixed ARMA shows gradual decay in both. Spikes at seasonal lags (12, 24 for monthly) reveal seasonal terms.'],
      table: { cols: ['Pattern', 'ACF', 'PACF', 'Suggests'], rows: [
        ['AR(p)', 'tails off (decays)', 'cuts off after lag p', 'AR order p'],
        ['MA(q)', 'cuts off after lag q', 'tails off (decays)', 'MA order q'],
        ['ARMA(p,q)', 'tails off', 'tails off', 'try small p and q'],
        ['Seasonal', 'spike at lag m, 2m…', 'spike at lag m', 'seasonal P/Q at period m'],
        ['Unit root', 'very slow linear decay', 'large spike near 1 at lag 1', 'difference (raise d)']] },
      ex: [{ h: 'Plotting ACF/PACF to pick orders', p: ['Blue bands are the ~95% confidence limits (±1.96/√n); spikes poking outside them are significant. Suppose the differenced series shows a PACF significant only at lag 1 and an ACF that decays — that is the AR(1) signature, so <code>p=1, q=0</code>.'],
        code: 'from statsmodels.graphics.tsaplots import plot_acf, plot_pacf\n\nd1 = y.diff().dropna()\nplot_acf(d1,  lags=36)   # MA signature: where does ACF cut off?\nplot_pacf(d1, lags=36)   # AR signature: where does PACF cut off?' }],
      note: 'Read ACF/PACF on the <i>differenced, stationary</i> series, not the raw one — otherwise the trend swamps every lag and both plots look uninformative.' },

    { h: 'Differencing and variance-stabilising transforms', p: [
      'To reach stationarity you attack the mean and the variance separately. <b>Differencing</b> removes trend by modelling changes instead of levels: first difference Δy(t) = y(t) − y(t−1). A second difference removes a linear trend in the change itself (rarely need more than d=2). <b>Seasonal differencing</b> Δₘy(t) = y(t) − y(t−m) removes a repeating seasonal pattern of period m.',
      'To tame a variance that grows with the level, apply a <b>transform first</b>. The <b>log</b> turns multiplicative structure additive and compresses large values. The <b>Box-Cox</b> family generalises it with a parameter λ chosen to best stabilise variance (λ=0 recovers the log; λ=1 leaves it unchanged). Always remember to <b>invert</b> the transform (exponentiate, inverse-Box-Cox) when producing final forecasts.'],
      eqn: 'First difference:     Δy(t) = y(t) − y(t−1)\nSeasonal difference:  Δₘy(t) = y(t) − y(t−m)\nBox-Cox:  w(t) = (y(t)^λ − 1)/λ  (λ≠0),   w(t) = log y(t)  (λ=0)',
      ex: [{ h: 'Order of operations to stationarity', p: ['For monthly airline data: (1) log to flatten the growing seasonal swings, (2) seasonal-difference at lag 12 to kill the yearly cycle, (3) first-difference to remove the remaining trend, (4) ADF-test to confirm. That sequence gives <code>d=1, D=1, m=12</code> for a SARIMA model.'],
        code: 'import numpy as np\nfrom scipy.stats import boxcox\n\nlogy = np.log(y)                 # variance stabilise\nstat = logy.diff(12).diff().dropna()   # seasonal + first difference\n\n# or let Box-Cox pick lambda automatically\nz, lam = boxcox(y.values)\nprint("optimal lambda:", round(lam, 3))' }],
      note: 'Under-differencing leaves a trend the model cannot handle; over-differencing injects artificial negative autocorrelation and inflates variance. Prefer the smallest d that passes the ADF test.' },

    { h: 'Smoothing: moving averages and exponential smoothing', p: [
      'Smoothing suppresses noise to reveal the signal and, for the exponential family, to forecast. A <b>simple moving average (SMA)</b> averages the last k observations with equal weight — easy but laggy and equally trusting of stale data. A <b>weighted moving average (WMA)</b> gives recent points more weight. <b>Exponential smoothing</b> takes that idea to its limit: weights decay geometrically into the past, controlled by a smoothing parameter α ∈ (0,1).',
      '<b>Simple exponential smoothing (SES)</b> tracks only a level and suits data with no trend or seasonality. <b>Holt’s linear</b> method adds a trend component (a second smoothing parameter β). <b>Holt-Winters</b> adds seasonality (a third parameter γ) and comes in additive and multiplicative flavours — the workhorse for seasonal business series. These are the components later formalised as ETS state-space models.'],
      eqn: 'SES:    ℓ(t) = α·y(t) + (1−α)·ℓ(t−1),      ŷ(t+1) = ℓ(t)\nHolt:   ℓ(t) = α·y(t) + (1−α)(ℓ(t−1)+b(t−1))\n        b(t) = β·(ℓ(t)−ℓ(t−1)) + (1−β)·b(t−1),   ŷ(t+h) = ℓ(t) + h·b(t)\nHolt-Winters (additive):  ŷ(t+h) = ℓ(t) + h·b(t) + s(t+h−m)',
      table: { cols: ['Method', 'Handles', 'Params'], rows: [
        ['SMA / WMA', 'noise only (no forecast of trend)', 'window k (+ weights)'],
        ['SES', 'level', 'α'],
        ['Holt', 'level + trend', 'α, β'],
        ['Holt-Winters', 'level + trend + seasonality', 'α, β, γ']] },
      ex: [{ h: 'Holt-Winters on seasonal sales', p: ['With growing yearly seasonality use the multiplicative seasonal form (or log then additive). The fitted model both smooths history and projects h steps ahead, seasonality included.'],
        code: 'from statsmodels.tsa.holtwinters import ExponentialSmoothing\n\nmodel = ExponentialSmoothing(\n    y, trend="add", seasonal="mul", seasonal_periods=12\n).fit()                      # estimates alpha, beta, gamma by MLE\nfc = model.forecast(12)      # next 12 months, seasonality included' }],
      note: 'A larger α reacts faster to recent change but is jumpier; a smaller α is smoother but slower to adapt. statsmodels can optimise α, β, γ for you by minimising in-sample error.' },

    { h: 'AR, MA, ARMA, ARIMA and SARIMA', p: [
      'These build up the classic Box-Jenkins family on a stationary series. An <b>AR(p)</b> (autoregressive) model predicts y(t) from a linear combination of its own p past values — memory of past <i>levels</i>. An <b>MA(q)</b> (moving average) model predicts from the last q forecast <i>errors</i> — memory of past <i>shocks</i>. <b>ARMA(p,q)</b> combines both on a stationary series.',
      '<b>ARIMA(p,d,q)</b> = "Integrated" ARMA: it first differences the series <code>d</code> times to make it stationary, then fits ARMA(p,q) to the differences. So <b>p</b> = AR terms, <b>d</b> = differences, <b>q</b> = MA terms. <b>SARIMA(p,d,q)(P,D,Q)ₘ</b> adds a seasonal copy of each term operating at the seasonal period m — capital P, D, Q are the seasonal AR, seasonal differencing, and seasonal MA orders. A monthly series with yearly seasonality uses m=12.'],
      eqn: 'AR(p):    y(t) = c + φ₁y(t−1) + … + φₚy(t−p) + ε(t)\nMA(q):    y(t) = c + ε(t) + θ₁ε(t−1) + … + θ_q ε(t−q)\nARIMA(p,d,q):  apply AR(p)+MA(q) to the d-times-differenced series\nSARIMA(p,d,q)(P,D,Q)ₘ:  plus seasonal terms at period m',
      table: { cols: ['Term', 'Meaning', 'Chosen from'], rows: [
        ['p', 'non-seasonal AR order', 'PACF cut-off of the differenced series'],
        ['d', 'non-seasonal differencing', 'ADF test / number of diffs to stationarity'],
        ['q', 'non-seasonal MA order', 'ACF cut-off of the differenced series'],
        ['P,D,Q', 'seasonal AR, diff, MA', 'ACF/PACF spikes at seasonal lags'],
        ['m', 'seasonal period', 'domain knowledge (12 monthly, 7 daily…)']] },
      ex: [{ h: 'Choosing p, d, q from ACF/PACF — worked', p: ['A monthly series is non-stationary (ADF p=0.40). After one difference ADF p=0.01, so <b>d=1</b>. On the differenced series the PACF has one significant spike at lag 1 then nothing (AR signature ⇒ <b>p=1</b>) and the ACF decays gradually (no sharp MA cut-off ⇒ <b>q=0</b>). Candidate: ARIMA(1,1,0). Confirm by fitting neighbours and comparing AIC; check residuals are white noise (Ljung-Box p &gt; 0.05).'],
        eqn: 'ADF(raw) p=0.40 -> d=1 ;  PACF cuts at 1 -> p=1 ;  ACF tails off -> q=0\n=> ARIMA(1,1,0),  verify by lowest AIC and white-noise residuals' }],
      note: 'Manual order selection teaches the intuition; in practice pmdarima’s auto_arima searches p,d,q,P,D,Q by AIC. Always finish by checking residuals look like white noise.' },

    { h: 'Fitting ARIMA/SARIMA in code', p: [
      'statsmodels <code>SARIMAX</code> fits the whole family (and lets you add exogenous regressors, the "X"). Give it the raw series and the chosen orders; it handles the differencing internally, so forecasts come back on the original scale. Inspect <code>summary()</code> for coefficient significance and AIC, and run diagnostics on the residuals before trusting any forecast.',
      'For automatic order selection, <code>pmdarima.auto_arima</code> steps through candidate orders and returns the lowest-AIC model — a strong baseline, though a hand-checked model informed by ACF/PACF is often more robust.'],
      ex: [{ h: 'A full SARIMA fit with forecast intervals', p: ['Fit SARIMA(1,1,0)(0,1,1)₁₂ to monthly data, forecast 12 months, and extract the 95% prediction interval — never ship a point forecast without one.'],
        code: 'from statsmodels.tsa.statespace.sarimax import SARIMAX\n\nmodel = SARIMAX(y, order=(1,1,0), seasonal_order=(0,1,1,12),\n                enforce_stationarity=False).fit(disp=False)\nprint(model.summary())            # coefficients, AIC\n\nfc = model.get_forecast(steps=12)\nmean = fc.predicted_mean\nci   = fc.conf_int(alpha=0.05)     # 95% prediction interval\n\n# residual diagnostics: want white noise (p > 0.05)\nfrom statsmodels.stats.diagnostic import acorr_ljungbox\nacorr_ljungbox(model.resid, lags=[12], return_df=True)' }],
      code: 'import pmdarima as pm\nauto = pm.auto_arima(y, seasonal=True, m=12,\n                     stepwise=True, information_criterion="aic",\n                     suppress_warnings=True)\nprint(auto.order, auto.seasonal_order)   # e.g. (1,1,0) (0,1,1,12)\nfc, ci = auto.predict(n_periods=12, return_conf_int=True)',
      note: 'The Ljung-Box test on residuals checks for leftover autocorrelation: a p-value above 0.05 means the model has captured the structure and residuals resemble white noise.' },

    { h: 'ETS and state-space models', p: [
      '<b>ETS</b> stands for <b>Error, Trend, Seasonal</b> — a principled taxonomy of exponential-smoothing methods cast as state-space models. Each component can be None (N), Additive (A), or Multiplicative (M), and the error can be additive or multiplicative. So ETS(A,A,A) is additive Holt-Winters; ETS(M,A,M) has multiplicative error and seasonality. Writing them as state-space models yields likelihoods (for AIC-based selection) and genuine prediction intervals.',
      'ETS and ARIMA are complementary rather than rival: ETS is organised around unobserved <i>components</i> (level, trend, season) evolving over time, while ARIMA is organised around <i>autocorrelation</i> of a stationary series. Many ETS models have an ARIMA equivalent and vice versa. A common workflow fits both and picks the lower cross-validated error.'],
      terms: [['Error (E)', 'A or M — is noise additive or proportional to level.'], ['Trend (T)', 'N, A, or Ad (damped additive) — long-run slope, optionally damped.'], ['Seasonal (S)', 'N, A, or M — fixed-period pattern, additive or multiplicative.'], ['Damped trend', 'trend that flattens over the horizon — often more accurate for long h.'], ['State-space form', 'level/trend/season as hidden states updated each step, giving likelihoods and intervals.']],
      ex: [{ h: 'Automatic ETS selection', p: ['statsmodels can pick the best ETS configuration by AIC. A damped additive trend (<code>damped_trend=True</code>) usually beats an undamped one on longer horizons because real trends rarely continue forever.'],
        code: 'from statsmodels.tsa.exponential_smoothing.ets import ETSModel\n\nmodel = ETSModel(y, error="add", trend="add", damped_trend=True,\n                 seasonal="mul", seasonal_periods=12).fit()\nfc = model.get_prediction(start=len(y), end=len(y)+11)\nfc.summary_frame(alpha=0.05)   # mean + prediction interval' }],
      note: 'Rule of thumb: multiplicative seasonality/error for series that are strictly positive and whose swings grow with the level; additive for series that can be near zero or have constant-size swings.' },

    { h: 'Prophet: decomposable trend + seasonality + holidays', p: [
      'Prophet (from Meta) fits an <b>additive decomposable model</b>: y(t) = g(t) + s(t) + h(t) + ε. The <b>trend g(t)</b> is a piecewise-linear (or logistic-saturating) curve with automatically detected <b>changepoints</b>. The <b>seasonality s(t)</b> is modelled with Fourier series, so you can superimpose yearly, weekly, and daily cycles. The <b>holidays h(t)</b> term lets you inject known irregular events (Black Friday, Eid, elections) with their own effect windows.',
      'Its strengths are usability and robustness: it tolerates missing data and outliers, handles multiple seasonalities out of the box, needs little tuning, and its components are interpretable. It shines on daily business series with strong human-calendar effects. It is less suited to short series, high-frequency data with sharp autocorrelation, or where an ARIMA-style error model matters.'],
      eqn: 'y(t) = g(t) + s(t) + h(t) + ε(t)\ng(t): piecewise-linear/logistic trend with changepoints\ns(t): Σ Fourier terms (yearly, weekly, daily)\nh(t): holiday/event effects',
      ex: [{ h: 'Forecasting with holidays', p: ['Prophet expects a dataframe with columns <code>ds</code> (date) and <code>y</code> (value). Add country holidays or a custom events table, fit, and forecast a future frame — you get the forecast plus per-component contributions and an uncertainty band.'],
        code: 'from prophet import Prophet\n\ndf = y.rename_axis("ds").reset_index(name="y")\nm = Prophet(yearly_seasonality=True, weekly_seasonality=True,\n            changepoint_prior_scale=0.05, interval_width=0.95)\nm.add_country_holidays(country_name="US")\nm.fit(df)\n\nfuture = m.make_future_dataframe(periods=90)     # 90 days ahead\nfc = m.predict(future)\nfc[["ds","yhat","yhat_lower","yhat_upper"]].tail()\nm.plot_components(fc)     # trend, weekly, yearly, holidays' }],
      note: 'The changepoint_prior_scale knob trades trend flexibility against overfitting: raise it if the trend is too rigid, lower it if the forecast wiggles too much.' },

    { h: 'Machine-learning forecasting: lag & rolling features + gradient boosting', p: [
      'You can turn forecasting into <b>supervised regression</b> by engineering features from the past. The target is y(t); the features are <b>lags</b> (y(t−1), y(t−7), y(t−365)), <b>rolling statistics</b> (trailing mean/std/min/max over a window), and <b>calendar features</b> (day-of-week, month, is-holiday, Fourier terms). A model like <b>gradient-boosted trees</b> (XGBoost, LightGBM) then learns non-linear interactions among them.',
      'This approach scales beautifully to <b>many related series at once</b> (thousands of products/stores in one model), ingests exogenous drivers (price, weather, promotions) naturally, and captures non-linearities that ARIMA cannot. The catch is discipline: every feature must be computable from <i>past</i> data only. A rolling mean must be <b>shifted</b> so it excludes the current row, or you leak the target. Tree models also cannot <i>extrapolate</i> a trend beyond the range they saw — detrend or difference first, or add an explicit trend feature.'],
      terms: [['Lag feature', 'the value k steps ago, y(t−k).'], ['Rolling feature', 'a statistic over a trailing window, shifted to exclude the present.'], ['Calendar feature', 'day-of-week, month, holiday flag, Fourier terms.'], ['Direct vs recursive', 'train one model per horizon vs feed predictions back as inputs for multi-step forecasts.'], ['Global model', 'one model trained across many series, sharing statistical strength.']],
      ex: [{ h: 'Building leakage-safe lag features', p: ['Note the <code>.shift(1)</code> inside the rolling feature: without it the window would include the current target and leak the answer. Split chronologically, then train a gradient-boosting regressor.'],
        code: 'import pandas as pd, lightgbm as lgb\n\ndf = y.to_frame("y")\nfor k in [1, 7, 14, 365]:\n    df[f"lag_{k}"] = df["y"].shift(k)\n# rolling stats on PAST values only (shift(1) prevents leakage)\ndf["roll_mean_7"] = df["y"].shift(1).rolling(7).mean()\ndf["roll_std_7"]  = df["y"].shift(1).rolling(7).std()\ndf["dow"]   = df.index.dayofweek\ndf["month"] = df.index.month\ndf = df.dropna()\n\ncut = "2023-01-01"\nX_tr, y_tr = df[:cut].drop(columns="y"), df[:cut]["y"]\nX_te, y_te = df[cut:].drop(columns="y"), df[cut:]["y"]\nmodel = lgb.LGBMRegressor(n_estimators=500, learning_rate=0.05)\nmodel.fit(X_tr, y_tr)\npred = model.predict(X_te)' }],
      note: 'For multi-step horizons, either train a separate model per step (direct) or feed predictions back as new lags (recursive). Direct avoids error accumulation; recursive is cheaper to maintain.' },

    { h: 'Deep learning: RNN/LSTM, N-BEATS, Temporal Fusion Transformer', p: [
      'Neural sequence models learn temporal patterns end-to-end and excel when you have <b>long histories, many related series, and rich covariates</b>. <b>RNNs</b>, and especially <b>LSTMs/GRUs</b> with their gated memory, process the sequence step by step and carry state forward, capturing longer dependencies than a plain RNN can. They need careful windowing, scaling, and plenty of data to beat well-tuned classical or boosting baselines.',
      '<b>N-BEATS</b> is a pure deep architecture of stacked fully-connected blocks with a basis-expansion (trend/seasonality) structure — strong accuracy and interpretable components, no recurrence. The <b>Temporal Fusion Transformer (TFT)</b> combines LSTM encoders with attention, and crucially separates <b>static</b> covariates, <b>known-future</b> inputs (calendar, planned promos) and <b>observed-past</b> inputs, produces <b>quantile</b> forecasts (built-in uncertainty), and offers variable-importance interpretability. Libraries like <code>darts</code>, <code>pytorch-forecasting</code>, and <code>GluonTS</code> package these.'],
      table: { cols: ['Model', 'Strength', 'Watch out for'], rows: [
        ['LSTM / GRU', 'flexible sequence memory, covariates', 'data-hungry, tuning-sensitive'],
        ['N-BEATS / N-HiTS', 'accuracy + interpretable basis, no recurrence', 'univariate focus, needs long history'],
        ['DeepAR', 'probabilistic, global over many series', 'assumes a likelihood family'],
        ['TFT', 'multi-horizon quantiles + interpretability', 'heavy, complex to configure']] },
      ex: [{ h: 'A quick deep-learning baseline with darts', p: ['darts wraps many models behind one API, so an N-BEATS baseline is a few lines. Scale inputs, fit, and forecast a horizon — then compare its backtest error against ARIMA and LightGBM before committing to the complexity.'],
        code: 'from darts import TimeSeries\nfrom darts.models import NBEATSModel\nfrom darts.dataprocessing.transformers import Scaler\n\nseries = TimeSeries.from_series(y)\ntrain, val = series[:-90], series[-90:]\nscaler = Scaler(); train_s = scaler.fit_transform(train)\n\nmodel = NBEATSModel(input_chunk_length=60, output_chunk_length=30,\n                    n_epochs=50, random_state=0)\nmodel.fit(train_s)\npred = scaler.inverse_transform(model.predict(90))' }],
      note: 'Start simple. A seasonal-naive or ARIMA baseline is often within a few percent of a heavy neural model on a single series; deep learning earns its keep on large panels of related series with covariates.' },

    { h: 'Forecast evaluation: chronological splits and rolling-origin backtesting', p: [
      'Because time is directional, evaluation must respect it. The minimum is a <b>chronological hold-out</b>: train on the earliest span, test on the most recent — never a random split. But a single split gives one noisy estimate. <b>Rolling-origin (walk-forward) backtesting</b> is the gold standard: repeatedly move the training origin forward, forecast the next block, record the error, and slide on. Averaging over many origins gives a stable, realistic estimate of live performance.',
      'Two variants: an <b>expanding window</b> keeps all history and grows the training set each step (good when older data stays relevant); a <b>sliding window</b> keeps a fixed-length recent window (good when the process drifts). Either way you must <b>refit or update</b> the model at each origin using only data available then. sklearn’s <code>TimeSeriesSplit</code> automates the index bookkeeping.'],
      eqn: 'Walk-forward:  for origin t in t₁ < t₂ < …:\n    fit on data ≤ t ,  forecast t+1 … t+h ,  score vs actuals\n    slide origin forward, repeat ;  report mean error across folds',
      ex: [{ h: 'Walk-forward backtest in code', p: ['Each fold trains only on earlier data and scores on the immediately following block — mirroring production. Report the mean and spread of the metric across folds, not a single number.'],
        code: 'import numpy as np\nfrom sklearn.model_selection import TimeSeriesSplit\nfrom sklearn.metrics import mean_absolute_error\n\ntscv = TimeSeriesSplit(n_splits=5)   # expanding window\nerrors = []\nfor tr_idx, te_idx in tscv.split(y):\n    train, test = y.iloc[tr_idx], y.iloc[te_idx]\n    m = SARIMAX(train, order=(1,1,1)).fit(disp=False)\n    pred = m.forecast(len(test))\n    errors.append(mean_absolute_error(test, pred))\nprint("MAE per fold:", np.round(errors, 2),\n      " mean:", round(np.mean(errors), 2))' }],
      note: 'Always benchmark against naive baselines: the last value (naive) and the value one season ago (seasonal-naive). If your fancy model cannot beat seasonal-naive on a walk-forward backtest, it is not adding value.' },

    { h: 'Error metrics: MAE, RMSE, MAPE, sMAPE', p: [
      'Pick the metric to match the decision. <b>MAE</b> (mean absolute error) is in the data’s units and robust to outliers. <b>RMSE</b> (root mean squared error) is also in-units but squares errors, so it punishes large misses harder — use it when big errors are disproportionately costly. Both are <b>scale-dependent</b>: you cannot compare them across series of different magnitudes.',
      'For scale-free comparison use percentage errors. <b>MAPE</b> (mean absolute percentage error) is intuitive but explodes when actuals are near zero and asymmetrically punishes over- vs under-forecasting. <b>sMAPE</b> (symmetric MAPE) bounds the denominator to reduce that asymmetry. <b>MASE</b> (mean absolute scaled error) divides MAE by the MAE of a naive forecast — below 1 means you beat naive — and is the most robust cross-series metric.'],
      eqn: 'MAE  = (1/n) Σ |y − ŷ|\nRMSE = √[ (1/n) Σ (y − ŷ)² ]\nMAPE = (100/n) Σ |y − ŷ| / |y|\nsMAPE = (100/n) Σ |y − ŷ| / ((|y| + |ŷ|)/2)',
      table: { cols: ['Metric', 'Units', 'Use when', 'Weakness'], rows: [
        ['MAE', 'data units', 'robust, interpretable typical error', 'scale-dependent'],
        ['RMSE', 'data units', 'large errors especially costly', 'outlier-sensitive, scale-dependent'],
        ['MAPE', 'percent', 'communicating relative error', 'blows up near zero, asymmetric'],
        ['sMAPE', 'percent', 'symmetric relative error', 'still unstable near zero'],
        ['MASE', 'ratio vs naive', 'comparing across many series', 'needs a naive baseline']] },
      ex: [{ h: 'Computing the metrics', p: ['Report at least one scale-dependent (MAE or RMSE) and one relative (MAPE/sMAPE/MASE) metric so both absolute size and relative accuracy are visible.'],
        code: 'import numpy as np\n\ndef mae(y, f):  return np.mean(np.abs(y - f))\ndef rmse(y, f): return np.sqrt(np.mean((y - f)**2))\ndef mape(y, f): return 100*np.mean(np.abs((y - f)/y))\ndef smape(y, f):\n    return 100*np.mean(np.abs(y - f)/((np.abs(y)+np.abs(f))/2))\n\nfor name, fn in [("MAE",mae),("RMSE",rmse),("MAPE",mape),("sMAPE",smape)]:\n    print(name, round(fn(y_true, y_pred), 3))' }],
      note: 'sMAPE is bounded roughly in [0, 200]% and treats over/under-forecasts more evenly than MAPE, but both are still unreliable when actuals can be zero — prefer MASE there.' },

    { h: 'Pitfalls: look-ahead leakage and other traps', p: [
      'The failure mode that silently ruins time-series projects is <b>look-ahead leakage</b>: any way future information sneaks into training. Common culprits: fitting a scaler or Box-Cox λ on the full dataset before splitting; rolling features that include the current row (forgot to <code>.shift</code>); target-encoding or imputation computed over all time; feature selection or hyper-parameter tuning done on the test period; or using a revised, backfilled value that was not known at forecast time (data <b>vintage</b> problems).',
      'Other classic traps: evaluating on a random split (inflates scores); ignoring that many business metrics are <b>non-stationary</b> so old accuracy overstates future accuracy; forecasting a differenced/log series and forgetting to invert; and <b>not benchmarking against naive baselines</b>, which hides that a complex model adds nothing. The defence is a single discipline: at every step ask, "was this information actually available at the moment of prediction?"'],
      terms: [['Leakage', 'future info reaching the model at training/inference time.'], ['Vintage / point-in-time', 'using the value as it was known then, not the later-revised figure.'], ['Concept drift', 'the data-generating process changes, so past accuracy overstates the future.'], ['Fit-on-train-only', 'scalers, transforms, encoders, and tuning must see training data alone.']],
      ex: [{ h: 'Leak-free scaling', p: ['Fit the scaler on the training slice only, then apply it to the test slice. Fitting on the whole series lets test-period statistics bleed into training and flatters the score.'],
        code: 'from sklearn.preprocessing import StandardScaler\n\nscaler = StandardScaler().fit(train.values.reshape(-1,1))  # train only\ntrain_s = scaler.transform(train.values.reshape(-1,1))\ntest_s  = scaler.transform(test.values.reshape(-1,1))      # reuse params' }],
      note: 'A red flag worth investigating: backtest error far lower than the eventual live error almost always traces back to leakage or a non-representative test window.' },

    { h: 'Prediction intervals and uncertainty', p: [
      'A point forecast is a guess with no honesty about risk; decisions need a <b>range</b>. A <b>prediction interval</b> gives bounds expected to contain the actual future value with a stated probability (e.g. a 95% interval). Intervals should <b>widen with the horizon</b> — the further ahead, the more uncertain — and models built on likelihoods (ARIMA, ETS, Prophet, DeepAR) provide them analytically or by simulation.',
      'When a model gives only point forecasts (e.g. gradient boosting), get uncertainty by other means: <b>quantile regression</b> (train models for the 5th and 95th percentiles via a pinball/quantile loss), <b>conformal prediction</b> (calibrate interval width from recent residuals with finite-sample coverage guarantees), or <b>bootstrapping</b> the residuals. Validate intervals by checking <b>coverage</b> — a well-calibrated 90% interval should contain the truth about 90% of the time in backtests; if it contains 70%, the intervals are overconfident.'],
      eqn: 'Gaussian PI:  ŷ(t+h) ± z_{α/2} · σ̂_h   (σ̂_h grows with h)\n90% interval => z ≈ 1.645 ;  95% => z ≈ 1.96\nCoverage check: fraction of actuals inside the interval ≈ nominal level',
      ex: [{ h: 'Quantile forecasts with gradient boosting', p: ['Train three LightGBM models — for the 5th, 50th and 95th percentiles — using the quantile objective. Together they form a point forecast plus a leak-free 90% prediction interval.'],
        code: 'import lightgbm as lgb\n\npreds = {}\nfor q in [0.05, 0.5, 0.95]:\n    m = lgb.LGBMRegressor(objective="quantile", alpha=q,\n                          n_estimators=400)\n    m.fit(X_tr, y_tr)\n    preds[q] = m.predict(X_te)\n# preds[0.5] = point ;  [preds[0.05], preds[0.95]] = 90% interval\ncoverage = ((y_te >= preds[0.05]) & (y_te <= preds[0.95])).mean()\nprint("empirical coverage:", round(coverage, 3))  # want ~0.90' }],
      note: 'Analytic ARIMA/ETS intervals assume the model and its Gaussian errors are correct and so tend to be too narrow in practice. Conformal prediction wraps any forecaster and gives distribution-free coverage guarantees.' },

    { h: 'Anomaly detection in time series', p: [
      'Anomaly detection flags observations that deviate from expected temporal behaviour — fraud spikes, sensor faults, outages, demand shocks. The core idea is <b>forecast, then compare</b>: model the normal pattern (trend + seasonality), and flag points whose actual value falls far outside the prediction interval — i.e. whose residual is large relative to its usual spread. Because "far" must account for seasonality and drift, you compare against the model’s expectation, not a global mean.',
      'Types matter: a <b>point anomaly</b> is a single outlier; a <b>contextual anomaly</b> is normal in general but abnormal for its context (30°C is fine in July, anomalous in January); a <b>collective anomaly</b> is a subsequence that is jointly unusual (a flat line where variation is expected). Methods span statistical (STL residual + robust z-score / MAD), decomposition-based (Twitter’s Seasonal-Hybrid ESD), forecasting-residual thresholds (ARIMA/Prophet), distance/density methods (isolation forest, LOF on windowed features), and reconstruction error from autoencoders/LSTMs for multivariate signals.'],
      terms: [['Point anomaly', 'a single value far from expectation.'], ['Contextual anomaly', 'unusual only given its time context (season, day).'], ['Collective anomaly', 'a subsequence that is jointly abnormal.'], ['Residual', 'actual minus forecast — the raw material for most detectors.'], ['MAD', 'median absolute deviation — a robust scale for thresholding residuals.']],
      ex: [{ h: 'STL-residual anomaly flagging', p: ['Decompose with STL, then flag points whose residual exceeds a robust threshold built from the median and MAD (robust to the very outliers you are hunting). This naturally accounts for trend and seasonality, so seasonal peaks are not falsely flagged.'],
        code: 'import numpy as np\nfrom statsmodels.tsa.seasonal import STL\n\nres = STL(y, period=12, robust=True).fit()\nr = res.resid\nmed, mad = np.median(r), np.median(np.abs(r - np.median(r)))\nrobust_z = 0.6745 * (r - med) / mad      # ~standard z via MAD\nanomalies = y[np.abs(robust_z) > 3.5]    # flag |z| > 3.5\nprint(anomalies)' }],
      note: 'Threshold choice trades precision for recall; tune it on labelled incidents if you have them, and always evaluate anomaly detectors with a time-respecting split — the same leakage rules apply.' },
  ]
});
