/* Deep dive — Transformers */
window.AtlasRef && window.AtlasRef.register('transformers', {
  color: '#A855F7',
  title: 'Transformers: attention is all you need',
  lead: 'The architecture behind GPT, BERT, Claude and every modern LLM. We build it from the ground up — why it replaced RNNs, how tokens become vectors, how self-attention lets every token look at every other token in parallel, and how stacking blocks turns that into a model that predicts the next word. Every step with exact matrix shapes, worked numbers and code.',
  sections: [

    { h: 'Why transformers replaced RNNs', p: [
      'Before 2017, sequence models were <b>recurrent</b> (RNNs, LSTMs, GRUs): they read one token at a time, carrying a hidden state forward. Two problems killed them. First, <b>no parallelism</b> — token <code>t</code> cannot be computed until token <code>t−1</code> is done, so a 1000-token sequence needs 1000 sequential steps and GPUs sit idle. Second, <b>long-range dependencies decay</b> — information from token 1 must survive being repeatedly overwritten to reach token 1000, and gradients vanish along the way.',
      'The <b>transformer</b> (Vaswani et al., <i>Attention Is All You Need</i>, 2017) throws out recurrence entirely. Every token attends to every other token <b>directly</b> in a single operation, and the whole sequence is processed <b>at once</b> as one big matrix multiply. Path length between any two tokens drops from O(n) to O(1), and training parallelises across the full sequence — the reason we can train models on trillions of tokens.'],
      table: { cols: ['Property', 'RNN / LSTM', 'Transformer'], rows: [
        ['Computation', 'sequential (token by token)', '<b>parallel</b> (whole sequence at once)'],
        ['Path between tokens i,j', 'O(|i−j|) steps', '<b>O(1)</b> — direct attention'],
        ['Long-range memory', 'decays, gradients vanish', 'flat access to all positions'],
        ['Cost per layer', 'O(n·d²)', 'O(n²·d) — quadratic in length n'],
        ['Bottleneck', 'sequence length (time)', 'context length (memory)']] },
      note: 'The trade-off: attention is O(n²) in sequence length, which is why the context window is the headline constraint of every LLM. Recurrence traded memory for time; attention trades time for memory.' },

    { h: 'Tokenization & embeddings: turning text into vectors', p: [
      'A model cannot multiply the word “cat”. Text is first split into <b>tokens</b> — sub-word chunks — by a tokenizer trained with <b>Byte-Pair Encoding (BPE)</b> or similar. Common words are one token; rare words split into pieces (“tokenization” → <code>token</code> + <code>ization</code>). A typical vocabulary has 30k–100k+ entries, each mapped to an integer <b>token ID</b>.',
      'Each ID indexes a row of the <b>embedding matrix</b> <code>E</code> of shape <code>(vocab_size, d_model)</code>. That row is a learned dense vector — the token’s starting meaning. So a sequence of <code>n</code> token IDs becomes a matrix <code>X</code> of shape <code>(n, d_model)</code>. This <code>X</code> is what flows through the whole network; everything downstream is operations on this matrix.'],
      terms: [['Token', 'a sub-word unit; the atomic input the model sees.'], ['Vocabulary', 'the fixed set of all tokens, size V (e.g. 50257 for GPT-2).'], ['d_model', 'the embedding / hidden width (e.g. 768, 4096) — same across all layers.'], ['Embedding matrix E', 'shape (V, d_model); a lookup table, learned by gradient descent.']],
      ex: [{ h: 'Text → IDs → matrix', p: ['The sentence “AI is powerful” might tokenize to 3 IDs. With <code>d_model = 4</code>, embedding lookup produces a <code>(3, 4)</code> matrix — one row per token. Real models use <code>d_model</code> in the hundreds or thousands.'],
        code: 'import numpy as np\nV, d_model = 50257, 4\nE = np.random.randn(V, d_model) * 0.02   # embedding table (V, d_model)\n\nids = [15496, 318, 3665]                  # "AI", " is", " powerful"\nX = E[ids]                               # fancy-index -> (3, 4)\nX.shape                                  # (3, 4) = (seq_len, d_model)' }] },

    { h: 'Positional encoding: injecting order', p: [
      'Self-attention is <b>permutation-invariant</b> — it treats the input as a <i>set</i>, not a sequence. “dog bites man” and “man bites dog” would look identical. Since order carries meaning, we must <b>add position information</b> to the embeddings before attention sees them.',
      'The original paper uses fixed <b>sinusoidal</b> encodings: each dimension is a sine/cosine of the position at a different frequency, giving every position a unique fingerprint and letting the model generalise to unseen lengths. Alternatives: <b>learned</b> absolute embeddings (a second lookup table, used by BERT/GPT-2); <b>RoPE</b> (Rotary Position Embedding) which <i>rotates</i> query and key vectors by an angle proportional to position so attention depends on <i>relative</i> distance — now dominant (LLaMA, most modern LLMs); and <b>ALiBi</b> which adds a distance-proportional penalty straight to the attention scores, extrapolating cleanly to longer contexts.'],
      eqn: 'PE(pos, 2i)   = sin( pos / 10000^(2i/d_model) )\nPE(pos, 2i+1) = cos( pos / 10000^(2i/d_model) )\n\nInput to layer 1:  X = TokenEmbed + PositionalEncoding      # both (n, d_model)',
      table: { cols: ['Scheme', 'Mechanism', 'Used by'], rows: [
        ['Sinusoidal', 'fixed sine/cosine of position', 'original Transformer'],
        ['Learned absolute', 'trained position lookup table', 'BERT, GPT-2'],
        ['RoPE', 'rotate Q,K by angle ∝ position (relative)', 'LLaMA, most modern LLMs'],
        ['ALiBi', 'linear distance penalty on scores', 'BLOOM, long-context models']],
      },
      ex: [{ h: 'Building sinusoidal encodings', p: ['For <code>d_model = 4</code> and a few positions, we fill a <code>(n, d_model)</code> table where even dims use sine, odd dims cosine, each at geometrically-spaced frequencies. Adding it to the token embeddings gives each position a distinct signature the model can learn to read.'],
        code: 'def positional_encoding(n, d_model):\n    pos = np.arange(n)[:, None]                 # (n, 1)\n    i   = np.arange(d_model)[None, :]           # (1, d_model)\n    angle = pos / np.power(10000, (2*(i//2))/d_model)\n    pe = np.zeros((n, d_model))\n    pe[:, 0::2] = np.sin(angle[:, 0::2])        # even dims\n    pe[:, 1::2] = np.cos(angle[:, 1::2])        # odd dims\n    return pe                                    # (n, d_model)\n\nX = X + positional_encoding(len(X), d_model)    # shapes must match' }] },

    { h: 'Self-attention: Query, Key, Value', p: [
      'Self-attention is the heart of the transformer. Each token asks: “which other tokens matter to me, and what should I pull from them?” It does this with three learned projections of the input. From <code>X</code> (shape <code>(n, d_model)</code>) we compute <b>Query</b> <code>Q = X·Wq</code>, <b>Key</b> <code>K = X·Wk</code>, and <b>Value</b> <code>V = X·Wv</code>, where each <code>W</code> is <code>(d_model, d_k)</code>, giving <code>Q,K,V</code> of shape <code>(n, d_k)</code>.',
      'A token’s <b>query</b> is compared against every token’s <b>key</b> via dot product — high dot product means “relevant to me”. Those scores are scaled by <code>√dₖ</code> (to keep the softmax from saturating when <code>dₖ</code> is large), softmaxed into a probability distribution (weights that sum to 1), and used to take a <b>weighted average of the value vectors</b>. The result: each token’s new representation is a blend of the tokens it found relevant.'],
      eqn: 'Attention(Q, K, V) = softmax( Q·Kᵀ / √dₖ ) · V\n\nshapes:  Q,K,V : (n, dₖ)      Q·Kᵀ : (n, n)      output : (n, dₖ)',
      terms: [['Query (Q)', 'what this token is looking for.'], ['Key (K)', 'what each token offers, for matching against queries.'], ['Value (V)', 'the actual content pulled from a token once matched.'], ['Scaling √dₖ', 'keeps dot-product variance ~1 so softmax gradients stay healthy.']],
      ex: [{ h: 'Computing attention weights by hand', p: ['Take 3 tokens with <code>dₖ = 2</code>. Query <code>q₁ = [1, 0]</code>. Keys: <code>k₁ = [1, 0]</code>, <code>k₂ = [0, 1]</code>, <code>k₃ = [1, 1]</code>. Raw scores are dot products: <code>q₁·k₁ = 1</code>, <code>q₁·k₂ = 0</code>, <code>q₁·k₃ = 1</code>. Scale by √2: <code>[0.707, 0, 0.707]</code>. Softmax → weights <code>[0.42, 0.16, 0.42]</code>. Token 1 splits its attention mostly between tokens 1 and 3, which its query aligned with, and largely ignores token 2.'],
        eqn: 'scores  = [1, 0, 1] / √2  = [0.707, 0, 0.707]\nweights = softmax(...)     = [0.422, 0.155, 0.422]   (sum = 1)\nout₁    = 0.422·v₁ + 0.155·v₂ + 0.422·v₃              # (2,) vector' },
        { h: 'Scaled dot-product attention in numpy', p: ['The full operation, vectorised over all 3 queries at once — no loops. Scores are <code>(3, 3)</code>, softmax each row, weighted-sum the values to a <code>(3, 2)</code> output.'],
        code: 'def softmax(x, axis=-1):\n    x = x - x.max(axis=axis, keepdims=True)\n    e = np.exp(x)\n    return e / e.sum(axis=axis, keepdims=True)\n\nQ = np.array([[1.,0.],[0.,1.],[1.,1.]])   # (3, 2)\nK = np.array([[1.,0.],[0.,1.],[1.,1.]])   # (3, 2)\nV = np.array([[10.,0.],[0.,10.],[5.,5.]]) # (3, 2)\n\nd_k = Q.shape[-1]\nscores  = Q @ K.T / np.sqrt(d_k)          # (3, 3)\nweights = softmax(scores, axis=-1)        # (3, 3), rows sum to 1\nout     = weights @ V                      # (3, 2)\nweights[0]   # -> [0.422, 0.155, 0.422]  matches the hand calc' }],
      note: 'The attention matrix Q·Kᵀ is (n, n) — one weight per pair of tokens. That n² is exactly the quadratic cost that bounds context length.' },

    { h: 'Multi-head attention', p: [
      'One attention pattern is limiting — a token may need to track syntax, a distant subject, and a coreference all at once. <b>Multi-head attention</b> runs <code>h</code> attentions in parallel, each with its own smaller <code>Wq,Wk,Wv</code> projecting to <code>d_k = d_model / h</code>. Each <b>head</b> learns a different relationship (one head tracks verbs, another tracks the previous token, another matches quotes).',
      'The <code>h</code> head outputs, each <code>(n, d_k)</code>, are <b>concatenated</b> back to <code>(n, d_model)</code> and passed through a final output projection <code>Wo</code> of shape <code>(d_model, d_model)</code>. Total parameters and compute stay roughly the same as one big head — we split the width, not add to it.'],
      eqn: 'headᵢ = Attention(X·Wqᵢ, X·Wkᵢ, X·Wvᵢ)        # each (n, d_model/h)\nMultiHead(X) = Concat(head₁ … head_h) · Wo    # (n, d_model)\n\nexample: d_model=512, h=8  ⇒  dₖ = 64 per head',
      ex: [{ h: 'Reshaping into heads', p: ['With <code>d_model = 512</code> and <code>h = 8</code>, project to <code>Q,K,V</code> of shape <code>(n, 512)</code>, then reshape to <code>(h, n, 64)</code> so the batched matmul runs all 8 heads together. After attention we transpose back and flatten to <code>(n, 512)</code>.'],
        code: 'n, d_model, h = 5, 512, 8\nd_k = d_model // h              # 64\nQ = X @ Wq                      # (n, 512)\n# split last dim into (h, d_k), move heads to front\nQh = Q.reshape(n, h, d_k).transpose(1, 0, 2)   # (h, n, d_k)\n# ... attention per head -> (h, n, d_k) ...\nout = out.transpose(1, 0, 2).reshape(n, d_model)  # (n, 512)\nout = out @ Wo                  # final mix, (n, 512)' }] },

    { h: 'The causal mask: no peeking at the future', p: [
      'A language model that predicts the next token must not see it. When predicting token <code>t</code>, attention must be restricted to positions <code>≤ t</code>. This is the <b>causal (autoregressive) mask</b>: before the softmax, every score where a query attends to a <i>future</i> key is set to <code>−∞</code>, so its softmax weight becomes 0.',
      'Concretely, we add a mask matrix to the <code>(n, n)</code> scores whose upper triangle (above the diagonal) is <code>−∞</code> and the rest is 0. This is the single difference that makes a decoder “causal”. Encoders (like BERT) skip the mask — they see the whole sequence at once, which is fine for understanding tasks but wrong for generation.'],
      eqn: 'mask[i,j] = 0     if j ≤ i   (allowed: past & present)\nmask[i,j] = −∞    if j > i   (blocked: future)\n\nweights = softmax( Q·Kᵀ/√dₖ + mask )',
      ex: [{ h: 'Building the mask', p: ['For <code>n = 4</code>, the mask keeps a lower-triangular window. After adding it, row 0 can attend only to token 0, row 1 to tokens 0–1, and so on. The <code>−1e9</code> stand-in for <code>−∞</code> drives those softmax weights to essentially zero.'],
        code: 'n = 4\nmask = np.triu(np.ones((n, n)), k=1) * -1e9   # upper tri -> -inf\n# mask =\n# [[0, -inf, -inf, -inf],\n#  [0,   0,  -inf, -inf],\n#  [0,   0,    0,  -inf],\n#  [0,   0,    0,    0 ]]\nscores  = Q @ K.T / np.sqrt(d_k) + mask       # (n, n)\nweights = softmax(scores, axis=-1)            # future weights ~ 0' }],
      note: 'BERT uses a different trick to learn bidirectionally: it masks input *tokens* (replacing them with [MASK]) rather than masking *attention*. Same word, opposite meaning.' },

    { h: 'The transformer block: residuals, layer norm & feed-forward', p: [
      'A transformer <b>block</b> wraps two sub-layers — multi-head attention and a feed-forward network — each protected by a <b>residual connection</b> and <b>layer normalization</b>. The residual (<code>x + Sublayer(x)</code>) gives gradients a highway straight through the network, making very deep stacks trainable and letting each block learn a small refinement rather than a full re-representation.',
      '<b>Layer norm</b> normalizes each token vector to zero mean and unit variance across its features, stabilizing training. Placement matters: <b>Post-LN</b> (original) applies it after the residual add; <b>Pre-LN</b> (<code>x + Sublayer(LN(x))</code>, used by GPT-2 onward) applies it inside — this is far more stable for deep models and is now standard. The <b>position-wise feed-forward network (FFN)</b> is a two-layer MLP applied to each token independently: expand to <code>d_ff</code> (typically <code>4·d_model</code>), apply a nonlinearity (ReLU/GELU), project back. It is where much of the model’s stored knowledge lives.'],
      eqn: 'Pre-LN block:\n  a = x + MultiHead( LN(x) )                 # (n, d_model)\n  y = a + FFN( LN(a) )                        # (n, d_model)\n\nFFN(z) = GELU( z·W1 + b1 )·W2 + b2\n  W1 : (d_model, d_ff)   W2 : (d_ff, d_model)   d_ff = 4·d_model',
      terms: [['Residual connection', 'x + f(x); preserves signal & gradient across depth.'], ['Layer norm', 'per-token normalization over the feature axis.'], ['FFN / MLP', 'position-wise 2-layer network; expand → nonlinearity → project.'], ['d_ff', 'the hidden width of the FFN, usually 4×d_model.']],
      ex: [{ h: 'One block in PyTorch', p: ['A complete pre-LN decoder block. Note both sub-layers follow the identical <code>x = x + sublayer(norm(x))</code> pattern; shapes stay <code>(batch, n, d_model)</code> throughout so blocks stack trivially.'],
        code: 'import torch, torch.nn as nn\nclass Block(nn.Module):\n    def __init__(self, d_model, h, d_ff):\n        super().__init__()\n        self.ln1 = nn.LayerNorm(d_model)\n        self.attn = nn.MultiheadAttention(d_model, h, batch_first=True)\n        self.ln2 = nn.LayerNorm(d_model)\n        self.ff  = nn.Sequential(\n            nn.Linear(d_model, d_ff), nn.GELU(),\n            nn.Linear(d_ff, d_model))\n    def forward(self, x, mask):\n        a = self.ln1(x)\n        x = x + self.attn(a, a, a, attn_mask=mask)[0]  # residual 1\n        x = x + self.ff(self.ln2(x))                   # residual 2\n        return x                                       # (B, n, d_model)' }] },

    { h: 'Stacking blocks & model architectures', p: [
      'A transformer is just <code>N</code> identical blocks stacked, each feeding the next, all keeping shape <code>(n, d_model)</code>. Depth builds abstraction: early layers capture surface patterns (syntax, nearby words), middle layers capture semantics, late layers capture task-level structure. GPT-2 small has 12 blocks; GPT-3 has 96; large models go deeper and wider together.',
      'Three families arrange these blocks differently for different jobs. <b>Encoder-only</b> (BERT) reads bidirectionally to <i>understand</i> — great for classification and embeddings. <b>Decoder-only</b> (GPT, Claude, LLaMA) is causally masked to <i>generate</i> — the dominant design for LLMs. <b>Encoder-decoder</b> (T5, original transformer) encodes an input then decodes an output while attending back to it via <b>cross-attention</b> — natural for translation and summarization.'],
      table: { cols: ['Family', 'Attention', 'Trained on', 'Strengths', 'Examples'], rows: [
        ['Encoder-only', 'bidirectional (no mask)', 'masked LM', 'understanding, embeddings, classification', 'BERT, RoBERTa'],
        ['Decoder-only', 'causal (masked)', 'next-token (causal LM)', 'open-ended generation, chat, few-shot', 'GPT, Claude, LLaMA'],
        ['Encoder-decoder', 'encoder full + decoder causal + cross-attn', 'span corruption / seq2seq', 'translation, summarization', 'T5, BART']] },
      note: 'Cross-attention is the same formula, but Q comes from the decoder and K,V come from the encoder output — letting the decoder read the source while writing the target.' },

    { h: 'Output layer, next-token prediction & the training objective', p: [
      'After the final block, each token position holds a <code>(n, d_model)</code> hidden state. To predict the next token, the last position’s vector is multiplied by the <b>unembedding</b> matrix (shape <code>(d_model, V)</code>, often tied to the input embedding <code>Eᵀ</code>) to produce <b>logits</b> — one raw score per vocabulary entry, shape <code>(V,)</code>. A <b>softmax</b> turns logits into a probability distribution over all <code>V</code> tokens.',
      'Generation is autoregressive: predict the next token, append it, feed the longer sequence back in, repeat. A <b>temperature</b> divides the logits before softmax (<code>&lt;1</code> sharpens/more deterministic, <code>&gt;1</code> flattens/more random); <b>top-k</b> and <b>top-p (nucleus)</b> sampling restrict the pool to the most probable tokens to avoid incoherent picks.',
      'Training is <b>self-supervised</b> — labels come free from the text. <b>Causal language modeling (CLM)</b>, used by GPT/Claude, predicts each token from all previous tokens; the loss is cross-entropy against the actual next token, averaged over every position, and thanks to the causal mask all <code>n</code> positions train in one forward pass. <b>Masked language modeling (MLM)</b>, used by BERT, hides ~15% of tokens with <code>[MASK]</code> and reconstructs them bidirectionally. CLM is generative (learns to continue text); MLM is denoising (learns to understand it); T5 blends both with <b>span corruption</b>.'],
      eqn: 'logits = h_last · Wᵤ           # (d_model,)·(d_model, V) -> (V,)\nP(next token) = softmax(logits / T)     # T<1 sharper · T→0 = greedy\n\nCausal LM loss:  L = −(1/n) Σₜ log P( xₜ | x₁ … xₜ₋₁ )    # cross-entropy\nMasked LM loss:  L = −(1/|M|) Σ_{t∈M} log P( xₜ | x_context )',
      ex: [{ h: 'From hidden state to a word', p: ['A tiny vocabulary of 5 tokens. The final hidden state yields 5 logits; softmax makes them probabilities; argmax (or sampling) picks the next token. With <code>logits = [2.0, 1.0, 0.1, 3.0, 0.5]</code>, token 3 wins with ~57% probability.'],
        code: 'vocab = ["the","cat","sat","on","mat"]\nlogits = np.array([2.0, 1.0, 0.1, 3.0, 0.5])   # (V,)\nprobs  = softmax(logits)                        # (V,)\nprobs.round(2)      # [0.21, 0.08, 0.03, 0.57, 0.05]\nvocab[int(probs.argmax())]                      # -> "on"\n\n# temperature sharpens/flattens the distribution\nT = 0.5\nsoftmax(logits / T).round(2)   # [0.17,0.02,0.00,0.80,0.01]  peakier' },
        { h: 'Causal-LM cross-entropy over a sequence', p: ['Given logits of shape <code>(n, V)</code> and the true next-token IDs (the input shifted left by one), the loss is the mean negative log-probability of the correct token at each position. This one number, backpropagated, trains the entire network.'],
        code: 'import torch\nlogits  = model(input_ids)          # (B, n, V)\ntargets = input_ids[:, 1:]          # shift left: predict next token\nlogits  = logits[:, :-1]            # align: drop last prediction\n\nloss = torch.nn.functional.cross_entropy(\n    logits.reshape(-1, logits.size(-1)),   # (B*(n-1), V)\n    targets.reshape(-1))                    # (B*(n-1),)\nloss.backward()                     # trains all positions at once' }] },

    { h: 'Context window & the KV cache', p: [
      'The <b>context window</b> is the maximum number of tokens the model can attend over at once (2k for GPT-3, 128k+ for modern models). It is bounded by the <code>O(n²)</code> attention cost and by how far positional encodings generalize. Everything the model “knows” in a conversation must fit inside it — prompt, history, and generated output share the same budget.',
      'Naive generation recomputes attention over the entire growing sequence at every step — <code>O(n²)</code> repeated <code>n</code> times. The <b>KV cache</b> fixes this: since past tokens never change under a causal mask, we <b>store</b> each layer’s Key and Value tensors and, for each new token, compute only its Q,K,V and append. Generation drops to <code>O(n)</code> per token. The cost is memory: cache size is <code>2 · layers · heads · d_k · n</code> per sequence, which is why long contexts are expensive to <i>serve</i>, not just to train.'],
      eqn: 'Without cache:  step t recomputes attention over t tokens  → O(n²) total\nWith KV cache:  step t reuses cached K,V, adds 1 row         → O(n) total\n\ncache memory ≈ 2 · n_layers · n_heads · d_k · seq_len · dtype_bytes',
      ex: [{ h: 'Caching keys and values', p: ['At each generation step we concatenate the new token’s K and V onto the cache, so attention sees the full history without recomputing it. The query is only the single newest token.'],
        code: 'k_cache, v_cache = None, None\nfor step in range(max_new_tokens):\n    q, k, v = project(new_token)        # each (1, d_k) — just 1 token\n    k_cache = k if k_cache is None else np.vstack([k_cache, k])\n    v_cache = v if v_cache is None else np.vstack([v_cache, v])\n    scores  = q @ k_cache.T / np.sqrt(d_k)   # (1, t): new token vs all past\n    out     = softmax(scores) @ v_cache      # (1, d_k)\n    new_token = sample(out)                  # feed back in' }],
      note: 'FlashAttention, sliding-window attention, and GQA (grouped-query attention) are all engineering tricks to push n larger or shrink the KV cache without changing the math above.' },

    { h: 'Scaling & emergent abilities', p: [
      'Transformer performance improves <b>predictably</b> with scale. The <b>scaling laws</b> (Kaplan et al.; Chinchilla) show test loss falls as a smooth power law in three quantities: <b>parameters</b> N, <b>data</b> D, and <b>compute</b> C. Chinchilla’s key correction: most early large models were under-trained — for a fixed compute budget you should scale parameters and tokens <i>together</i> (roughly 20 tokens per parameter), not just grow the model.',
      'More striking are <b>emergent abilities</b>: capabilities that are near-random at small scale then appear relatively sharply past a threshold — multi-step arithmetic, in-context learning (learning a task from examples in the prompt with no weight updates), chain-of-thought reasoning, instruction following. They are not explicitly trained; they fall out of next-token prediction at scale. This is the empirical bet behind frontier models: predict the next token well enough, at enough scale, and general capabilities emerge.'],
      eqn: 'Loss(N) ≈ (Nc / N)^αₙ        power law in parameters\nChinchilla-optimal:  D ≈ 20 · N     (tokens ≈ 20 × parameters)',
      table: { cols: ['Model', 'Parameters', 'Context', 'Layers'], rows: [
        ['GPT-2', '1.5B', '1024', '48'],
        ['GPT-3', '175B', '2048', '96'],
        ['LLaMA-2 70B', '70B', '4096', '80'],
        ['Frontier LLMs', 'hundreds of B–T+', '128k–1M+', '80–120+']] },
      note: 'Scaling laws are why the field pours compute into ever-larger runs: the return on scale has been remarkably smooth and — so far — not saturated.' },

    { h: 'Embeddings for retrieval & RAG', p: [
      'The same machinery that powers generation also produces <b>embeddings</b> — dense vectors capturing meaning — which drive <b>semantic search</b> and <b>Retrieval-Augmented Generation (RAG)</b>. RAG gives an LLM knowledge it was never trained on (private docs, fresh data) by <i>retrieving</i> relevant text and putting it in the context window, sidestepping the context limit and reducing hallucination.',
      'The pipeline: (1) <b>chunk</b> documents into passages (a few hundred tokens, often overlapping so ideas aren’t split); (2) <b>embed</b> each chunk with an embedding model and store the vectors in a <b>vector database</b> (FAISS, Pinecone, pgvector) with an ANN index for fast search; (3) at query time, embed the question and retrieve the top-k chunks by <b>cosine similarity</b>; (4) optionally <b>re-rank</b> the candidates with a cross-encoder for precision; (5) stuff the best chunks into the prompt and let the LLM answer grounded in them.'],
      eqn: 'cosine_sim(a, b) = (a · b) / (|a| · |b|)     # 1 = identical, 0 = unrelated\n\nretrieve: top-k chunks maximizing cosine_sim(embed(query), embed(chunk))',
      terms: [['Chunking', 'splitting docs into passages, usually with overlap.'], ['Vector DB', 'stores embeddings + approximate-nearest-neighbor index.'], ['Cosine similarity', 'direction-only match between query and chunk vectors.'], ['Re-ranking', 'a slower cross-encoder re-scores top candidates for precision.']],
      ex: [{ h: 'A minimal RAG retrieval step', p: ['Embed a query, score it against a store of chunk embeddings by cosine similarity, and return the top-k. Bi-encoder retrieval is fast (precompute chunk vectors once); a cross-encoder re-ranker would then re-score just these few for the final ordering.'],
        code: 'def cosine(a, B):                       # a:(d,)  B:(m,d)\n    a = a / np.linalg.norm(a)\n    B = B / np.linalg.norm(B, axis=1, keepdims=True)\n    return B @ a                        # (m,) similarity per chunk\n\nq_vec   = embed(query)                  # (d,)\nchunk_M = np.stack([embed(c) for c in chunks])   # (m, d)\nscores  = cosine(q_vec, chunk_M)        # (m,)\ntop_k   = np.argsort(-scores)[:5]       # indices of 5 best chunks\ncontext = "\\n".join(chunks[i] for i in top_k)\nanswer  = llm(f"Answer using:\\n{context}\\n\\nQ: {query}")' }],
      note: 'RAG vs fine-tuning: RAG injects *knowledge* at query time (cheap to update, cites sources); fine-tuning changes *behavior/style* by updating weights. Production systems often use both.' },
  ]
});
