/* Deep dive — Explainable AI (XAI) & interpretability */
window.AtlasRef && window.AtlasRef.register('xai', {
  color: '#F59E0B',
  title: 'Opening the black box',
  lead: 'Modern models predict brilliantly and explain nothing. Explainable AI is the discipline of recovering the <i>why</i> — from linear coefficients you can read at a glance to Shapley values, saliency maps and the mechanistic circuits inside large language models. This is the full course: the taxonomy, the mathematics of the leading methods, worked examples, code, and an honest account of where explanations mislead.',
  sections: [

    { h: 'Why explainability matters', p: [
      'A model that is accurate but inscrutable is a liability wherever its decisions touch people. Explainability buys four things. <b>Trust & adoption</b>: clinicians, loan officers and judges will not act on a number they cannot interrogate. <b>Debugging</b>: the only way to catch a model that is right for the wrong reason — the classic case of a pneumonia detector that keyed on the hospital‑specific metadata token in the scan rather than the lungs. <b>Fairness</b>: you cannot audit for discrimination you cannot see. <b>Regulation</b>: law increasingly demands it.',
      'The EU’s <b>GDPR</b> (Arts. 13–15 and 22, with Recital 71) grants data subjects <i>meaningful information about the logic involved</i> in automated decisions — widely discussed as a limited <b>“right to explanation.”</b> The <b>EU AI Act</b> layers transparency and human‑oversight duties on high‑risk systems, and sector rules like the US <b>Equal Credit Opportunity Act</b> already require <i>adverse‑action reasons</i> for a declined loan. Explainability is no longer optional infrastructure.'],
      terms: [['Transparency', 'the model’s mechanism is inspectable by design.'], ['Interpretability', 'a human can grasp the cause of a decision.'], ['Explainability', 'post‑hoc tools reconstruct a reason for an opaque model.'], ['Right to explanation', 'the (contested) legal claim to know the logic of an automated decision.']],
      note: 'Interpretability and accuracy are often, but not always, in tension — the “accuracy–interpretability trade‑off.” For structured/tabular data a well‑regularised interpretable model frequently matches a black box, so the trade‑off is smaller than assumed.' },

    { h: 'A taxonomy of explanation methods', p: [
      'Four axes organise the whole field, and every method sits at a coordinate. <b>Scope</b> — a <i>global</i> explanation describes the model’s overall behaviour; a <i>local</i> one explains a single prediction. <b>Intrinsic vs post‑hoc</b> — an <i>intrinsic</i> model is transparent by construction (you read the model itself); a <i>post‑hoc</i> method probes an already‑trained black box from outside. <b>Model‑specific vs model‑agnostic</b> — a specific method exploits internals (gradients, tree structure); an agnostic method treats the model as a query‑only oracle and so works on anything.',
      'These are not mutually exclusive: SHAP is post‑hoc, local (aggregable to global) and has both agnostic and model‑specific variants; a decision tree is intrinsic and global. Choosing a method starts by fixing the coordinate you need.'],
      table: { cols: ['Method', 'Scope', 'Intrinsic / post‑hoc', 'Agnostic?'], rows: [
        ['Linear coefficients', 'global', 'intrinsic', 'specific'],
        ['Decision tree path', 'local + global', 'intrinsic', 'specific'],
        ['Permutation importance', 'global', 'post‑hoc', 'agnostic'],
        ['LIME', 'local', 'post‑hoc', 'agnostic'],
        ['SHAP (Kernel)', 'local → global', 'post‑hoc', 'agnostic'],
        ['Grad‑CAM', 'local', 'post‑hoc', 'specific (CNNs)'],
        ['Integrated Gradients', 'local', 'post‑hoc', 'specific (differentiable)']] },
      note: 'A useful rule of thumb: reach for an intrinsic model first; only escalate to post‑hoc explanation when a black box is genuinely necessary for accuracy.' },

    { h: 'Intrinsically interpretable models', p: [
      'Some models <i>are</i> their own explanation. In <b>linear/logistic regression</b> the weight βⱼ is the effect of feature j holding others fixed; for logistic regression exp(βⱼ) is an <b>odds ratio</b>. In a <b>decision tree</b> a prediction is a readable path of if‑then rules from root to leaf. <b>Generalised Additive Models (GAMs)</b> keep the additive, per‑feature transparency of a linear model while letting each feature contribute a nonlinear shape fⱼ(xⱼ) — you can plot exactly how the model responds to each variable.',
      'The catch: interpretability degrades with size. A depth‑3 tree is a diagram; a depth‑30 tree or a 50‑term interaction is not. Sparsity and depth limits are what keep these models honest.'],
      eqn: 'linear:      ŷ = β₀ + Σⱼ βⱼ xⱼ\nlogistic:    p = σ(β₀ + Σⱼ βⱼ xⱼ),   odds ratio = exp(βⱼ)\nGAM:         g(E[y]) = β₀ + Σⱼ fⱼ(xⱼ)          (each fⱼ plottable)',
      ex: [{ h: 'Reading a logistic coefficient', p: ['A credit model has β = 0.69 on <code>num_late_payments</code>. Then exp(0.69) ≈ 2.0: each additional late payment <b>doubles the odds</b> of default, all else equal. That single sentence is the whole explanation — no external tool required.'],
        eqn: 'exp(0.69) ≈ 2.0   ⇒   +1 late payment doubles the odds of default',
        code: 'from sklearn.linear_model import LogisticRegression\nimport numpy as np\nclf = LogisticRegression().fit(X, y)\nfor name, b in zip(feature_names, clf.coef_[0]):\n    print(f"{name:20s}  beta={b:+.2f}  odds_ratio={np.exp(b):.2f}")' }] },

    { h: 'Feature importance & permutation importance', p: [
      'A <b>global</b> question: which features does the model actually rely on? <b>Permutation importance</b> answers it model‑agnostically. Take a fitted model and a held‑out set, measure the baseline score, then <b>shuffle one feature’s column</b> (breaking its link to the target while preserving its marginal distribution) and re‑score. The drop in performance is that feature’s importance. Repeat per feature, average over several shuffles.',
      'It is honest about <i>what the model uses</i>, not what is causally true. Two big caveats: importances are measured on whatever data you pass (use test data to see generalisation), and <b>correlated features</b> share credit — permuting one while its correlated twin stays intact understates both.'],
      eqn: 'imp(j) = s_base − (1/K) Σₖ s(model, X with column j shuffled)',
      ex: [{ h: 'Permutation importance on a churn model', p: ['A gradient‑boosted churn classifier scores 0.86 AUC. Shuffling <code>tenure</code> drops it to 0.71 (importance 0.15); shuffling <code>region</code> barely moves it (0.002). Conclusion: tenure carries the signal, region is nearly ignored — a candidate for removal to simplify the model.'],
        code: 'from sklearn.inspection import permutation_importance\nr = permutation_importance(model, X_test, y_test,\n                           scoring="roc_auc",\n                           n_repeats=20, random_state=0)\nfor i in r.importances_mean.argsort()[::-1]:\n    print(f"{feature_names[i]:15s} {r.importances_mean[i]:.3f} "\n          f"+/- {r.importances_std[i]:.3f}")' }],
      note: 'Prefer permutation importance over a tree’s built‑in <code>feature_importances_</code> (mean decrease in impurity), which is biased toward high‑cardinality and continuous features.' },

    { h: 'SHAP — Shapley values & additive attribution', p: [
      'SHAP borrows the <b>Shapley value</b> from cooperative game theory. Imagine the features are players cooperating to produce the prediction; the Shapley value φⱼ is player j’s fair share of the payout, defined as its <b>average marginal contribution across every possible ordering</b> in which features are added to the coalition. It is the <i>unique</i> attribution satisfying efficiency, symmetry, dummy and additivity axioms.',
      'The payoff for ML is the <b>additive‑attribution / local‑accuracy</b> property: for any single prediction the feature contributions sum exactly to the prediction minus the baseline. Nothing is lost or invented — every explanation is a complete budget. This is what makes SHAP both locally faithful and globally aggregable (mean |φⱼ| across a dataset gives a principled global importance).'],
      eqn: 'φⱼ = Σ_{S⊆F∖{j}}  [ |S|!(|F|−|S|−1)! / |F|! ] · ( f(S∪{j}) − f(S) )\n\nlocal accuracy:   f(x) = φ₀ + Σⱼ φⱼ ,    φ₀ = E[f(X)]  (the baseline)',
      ex: [{ h: 'A three‑feature budget that sums to the prediction', p: ['A model predicts a house price of <b>$420k</b>; the dataset baseline (average prediction) is <b>$300k</b>. SHAP splits the +$120k gap: <code>size</code> = +$90k, <code>location</code> = +$40k, <code>old_roof</code> = −$10k. They sum exactly: 300 + 90 + 40 − 10 = 420. You can read each feature’s dollar push for <i>this</i> house — the essence of a local explanation.'],
        eqn: 'φ₀=300k  +size 90k  +location 40k  −roof 10k  =  ŷ 420k',
        code: 'import shap\nexplainer = shap.TreeExplainer(model)      # fast exact SHAP for trees\nsv = explainer(X_test)                      # Explanation object\nshap.plots.waterfall(sv[0])                 # local: one prediction\nshap.plots.beeswarm(sv)                      # global: whole dataset\nprint(sv[0].values.sum() + sv[0].base_values, model.predict(X_test[:1]))  # equal' }],
      note: 'Exact Shapley values cost 2^F evaluations. KernelSHAP approximates them for any model via weighted local regression; TreeSHAP computes them exactly and fast for tree ensembles.' },

    { h: 'LIME — local surrogate models', p: [
      'LIME (Local Interpretable Model‑agnostic Explanations) asks a narrower question than SHAP: <i>near this one point</i>, what simple model imitates the black box? It <b>perturbs</b> the instance to generate a cloud of nearby samples, labels them with the black box, weights them by proximity to the original point, and fits a <b>sparse linear surrogate</b> on that weighted neighbourhood. The surrogate’s coefficients are the explanation — locally faithful even if the global model is wildly nonlinear.',
      'Strengths: model‑agnostic, works on tabular, text (word presence) and images (superpixels). Weaknesses: the explanation depends heavily on the perturbation distribution and kernel width, and can be <b>unstable</b> — re‑running on the same point may yield different coefficients. Treat LIME as a local sketch, not a guarantee.'],
      eqn: 'ξ(x) = argmin_{g∈G}  L(f, g, πₓ) + Ω(g)\n   f = black box,  g = interpretable surrogate,  πₓ = locality weight,  Ω = complexity penalty',
      ex: [{ h: 'Explaining one text classification', p: ['A spam classifier flags an email. LIME perturbs it by deleting random words, sees which deletions most change the score, and reports the local weights: <code>free</code> +0.42, <code>winner</code> +0.31, <code>meeting</code> −0.12. The user sees the exact words that tipped <i>this</i> message into spam.'],
        code: 'from lime.lime_text import LimeTextExplainer\nexplainer = LimeTextExplainer(class_names=["ham", "spam"])\nexp = explainer.explain_instance(email_text,\n                                 clf.predict_proba,\n                                 num_features=6)\nprint(exp.as_list())   # [("free", 0.42), ("winner", 0.31), ...]' }] },

    { h: 'Partial dependence (PDP) & ICE curves', p: [
      'To see the <b>shape</b> of a feature’s effect globally, a <b>Partial Dependence Plot</b> sweeps feature j across its range, and at each value averages the model’s prediction over all other features in the dataset. The resulting curve shows the average marginal effect — is the relationship linear, a threshold, U‑shaped?',
      '<b>Individual Conditional Expectation (ICE)</b> curves are the un‑averaged version: one line per instance. They reveal <b>heterogeneity and interactions</b> that a PDP hides — if the ICE lines fan out or cross, the feature’s effect depends on other features, and the single PDP average is misleading. The known flaw of PDPs: they assume feature independence, so averaging over unrealistic feature combinations (e.g. 2‑metre‑tall, 30‑kg people) can distort the curve.'],
      eqn: 'PDP:  f̄_S(x_S) = (1/n) Σᵢ f( x_S , x_C⁽ⁱ⁾ )      (average over the other features x_C)\nICE:  one curve  f( x_S , x_C⁽ⁱ⁾ )  per instance i',
      ex: [{ h: 'Reading a PDP + ICE together', p: ['A bike‑rental model’s PDP for <code>temperature</code> rises then falls — demand peaks around 20 °C. But the ICE curves split into two bundles: casual riders (steep temperature sensitivity) and commuters (flat). The averaged PDP alone would have hidden that the effect is entirely driven by one segment.'],
        code: 'from sklearn.inspection import PartialDependenceDisplay\nPartialDependenceDisplay.from_estimator(\n    model, X, features=["temperature"],\n    kind="both")   # "both" overlays ICE lines on the PDP average' }] },

    { h: 'Counterfactual explanations', p: [
      'A counterfactual answers the question people actually ask after a rejection: <b>“what is the smallest change that would flip the decision?”</b> Rather than attributing the current outcome, it names an actionable alternative — <i>“had your income been $4k higher, the loan would have been approved.”</i> This is contrastive, recourse‑oriented, and maps directly onto adverse‑action requirements.',
      'Formally, find x′ close to x (small, sparse, plausible change) whose prediction is the desired class. Good counterfactuals are <b>actionable</b> (don’t ask a user to become younger), <b>sparse</b> (change few features), and <b>plausible</b> (stay on the data manifold). Many counterfactuals exist for one point — a strength (offer options) and a subtlety (which to show?).'],
      eqn: 'x′ = argmin_{x′}  d(x, x′)      subject to   f(x′) = desired outcome\n   d = distance that rewards small, sparse, realistic edits',
      ex: [{ h: 'Recourse for a declined loan', p: ['Applicant declined. A counterfactual search finds the minimal flip: raise <code>annual_income</code> from $38k → $42k <b>or</b> lower <code>credit_utilisation</code> from 75% → 60%. Either single change crosses the approval boundary, giving the applicant concrete, actionable recourse instead of an opaque “no.”'],
        code: 'import dice_ml\nd = dice_ml.Data(dataframe=df, continuous_features=cont, outcome_name="approved")\nm = dice_ml.Model(model=model, backend="sklearn")\nexp = dice_ml.Dice(d, m, method="random")\ncf = exp.generate_counterfactuals(x_query, total_CFs=3,\n                                  desired_class="opposite")\ncf.visualize_as_dataframe()' }] },

    { h: 'Explaining deep vision models: saliency, Grad‑CAM, integrated gradients', p: [
      'For image models the natural explanation is a <b>heatmap over pixels</b>. The simplest is a <b>vanilla saliency map</b>: the gradient of the output class score w.r.t. the input pixels — “which pixels, if nudged, most change the score.” Raw gradients are noisy, motivating better methods.',
      '<b>Grad‑CAM</b> uses the gradients flowing into the last convolutional layer to weight its feature maps, producing a coarse, class‑discriminative heatmap localised on the object — robust and the vision default. <b>Integrated Gradients</b> fixes gradient saturation by integrating gradients along a straight path from a baseline (usually black) to the input; it satisfies a <b>completeness</b> axiom analogous to SHAP: the attributions sum to the score difference f(x) − f(baseline).'],
      eqn: 'saliency:   M = |∂ y_c / ∂ x|\nGrad‑CAM:   L_c = ReLU( Σ_k α_kᶜ A^k ),  α_kᶜ = global‑avg‑pool( ∂y_c/∂A^k )\nIntegratedGrads_j = (x_j − x′_j) · ∫₀¹ ∂f(x′ + α(x−x′))/∂x_j  dα',
      ex: [{ h: 'Catching a “Clever Hans” model', p: ['A husky‑vs‑wolf classifier reports 90% accuracy. Grad‑CAM heatmaps reveal the model is highlighting <b>snow in the background</b>, not the animal — wolves happened to be photographed in snow. The explanation exposes a spurious correlation that the accuracy number completely hid.'],
        code: 'from pytorch_grad_cam import GradCAM\nfrom pytorch_grad_cam.utils.image import show_cam_on_image\ncam = GradCAM(model=model, target_layers=[model.layer4[-1]])\ngrayscale = cam(input_tensor=img, targets=None)[0]     # HxW heatmap\nvis = show_cam_on_image(rgb_img, grayscale, use_rgb=True)' }] },

    { h: 'Interpreting attention, and mechanistic interpretability for LLMs', p: [
      'For transformers the tempting explanation is <b>attention weights</b> — how much each token attended to each other token, cheap to visualise and sometimes revealing structure. But <b>“attention is not explanation”</b> is a well‑supported warning: attention is one component of a deep nonlinear computation, and one can often find <b>alternative attention distributions</b> yielding the same output, so high attention does not reliably mean high causal importance. Use it as a hypothesis generator, then verify causally.',
      '<b>Mechanistic interpretability (MI)</b> goes deeper — it aims to <b>reverse‑engineer the actual algorithm</b> a network implements. The <b>logit lens</b> projects hidden states at each layer through the unembedding to watch the prediction form layer by layer. <b>Circuits</b> are small, human‑understandable subgraphs of attention heads and MLP neurons implementing a specific behaviour — the canonical <b>induction heads</b> complete repeated patterns ([A][B] … [A] → [B]) and underpin much in‑context learning.',
      'The central obstacle is <b>superposition</b>: networks pack more features than they have neurons, so single neurons are <b>polysemantic</b> (fire for many unrelated concepts). <b>Sparse autoencoders (SAEs)</b> attack this by learning an overcomplete, sparse dictionary that decomposes activations into many <b>monosemantic features</b> — interpretable, and in Anthropic’s work steerable (amplify a feature to change behaviour). MI is young and labour‑intensive but is the most promising route to genuine, causal understanding of LLMs.'],
      terms: [['Logit lens', 'decode intermediate layers with the output head to see the prediction emerge.'], ['Circuit', 'a minimal subgraph of heads/MLPs implementing one behaviour.'], ['Induction head', 'a head that copies/continues repeated sequences; a core in‑context‑learning mechanism.'], ['Superposition', 'more features than neurons, forcing overlap.'], ['SAE feature', 'a sparse, often monosemantic direction recovered from activations.']],
      ex: [{ h: 'Activation patching to localise a behaviour', p: ['To test whether a specific head causes a factual recall, run the model on a clean prompt and a corrupted one, then <b>patch</b> the clean head’s activation into the corrupted run. If the correct answer is restored, that head causally carries the information — a rigorous, causal alternative to eyeballing attention.'],
        code: '# sketch with TransformerLens\nfrom transformer_lens import HookedTransformer\nmodel = HookedTransformer.from_pretrained("gpt2-small")\n_, clean_cache = model.run_with_cache(clean_tokens)\n\ndef patch_head(act, hook, head=5):\n    act[:, :, head, :] = clean_cache[hook.name][:, :, head, :]\n    return act\n\nlogits = model.run_with_hooks(corrupted_tokens,\n    fwd_hooks=[("blocks.9.attn.hook_z", patch_head)])\n# recovery of the correct logit  =>  head 9.5 is causal' }] },

    { h: 'Fairness auditing with explanations', p: [
      'Explainability and fairness are siblings: attributions reveal <i>whether a protected attribute (or its proxy) drives decisions</i>, and group‑wise metrics reveal <i>whether outcomes differ across groups</i>. A model can be accurate overall yet fail a subgroup — SHAP or permutation importance can expose reliance on a proxy like ZIP code, while metrics like <b>demographic parity difference</b> and <b>equalized‑odds difference</b> quantify disparate impact.',
      'Two toolkits industrialise this. <b>Fairlearn</b> (Microsoft) provides metrics (<code>MetricFrame</code>) and mitigation (reductions, post‑processing to equalize odds). <b>AIF360</b> (IBM) offers a broad library of fairness metrics and pre/in/post‑processing mitigators. Explanation tells you the mechanism; fairness metrics tell you the harm; together they support an audit.'],
      eqn: 'demographic parity diff = | P(ŷ=1 | A=a) − P(ŷ=1 | A=b) |\nequalized odds diff     = max over y of | TPR_a − TPR_b |, | FPR_a − FPR_b |',
      ex: [{ h: 'Auditing selection rate across groups', p: ['A hiring model is approved by overall accuracy, but a Fairlearn <code>MetricFrame</code> shows the selection rate is 0.62 for group A and 0.31 for group B — a demographic‑parity difference of 0.31. SHAP then reveals the driver is <code>years_gap</code>, a proxy correlated with the protected attribute. Explanation + metric together locate both the disparity and its cause.'],
        code: 'from fairlearn.metrics import MetricFrame, selection_rate, demographic_parity_difference\nmf = MetricFrame(metrics=selection_rate,\n                 y_true=y_test, y_pred=y_pred,\n                 sensitive_features=A_test)\nprint(mf.by_group)                       # rate per group\nprint(demographic_parity_difference(\n        y_test, y_pred, sensitive_features=A_test))' }] },

    { h: 'Limitations & pitfalls: explanations can mislead', p: [
      'The most important lesson in XAI is skepticism about XAI. Explanations are themselves <b>models of a model</b>, and they fail in characteristic ways. <b>Unfaithfulness</b>: a plausible‑looking heatmap or coefficient may not reflect the true computation — some saliency methods pass sanity checks no better than an edge detector and are invariant to randomising the model’s weights. <b>Instability</b>: LIME and gradient maps can change under tiny input or seed perturbations. <b>Adversarial explanations</b>: attributions can be deliberately manipulated to hide bias (“fairwashing”) while leaving predictions intact.',
      'Correlated features fool importance methods; PDPs assume independence; attention is not causal; and a confident explanation can manufacture false trust — arguably worse than no explanation. Practical hygiene: prefer intrinsic models when you can, <b>triangulate</b> across multiple methods, validate faithfulness (deletion/insertion metrics, sanity checks, causal patching), and always ask <i>who</i> the explanation is for and <i>what decision</i> it must support.'],
      terms: [['Faithfulness', 'the explanation matches the model’s real reasoning.'], ['Sanity check', 'randomise weights/labels; a good method’s output should change.'], ['Fairwashing', 'crafting benign explanations that mask a biased model.'], ['Deletion/insertion', 'remove/add the “important” features and check the score responds.']],
      note: 'A good explanation is a means to a decision — auditing, debugging, recourse — not an end. Judge it by whether it improves that decision, and verify before you trust.' },
  ]
});
